In [13]:
import soccerdata as sd

season = 2023

fbref = sd.FBref(leagues="ENG-Premier League", seasons=season)

team_match_stats = fbref.read_team_match_stats(stat_type="schedule", team="Manchester City")
team_match_stats.head()

[01/09/26 16:03:07] INFO     Saving cached data to C:\Users\Adam\soccerdata\data\FBref               ]8;id=719825;file://e:\anacoda3\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=127253;file://e:\anacoda3\Lib\site-packages\soccerdata\_common.py#263\263]8;;\

                    WARNING  e:\anacoda3\Lib\site-packages\soccerdata\fbref.py:165: FutureWarning:  ]8;id=194501;file://e:\anacoda3\Lib\warnings.py\warnings.py]8;;\:]8;id=835139;file://e:\anacoda3\Lib\warnings.py#112\112]8;;\
                             The behavior of DataFrame concatenation with empty or all-NA entries
                             is deprecated. In a future version, this will no longer exclude empty
                             or all-NA columns when determining the result dtypes. To retain the
                             old behavior, exclude the relevant entries before the concat
                             operation.
                               pd.concat(dfs)

                                                                                         date  \
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City       2023-08-11
                                          2023-08-19 Manchester City-Newcastle Utd 2023-08-19
                                          2023-08-27 Sheffield Utd-Manchester City 2023-08-27
                                          2023-09-02 Manchester City-Fulham        2023-09-02
                                          2023-09-16 West Ham-Manchester City      2023-09-16

                                                                                        time  \
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City        20:00:00
                                          2023-08-19 Manchester City-Newcastle Utd  20:00:00
                                          2023-08-27 Sheffield Utd-Manchester City  14:00:00
                                          2023-09-02 Manchester City-Fulham         15:00:00
                                          2023-09-16 West Ham-Manchester City       15:00:00

                                                                                          round  \
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City        Matchweek 1
                                          2023-08-19 Manchester City-Newcastle Utd  Matchweek 2
                                          2023-08-27 Sheffield Utd-Manchester City  Matchweek 3
                                          2023-09-02 Manchester City-Fulham         Matchweek 4
                                          2023-09-16 West Ham-Manchester City       Matchweek 5

                                                                                    day  \
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City        Fri
                                          2023-08-19 Manchester City-Newcastle Utd  Sat
                                          2023-08-27 Sheffield Utd-Manchester City  Sun
                                          2023-09-02 Manchester City-Fulham         Sat
                                          2023-09-16 West Ham-Manchester City       Sat

                                                                                   venue  \
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City        Away
                                          2023-08-19 Manchester City-Newcastle Utd  Home
                                          2023-08-27 Sheffield Utd-Manchester City  Away
                                          2023-09-02 Manchester City-Fulham         Home
                                          2023-09-16 West Ham-Manchester City       Away

                                                                                   result  \
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City            W
                                          2023-08-19 Manchester City-Newcastle Utd      W
                                          2023-08-27 Sheffield Utd-Manchester City      W
                                          2023-09-02 Manchester City-Fulham             W
                                          2023-09-16 West Ham-Manchester City           W

                                                                                   GF  \
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City        3
                                          2023-08-19 Manchester City-Newcastle Utd  1
                                          2023-08-27 Sheffield Utd-Manchester City  2
                                          2023-09-02 Manchester City-Fulham         5
                                          2023-09-16 West Ham-Manchester City       3

                                                                                   GA  \
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City        0
                                          2023-08-19 Manchester City-Newcastle Utd  0
                                          2023-08-27 Sheffield Utd-Manchester City  1
                                          2023-09-02 Manchester City-Fulham         1
                                          2023-09-16 West Ham-Manchester City       1

                                                                                         opponent  \
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City              Burnley
                                          2023-08-19 Manchester City-Newcastle Utd  Newcastle Utd
                                          2023-08-27 Sheffield Utd-Manchester City  Sheffield Utd
                                          2023-09-02 Manchester City-Fulham                Fulham
                                          2023-09-16 West Ham-Manchester City            West Ham

                                                                                     xG  \
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City        1.9
                                          2023-08-19 Manchester City-Newcastle Utd  1.0
                                          2023-08-27 Sheffield Utd-Manchester City  3.5
                                          2023-09-02 Manchester City-Fulham         2.2
                                          2023-09-16 West Ham-Manchester City       3.6

                                                                                    xGA  \
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City        0.3
                                          2023-08-19 Manchester City-Newcastle Utd  0.3
                                          2023-08-27 Sheffield Utd-Manchester City  0.7
                                          2023-09-02 Manchester City-Fulham         1.4
                                          2023-09-16 West Ham-Manchester City       0.9

                                                                                    Poss  \
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City          65
                                          2023-08-19 Manchester City-Newcastle Utd    59
                                          2023-08-27 Sheffield Utd-Manchester City    79
                                          2023-09-02 Manchester City-Fulham           68
                                          2023-09-16 West Ham-Manchester City         68

                                                                                    Attendance  \
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City             21572
                                          2023-08-19 Manchester City-Newcastle Utd       53419
                                          2023-08-27 Sheffield Utd-Manchester City       31336
                                          2023-09-02 Manchester City-Fulham              52899
                                          2023-09-16 West Ham-Manchester City            62475

                                                                                            Captain  \
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City        Kevin De Bruyne
                                          2023-08-19 Manchester City-Newcastle Utd      Kyle Walker
                                          2023-08-27 Sheffield Utd-Manchester City      Kyle Walker
                                          2023-09-02 Manchester City-Fulham             Kyle Walker
                                          2023-09-16 West Ham-Manchester City           Kyle Walker

                                                                                   Formation  \
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City         4-2-3-1
                                          2023-08-19 Manchester City-Newcastle Utd   4-2-3-1
                                          2023-08-27 Sheffield Utd-Manchester City   4-2-3-1
                                          2023-09-02 Manchester City-Fulham          4-2-3-1
                                          2023-09-16 West Ham-Manchester City        4-2-3-1

                                                                                   Opp Formation  \
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City               5-4-1
                                          2023-08-19 Manchester City-Newcastle Utd         4-3-3
                                          2023-08-27 Sheffield Utd-Manchester City         3-5-2
                                          2023-09-02 Manchester City-Fulham                4-3-3
                                          2023-09-16 West Ham-Manchester City            4-2-3-1

                                                                                           Referee  \
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City          Craig Pawson
                                          2023-08-19 Manchester City-Newcastle Utd    Robert Jones
                                          2023-08-27 Sheffield Utd-Manchester City  Jarred Gillett
                                          2023-09-02 Manchester City-Fulham         Michael Oliver
                                          2023-09-16 West Ham-Manchester City          Andy Madley

                                                                                                                         match_report  \
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City        /en/matches/3a6836b4/Burnley-Manchester-City-A...
                                          2023-08-19 Manchester City-Newcastle Utd  /en/matches/0b8f50a5/Manchester-City-Newcastle...
                                          2023-08-27 Sheffield Utd-Manchester City  /en/matches/0844ff10/Sheffield-United-Manchest...
                                          2023-09-02 Manchester City-Fulham         /en/matches/88066bdf/Manchester-City-Fulham-Se...
                                          2023-09-16 West Ham-Manchester City       /en/matches/64c0a6e2/West-Ham-United-Mancheste...

                                                                                   Notes
league             season team            game
ENG-Premier League 2324   Manchester City 2023-08-11 Burnley-Manchester City        <NA>
                                          2023-08-19 Manchester City-Newcastle Utd  <NA>
                                          2023-08-27 Sheffield Utd-Manchester City  <NA>
                                          2023-09-02 Manchester City-Fulham         <NA>
                                          2023-09-16 West Ham-Manchester City       <NA>

In [10]:
print(fbref.__doc__)

Provides pd.DataFrames from data at http://fbref.com.

    Data will be downloaded as necessary and cached locally in
    ``~/soccerdata/data/FBref``.

    Parameters
    ----------
    leagues : string or iterable, optional
        IDs of leagues to include. For efficiently reading data from the Top-5
        European leagues, use "Big 5 European Leagues Combined".
    seasons : string, int or list, optional
        Seasons to include. Supports multiple formats.
        Examples: '16-17'; 2016; '2016-17'; [14, 15, 16]
    proxy : 'tor' or dict or list(dict) or callable, optional
        Use a proxy to hide your IP address. Valid options are:
            - "tor": Uses the Tor network. Tor should be running in
              the background on port 9050.
            - dict: A dictionary with the proxy to use. The dict should be
              a mapping of supported protocols to proxy addresses. For example::

                  {
                      'http': 'http://10.10.1.10:3128',
                      'https': 'http://10.10.1.10:1080',
                  }

            - list(dict): A list of proxies to choose from. A different proxy will
              be selected from this list after failed requests, allowing rotating
              proxies.
            - callable: A function that returns a valid proxy. This function will
              be called after failed requests, allowing rotating proxies.
    no_cache : bool
        If True, will not use cached data.
    no_store : bool
        If True, will not store downloaded data.
    data_dir : Path
        Path to directory where data will be cached.

In [12]:
match_id = "0b8f50a5"

player_match_stats = fbref.read_player_match_stats(stat_type="passing", match_id=match_id)
display(player_match_stats)

lineups = fbref.read_lineup(match_id=match_id)
display(lineups)

[01/09/26 16:02:54] WARNING  e:\anacoda3\Lib\site-packages\soccerdata\fbref.py:165: FutureWarning:  ]8;id=636330;file://e:\anacoda3\Lib\warnings.py\warnings.py]8;;\:]8;id=559448;file://e:\anacoda3\Lib\warnings.py#112\112]8;;\
                             The behavior of DataFrame concatenation with empty or all-NA entries
                             is deprecated. In a future version, this will no longer exclude empty
                             or all-NA columns when determining the result dtypes. To retain the
                             old behavior, exclude the relevant entries before the concat
                             operation.
                               pd.concat(dfs)

[01/09/26 16:02:55] INFO     [1/1] Retrieving game with id=0b8f50a5                                    ]8;id=931695;file://e:\anacoda3\Lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=835090;file://e:\anacoda3\Lib\site-packages\soccerdata\fbref.py#815\815]8;;\

                                                                                                         jersey_number  \

league             season game                                     team             player
ENG-Premier League 2324   2023-08-19 Manchester City-Newcastle Utd Manchester City  Ederson                         31
                                                                                    Erling Haaland                   9
                                                                                    Jack Grealish                   10
                                                                                    Joško Gvardiol                  24
                                                                                    Julián Álvarez                  19
                                                                                    Kyle Walker                      2
                                                                                    Manuel Akanji                   25
                                                                                    Mateo Kovačić                    8
                                                                                    Phil Foden                      47
                                                                                    Rodri                           16
                                                                                    Rúben Dias                       3
                                                                   Newcastle United Alexander Isak                  14
                                                                                    Anthony Gordon                  10
                                                                                    Bruno Guimarães                 39
                                                                                    Callum Wilson                    9
                                                                                    Dan Burn                        33
                                                                                    Elliot Anderson                 32
                                                                                    Fabian Schär                     5
                                                                                    Harvey Barnes                   15
                                                                                    Joelinton                        7
                                                                                    Kieran Trippier                  2
                                                                                    Miguel Almirón                  24
                                                                                    Nick Pope                       22
                                                                                    Sandro Tonali                    8
                                                                                    Sean Longstaff                  36
                                                                                    Sven Botman                      4
                                                                                    Valentino Livramento            21

                                                                                                         nation  \

league             season game                                     team             player
ENG-Premier League 2324   2023-08-19 Manchester City-Newcastle Utd Manchester City  Ederson                 BRA
                                                                                    Erling Haaland          NOR
                                                                                    Jack Grealish           ENG
                                                                                    Joško Gvardiol          CRO
                                                                                    Julián Álvarez          ARG
                                                                                    Kyle Walker             ENG
                                                                                    Manuel Akanji           SUI
                                                                                    Mateo Kovačić           CRO
                                                                                    Phil Foden              ENG
                                                                                    Rodri                   ESP
                                                                                    Rúben Dias              POR
                                                                   Newcastle United Alexander Isak          SWE
                                                                                    Anthony Gordon          ENG
                                                                                    Bruno Guimarães         BRA
                                                                                    Callum Wilson           ENG
                                                                                    Dan Burn                ENG
                                                                                    Elliot Anderson         ENG
                                                                                    Fabian Schär            SUI
                                                                                    Harvey Barnes           ENG
                                                                                    Joelinton               BRA
                                                                                    Kieran Trippier         ENG
                                                                                    Miguel Almirón          PAR
                                                                                    Nick Pope               ENG
                                                                                    Sandro Tonali           ITA
                                                                                    Sean Longstaff          ENG
                                                                                    Sven Botman             NED
                                                                                    Valentino Livramento    ENG

                                                                                                            pos  \

league             season game                                     team             player
ENG-Premier League 2324   2023-08-19 Manchester City-Newcastle Utd Manchester City  Ederson                  GK
                                                                                    Erling Haaland           FW
                                                                                    Jack Grealish            LW
                                                                                    Joško Gvardiol           LB
                                                                                    Julián Álvarez           AM
                                                                                    Kyle Walker              RB
                                                                                    Manuel Akanji            CB
                                                                                    Mateo Kovačić            DM
                                                                                    Phil Foden               RW
                                                                                    Rodri                    DM
                                                                                    Rúben Dias               CB
                                                                   Newcastle United Alexander Isak           FW
                                                                                    Anthony Gordon           LW
                                                                                    Bruno Guimarães          CM
                                                                                    Callum Wilson            FW
                                                                                    Dan Burn                 LB
                                                                                    Elliot Anderson          LM
                                                                                    Fabian Schär             CB
                                                                                    Harvey Barnes            LW
                                                                                    Joelinton                LM
                                                                                    Kieran Trippier          RB
                                                                                    Miguel Almirón           RW
                                                                                    Nick Pope                GK
                                                                                    Sandro Tonali            RM
                                                                                    Sean Longstaff        RM,LM
                                                                                    Sven Botman              CB
                                                                                    Valentino Livramento     RW

                                                                                                             age  \

league             season game                                     team             player
ENG-Premier League 2324   2023-08-19 Manchester City-Newcastle Utd Manchester City  Ederson               30-002
                                                                                    Erling Haaland        23-029
                                                                                    Jack Grealish         27-343
                                                                                    Joško Gvardiol        21-208
                                                                                    Julián Álvarez        23-200
                                                                                    Kyle Walker           33-083
                                                                                    Manuel Akanji         28-031
                                                                                    Mateo Kovačić         29-105
                                                                                    Phil Foden            23-083
                                                                                    Rodri                 27-058
                                                                                    Rúben Dias            26-097
                                                                   Newcastle United Alexander Isak        23-332
                                                                                    Anthony Gordon        22-176
                                                                                    Bruno Guimarães       25-276
                                                                                    Callum Wilson         31-173
                                                                                    Dan Burn              31-102
                                                                                    Elliot Anderson       20-286
                                                                                    Fabian Schär          31-242
                                                                                    Harvey Barnes         25-253
                                                                                    Joelinton             27-005
                                                                                    Kieran Trippier       32-334
                                                                                    Miguel Almirón        29-190
                                                                                    Nick Pope             31-122
                                                                                    Sandro Tonali         23-103
                                                                                    Sean Longstaff        25-293
                                                                                    Sven Botman           23-219
                                                                                    Valentino Livramento  20-280

                                                                                                         min  \

league             season game                                     team             player
ENG-Premier League 2324   2023-08-19 Manchester City-Newcastle Utd Manchester City  Ederson               90
                                                                                    Erling Haaland        90
                                                                                    Jack Grealish         90
                                                                                    Joško Gvardiol        90
                                                                                    Julián Álvarez        90
                                                                                    Kyle Walker           90
                                                                                    Manuel Akanji         90
                                                                                    Mateo Kovačić         90
                                                                                    Phil Foden            90
                                                                                    Rodri                 90
                                                                                    Rúben Dias            90
                                                                   Newcastle United Alexander Isak        65
                                                                                    Anthony Gordon        55
                                                                                    Bruno Guimarães       90
                                                                                    Callum Wilson         25
                                                                                    Dan Burn              90
                                                                                    Elliot Anderson       25
                                                                                    Fabian Schär          90
                                                                                    Harvey Barnes         35
                                                                                    Joelinton             56
                                                                                    Kieran Trippier       90
                                                                                    Miguel Almirón        85
                                                                                    Nick Pope             90
                                                                                    Sandro Tonali         65
                                                                                    Sean Longstaff        34
                                                                                    Sven Botman           90
                                                                                    Valentino Livramento   5

                                                                                                         Total  \
                                                                                                           Cmp
league             season game                                     team             player
ENG-Premier League 2324   2023-08-19 Manchester City-Newcastle Utd Manchester City  Ederson                 39
                                                                                    Erling Haaland           6
                                                                                    Jack Grealish           39
                                                                                    Joško Gvardiol          57
                                                                                    Julián Álvarez          24
                                                                                    Kyle Walker             65
                                                                                    Manuel Akanji           57
                                                                                    Mateo Kovačić           91
                                                                                    Phil Foden              50
                                                                                    Rodri                  122
                                                                                    Rúben Dias              82
                                                                   Newcastle United Alexander Isak           8
                                                                                    Anthony Gordon          14
                                                                                    Bruno Guimarães         62
                                                                                    Callum Wilson            3
                                                                                    Dan Burn                43
                                                                                    Elliot Anderson          9
                                                                                    Fabian Schär            59
                                                                                    Harvey Barnes           13
                                                                                    Joelinton               17
                                                                                    Kieran Trippier         61
                                                                                    Miguel Almirón          23
                                                                                    Nick Pope               25
                                                                                    Sandro Tonali           32
                                                                                    Sean Longstaff          10
                                                                                    Sven Botman             53
                                                                                    Valentino Livramento     0

                                                                                                               \
                                                                                                          Att
league             season game                                     team             player

                    WARNING  e:\anacoda3\Lib\site-packages\soccerdata\fbref.py:165: FutureWarning:  ]8;id=932031;file://e:\anacoda3\Lib\warnings.py\warnings.py]8;;\:]8;id=978202;file://e:\anacoda3\Lib\warnings.py#112\112]8;;\
                             The behavior of DataFrame concatenation with empty or all-NA entries
                             is deprecated. In a future version, this will no longer exclude empty
                             or all-NA columns when determining the result dtypes. To retain the
                             old behavior, exclude the relevant entries before the concat
                             operation.
                               pd.concat(dfs)

                    INFO     [1/1] Retrieving game with id=0b8f50a5                                    ]8;id=641893;file://e:\anacoda3\Lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=8578;file://e:\anacoda3\Lib\site-packages\soccerdata\fbref.py#904\904]8;;\

                                                                    jersey_number  \
league             season game
ENG-Premier League 2324   2023-08-19 Manchester City-Newcastle Utd             31
                          2023-08-19 Manchester City-Newcastle Utd              2
                          2023-08-19 Manchester City-Newcastle Utd              3
                          2023-08-19 Manchester City-Newcastle Utd              8
                          2023-08-19 Manchester City-Newcastle Utd              9
                          2023-08-19 Manchester City-Newcastle Utd             10
                          2023-08-19 Manchester City-Newcastle Utd             16
                          2023-08-19 Manchester City-Newcastle Utd             19
                          2023-08-19 Manchester City-Newcastle Utd             24
                          2023-08-19 Manchester City-Newcastle Utd             25
                          2023-08-19 Manchester City-Newcastle Utd             47
                          2023-08-19 Manchester City-Newcastle Utd             18
                          2023-08-19 Manchester City-Newcastle Utd              4
                          2023-08-19 Manchester City-Newcastle Utd              6
                          2023-08-19 Manchester City-Newcastle Utd             21
                          2023-08-19 Manchester City-Newcastle Utd             32
                          2023-08-19 Manchester City-Newcastle Utd             52
                          2023-08-19 Manchester City-Newcastle Utd             80
                          2023-08-19 Manchester City-Newcastle Utd             82
                          2023-08-19 Manchester City-Newcastle Utd             87
                          2023-08-19 Manchester City-Newcastle Utd             22
                          2023-08-19 Manchester City-Newcastle Utd              2
                          2023-08-19 Manchester City-Newcastle Utd              4
                          2023-08-19 Manchester City-Newcastle Utd              5
                          2023-08-19 Manchester City-Newcastle Utd              7
                          2023-08-19 Manchester City-Newcastle Utd              8
                          2023-08-19 Manchester City-Newcastle Utd             10
                          2023-08-19 Manchester City-Newcastle Utd             14
                          2023-08-19 Manchester City-Newcastle Utd             24
                          2023-08-19 Manchester City-Newcastle Utd             33
                          2023-08-19 Manchester City-Newcastle Utd             39
                          2023-08-19 Manchester City-Newcastle Utd              1
                          2023-08-19 Manchester City-Newcastle Utd              6
                          2023-08-19 Manchester City-Newcastle Utd              9
                          2023-08-19 Manchester City-Newcastle Utd             11
                          2023-08-19 Manchester City-Newcastle Utd             13
                          2023-08-19 Manchester City-Newcastle Utd             15
                          2023-08-19 Manchester City-Newcastle Utd             21
                          2023-08-19 Manchester City-Newcastle Utd             32
                          2023-08-19 Manchester City-Newcastle Utd             36

                                                                                  player  \
league             season game
ENG-Premier League 2324   2023-08-19 Manchester City-Newcastle Utd               Ederson
                          2023-08-19 Manchester City-Newcastle Utd           Kyle Walker
                          2023-08-19 Manchester City-Newcastle Utd            Rúben Dias
                          2023-08-19 Manchester City-Newcastle Utd         Mateo Kovačić
                          2023-08-19 Manchester City-Newcastle Utd        Erling Haaland
                          2023-08-19 Manchester City-Newcastle Utd         Jack Grealish
                          2023-08-19 Manchester City-Newcastle Utd                 Rodri
                          2023-08-19 Manchester City-Newcastle Utd        Julián Álvarez
                          2023-08-19 Manchester City-Newcastle Utd        Joško Gvardiol
                          2023-08-19 Manchester City-Newcastle Utd         Manuel Akanji
                          2023-08-19 Manchester City-Newcastle Utd            Phil Foden
                          2023-08-19 Manchester City-Newcastle Utd         Stefan Ortega
                          2023-08-19 Manchester City-Newcastle Utd       Kalvin Phillips
                          2023-08-19 Manchester City-Newcastle Utd            Nathan Aké
                          2023-08-19 Manchester City-Newcastle Utd          Sergio Gómez
                          2023-08-19 Manchester City-Newcastle Utd        Máximo Perrone
                          2023-08-19 Manchester City-Newcastle Utd            Oscar Bobb
                          2023-08-19 Manchester City-Newcastle Utd           Cole Palmer
                          2023-08-19 Manchester City-Newcastle Utd            Rico Lewis
                          2023-08-19 Manchester City-Newcastle Utd          James Mcatee
                          2023-08-19 Manchester City-Newcastle Utd             Nick Pope
                          2023-08-19 Manchester City-Newcastle Utd       Kieran Trippier
                          2023-08-19 Manchester City-Newcastle Utd           Sven Botman
                          2023-08-19 Manchester City-Newcastle Utd          Fabian Schär
                          2023-08-19 Manchester City-Newcastle Utd             Joelinton
                          2023-08-19 Manchester City-Newcastle Utd         Sandro Tonali
                          2023-08-19 Manchester City-Newcastle Utd        Anthony Gordon
                          2023-08-19 Manchester City-Newcastle Utd        Alexander Isak
                          2023-08-19 Manchester City-Newcastle Utd        Miguel Almirón
                          2023-08-19 Manchester City-Newcastle Utd              Dan Burn
                          2023-08-19 Manchester City-Newcastle Utd       Bruno Guimarães
                          2023-08-19 Manchester City-Newcastle Utd       Martin Dúbravka
                          2023-08-19 Manchester City-Newcastle Utd      Jamaal Lascelles
                          2023-08-19 Manchester City-Newcastle Utd         Callum Wilson
                          2023-08-19 Manchester City-Newcastle Utd          Matt Ritchie
                          2023-08-19 Manchester City-Newcastle Utd          Matt Targett
                          2023-08-19 Manchester City-Newcastle Utd         Harvey Barnes
                          2023-08-19 Manchester City-Newcastle Utd  Valentino Livramento
                          2023-08-19 Manchester City-Newcastle Utd       Elliot Anderson
                          2023-08-19 Manchester City-Newcastle Utd        Sean Longstaff

                                                                                team  \
league             season game
ENG-Premier League 2324   2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd   Manchester City
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United
                          2023-08-19 Manchester City-Newcastle Utd  Newcastle United

                                                                   is_starter  \
league             season game
ENG-Premier League 2324   2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd      False
                          2023-08-19 Manchester City-Newcastle Utd      False
                          2023-08-19 Manchester City-Newcastle Utd      False
                          2023-08-19 Manchester City-Newcastle Utd      False
                          2023-08-19 Manchester City-Newcastle Utd      False
                          2023-08-19 Manchester City-Newcastle Utd      False
                          2023-08-19 Manchester City-Newcastle Utd      False
                          2023-08-19 Manchester City-Newcastle Utd      False
                          2023-08-19 Manchester City-Newcastle Utd      False
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd       True
                          2023-08-19 Manchester City-Newcastle Utd      False
                          2023-08-19 Manchester City-Newcastle Utd      False
                          2023-08-19 Manchester City-Newcastle Utd      False
                          2023-08-19 Manchester City-Newcastle Utd      False
                          2023-08-19 Manchester City-Newcastle Utd      False
                          2023-08-19 Manchester City-Newcastle Utd      False
                          2023-08-19 Manchester City-Newcastle Utd      False
                          2023-08-19 Manchester City-Newcastle Utd      False
                          2023-08-19 Manchester City-Newcastle Utd      False

                                                                   position  \
league             season game
ENG-Premier League 2324   2023-08-19 Manchester City-Newcastle Utd       GK
                          2023-08-19 Manchester City-Newcastle Utd       RB
                          2023-08-19 Manchester City-Newcastle Utd       CB
                          2023-08-19 Manchester City-Newcastle Utd       DM
                          2023-08-19 Manchester City-Newcastle Utd       FW
                          2023-08-19 Manchester City-Newcastle Utd       LW
                          2023-08-19 Manchester City-Newcastle Utd       DM
                          2023-08-19 Manchester City-Newcastle Utd       AM
                          2023-08-19 Manchester City-Newcastle Utd       LB
                          2023-08-19 Manchester City-Newcastle Utd       CB
                          2023-08-19 Manchester City-Newcastle Utd       RW
                          2023-08-19 Manchester City-Newcastle Utd     <NA>
                          2023-08-19 Manchester City-Newcastle Utd     <NA>
                          2023-08-19 Manchester City-Newcastle Utd     <NA>
                          2023-08-19 Manchester City-Newcastle Utd     <NA>
                          2023-08-19 Manchester City-Newcastle Utd     <NA>
                          2023-08-19 Manchester City-Newcastle Utd     <NA>
                          2023-08-19 Manchester City-Newcastle Utd     <NA>
                          2023-08-19 Manchester City-Newcastle Utd     <NA>
                          2023-08-19 Manchester City-Newcastle Utd     <NA>
                          2023-08-19 Manchester City-Newcastle Utd       GK
                          2023-08-19 Manchester City-Newcastle Utd       RB
                          2023-08-19 Manchester City-Newcastle Utd       CB
                          2023-08-19 Manchester City-Newcastle Utd       CB
                          2023-08-19 Manchester City-Newcastle Utd       LM
                          2023-08-19 Manchester City-Newcastle Utd       RM
                          2023-08-19 Manchester City-Newcastle Utd       LW
                          2023-08-19 Manchester City-Newcastle Utd       FW
                          2023-08-19 Manchester City-Newcastle Utd       RW
                          2023-08-19 Manchester City-Newcastle Utd       LB
                          2023-08-19 Manchester City-Newcastle Utd       CM
                          2023-08-19 Manchester City-Newcastle Utd     <NA>
                          2023-08-19 Manchester City-Newcastle Utd     <NA>
                          2023-08-19 Manchester City-Newcastle Utd       FW
                          2023-08-19 Manchester City-Newcastle Utd     <NA>
                          2023-08-19 Manchester City-Newcastle Utd     <NA>
                          2023-08-19 Manchester City-Newcastle Utd       LW
                          2023-08-19 Manchester City-Newcastle Utd       RW
                          2023-08-19 Manchester City-Newcastle Utd       LM
                          2023-08-19 Manchester City-Newcastle Utd    RM,LM

                                                                    minutes_played
league             season game
ENG-Premier League 2324   2023-08-19 Manchester City-Newcastle Utd              90
                          2023-08-19 Manchester City-Newcastle Utd              90
                          2023-08-19 Manchester City-Newcastle Utd              90
                          2023-08-19 Manchester City-Newcastle Utd              90
                          2023-08-19 Manchester City-Newcastle Utd              90
                          2023-08-19 Manchester City-Newcastle Utd              90
                          2023-08-19 Manchester City-Newcastle Utd              90
                          2023-08-19 Manchester City-Newcastle Utd              90
                          2023-08-19 Manchester City-Newcastle Utd              90
                          2023-08-19 Manchester City-Newcastle Utd              90
                          2023-08-19 Manchester City-Newcastle Utd              90
                          2023-08-19 Manchester City-Newcastle Utd               0
                          2023-08-19 Manchester City-Newcastle Utd               0
                          2023-08-19 Manchester City-Newcastle Utd               0
                          2023-08-19 Manchester City-Newcastle Utd               0
                          2023-08-19 Manchester City-Newcastle Utd               0
                          2023-08-19 Manchester City-Newcastle Utd               0
                          2023-08-19 Manchester City-Newcastle Utd               0
                          2023-08-19 Manchester City-Newcastle Utd               0
                          2023-08-19 Manchester City-Newcastle Utd               0
                          2023-08-19 Manchester City-Newcastle Utd              90
                          2023-08-19 Manchester City-Newcastle Utd              90
                          2023-08-19 Manchester City-Newcastle Utd              90
                          2023-08-19 Manchester City-Newcastle Utd              90
                          2023-08-19 Manchester City-Newcastle Utd              56
                          2023-08-19 Manchester City-Newcastle Utd              65
                          2023-08-19 Manchester City-Newcastle Utd              55
                          2023-08-19 Manchester City-Newcastle Utd              65
                          2023-08-19 Manchester City-Newcastle Utd              85
                          2023-08-19 Manchester City-Newcastle Utd              90
                          2023-08-19 Manchester City-Newcastle Utd              90
                          2023-08-19 Manchester City-Newcastle Utd               0
                          2023-08-19 Manchester City-Newcastle Utd               0
                          2023-08-19 Manchester City-Newcastle Utd              25