In [1]:
# IMPORT, CONFIG

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import re

from scrapers import MatchScraper, H2HScraper
from scrapers.base_scraper import BaseScraper
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

rankings = pd.read_csv("data/all_rankings2025.csv")
rankings.date = pd.to_datetime(rankings.date)

tours = {'8292': {'name': 'ESL Pro League Season 21',
                  'url': 'https://www.oddsportal.com/esports/counter-strike/counter-strike-esl-pro-league-season-21/results/'},
         '7907': {'name': 'BLAST Open London 2025',
                  'url': 'https://www.oddsportal.com/esports/counter-strike/counter-strike-blast-open/results/'},
         '8038': {'name': 'IEM Cologne 2025',
              'url': 'https://www.oddsportal.com/esports/counter-strike/counter-strike-intel-extreme-masters-cologne/results/'},
         '8036': {'name': 'IEM Melbourne 2025',
              'url': 'https://www.oddsportal.com/esports/counter-strike/counter-strike-iem-melbourne/results/'}
        }

In [2]:
# 3. TARGET MATCHES SCRAPING

def _target_match_scrape(event_id):

    print("\n" + "="*60)
    print("1️⃣ TARGET MATCHES SCRAPING")
    print("="*60)

    try:
        scraper = MatchScraper(headless=False)
        target_matches = scraper.scrape_event_matches(event_id)
        
        if target_matches.empty:
            raise ValueError("❌ Nincs target match!")
        
        # ordinal ragok eltávolítása
        target_matches["date_clean"] = target_matches["date"].apply(lambda x: re.sub(r'(\d+)(st|nd|rd|th)', r'\1', x))

        # dátummá alakítás
        target_matches["date_parsed"] = pd.to_datetime(target_matches["date_clean"], format="%B %d %Y")

        
        print(f"✅ {len(target_matches)} meccs találva")
        display(target_matches.head(3))
        
    except Exception as e:
        print(f"❌ Hiba a target matches scraping közben: {e}")
        
    return target_matches

In [3]:
# 5. MATCH H2H SCRAPING
def _h2h_match_scrape(selected_match):
    print("\n" + "="*60)
    print("3️⃣ MATCH H2H SCRAPING")
    print("="*60)

    try:
        match_url = selected_match['link']
        print(f"🔍 Scraping: {match_url}")
        
        scraper = H2HScraper(headless=False)
        h2h_df = scraper.scrape_match_h2h(match_url)
        
        if h2h_df.empty:
            raise ValueError("❌ H2H scraping sikertelen!")
        
        match_h2h = h2h_df.iloc[0]
        
        print(f"✅ H2H data:")
        display(match_h2h)

        return match_h2h
        
    except Exception as e:
        print(f"❌ Hiba a H2H scraping közben: {e}")

        return pd.DataFrame()

In [4]:
# 6. TEAMS EXTRACTION

def _extract_teams(match_h2h):
    print("\n" + "="*60)
    print("4️⃣ TEAMS EXTRACTION")
    print("="*60)

    teams = {
        'home': {
            'team_id': str(match_h2h.get('home_team_id', 'unknown')),
            'team_name': match_h2h['home_team']
        },
        'away': {
            'team_id': str(match_h2h.get('away_team_id', 'unknown')), 
            'team_name': match_h2h['away_team']
        }
    }

    print(f"✅ Teams extracted:")
    print(f"  Home: {teams['home']['team_name']} (ID: {teams['home']['team_id']})")
    print(f"  Away: {teams['away']['team_name']} (ID: {teams['away']['team_id']})")

    return teams

In [5]:
# 7. TEAM HISTORY SCRAPING HELPER

print("\n" + "="*60)
print("5️⃣ TEAM HISTORY SCRAPING HELPER")
print("="*60)

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from scrapers.base_scraper import BaseScraper

class TeamHistoryScraper(BaseScraper):
    def scrape_team_matches(self, team_id: str, max_matches: int = 20):
        """Team match history scraping"""
        url = f"https://www.hltv.org/results?team={team_id}"
        self._init_driver()
        self.driver.get(url)

        wait = WebDriverWait(self.driver, 20)
        wait.until(EC.presence_of_element_located((By.CLASS_NAME, "results-holder")))

        self._random_delay()

        matches = []
        all_sublists = self.driver.find_elements(By.CLASS_NAME, "results-sublist")
        print(f"🔍 Összesen {len(all_sublists)} results-sublist betöltve")

        for sublist in all_sublists:
            if len(matches) >= max_matches:
                break

            try:
                headline = sublist.find_element(By.CLASS_NAME, "standard-headline").text.strip()
                match_date = headline.replace("Results for", "").strip()
            except:
                match_date = None

            match_blocks = sublist.find_elements(By.CLASS_NAME, "result-con")
            for match in match_blocks:
                if len(matches) >= max_matches:
                    break

                try:
                    a_tag = match.find_element(By.TAG_NAME, "a")
                    match_url = a_tag.get_attribute("href")
                    match_id = match_url.split('/')[4]

                    table = a_tag.find_element(By.TAG_NAME, "table")
                    tds = table.find_elements(By.TAG_NAME, "td")

                    team1_name = tds[0].find_element(By.CLASS_NAME, "team").text.strip()
                    team2_name = tds[2].find_element(By.CLASS_NAME, "team").text.strip()

                    score_spans = tds[1].find_elements(By.TAG_NAME, "span")
                    score1 = int(score_spans[0].text.strip())
                    score2 = int(score_spans[1].text.strip())

                    team1_html = tds[0].get_attribute("innerHTML")
                    won = "team-won" in team1_html

                    try:
                        map_text = a_tag.find_element(By.CSS_SELECTOR, ".map-text").text.strip()
                    except:
                        map_text = "bo1"

                    opponent_name = team2_name if team1_name else team1_name

                    matches.append({
                        "team_id": team_id,
                        "match_id": match_id,
                        "match_date": match_date,
                        "opponent_name": opponent_name,
                        "result": "win" if won else "loss",
                        "score_for": score1,
                        "score_against": score2,
                        "map_type": map_text,
                        "link": match_url
                    })

                except Exception as e:
                    print(f"⚠️ Hiba egy meccs feldolgozásánál: {e}")
                    continue

        self.close()
        return pd.DataFrame(matches)

print("✅ TeamHistoryScraper helper kész")


# 8. TEAM HISTORIES SCRAPING

def _team_history_scrape(teams, selected_match):
    print("\n" + "="*60)
    print("6️⃣ TEAM HISTORIES SCRAPING")
    print("="*60)

    team_histories = {}

    for side in ['home', 'away']:
        team_id = teams[side]['team_id']
        team_name = teams[side]['team_name']
        
        print(f"\n📈 Scraping history: {team_name} (ID: {team_id})")
        
        try:
            scraper = TeamHistoryScraper(headless=False)
            history_df = scraper.scrape_team_matches(team_id, max_matches=100)
            
            if history_df.empty:
                print(f"⚠️ Nincs history adat: {team_name}")
                team_histories[side] = pd.DataFrame()
                continue

            # ordinal ragok eltávolítása
            history_df["date_clean"] = history_df["match_date"].apply(lambda x: re.sub(r'(\d+)(st|nd|rd|th)', r'\1', x))
            # dátummá alakítás
            history_df["date_parsed"] = pd.to_datetime(history_df["date_clean"], format="%B %d %Y")

            # csak a meccs dátuma előttiek (megelőző meccsek)
            history_df = history_df[history_df['date_parsed'] < selected_match['date_parsed']]       

            if len(history_df) < 3:
                print(f"⚠️ Nincs elég history adat: {team_name}")
                team_histories[side] = pd.DataFrame()
                continue

            team_histories[side] = history_df
            
            print(f"✅ {len(history_df)} meccs találva")

            print(f"\n📋 Megelőző 3 meccs:")
            display(history_df.head(3))
            
        except Exception as e:
            print(f"❌ Hiba a history scraping közben: {e}")
            team_histories[side] = pd.DataFrame()
        
    return team_histories

============================================================
5️⃣ TEAM HISTORY SCRAPING HELPER
============================================================
✅ TeamHistoryScraper helper kész

In [6]:
# 9. HISTORICAL H2H SCRAPING

# Get rank data function
def get_rank_data(date, team_name):
    team_rankings = rankings[(rankings['date'] < date) & 
                            (rankings['team_name'] == team_name)].reset_index(drop=True)

    # Current (latest) rank & points
    rank = team_rankings.loc[0, 'rank']
    points = team_rankings.loc[0, 'points']
    # Latest rank & points change
    rank_change = team_rankings.loc[0, 'rank'] - team_rankings.loc[1, 'rank']
    points_change = team_rankings.loc[0, 'points'] - team_rankings.loc[1, 'points']

    return({'rank': rank,
            'rank_change': rank_change, 
            'points': points,
            'points_change': points_change}
            )
print("Rank data function initialized.")


def _historical_h2h_scrape(teams, team_histories, selected_match):
    print("\n" + "="*60)
    print("7️⃣ HISTORICAL H2H SCRAPING")
    print("="*60)

    historical_h2h = {}
    N_MATCHES = 3

    rank_data = {}
    for side in ['home', 'away']:
        team_name = teams[side]['team_name']
        team_id = teams[side]['team_id']
        date = selected_match['date_parsed']

        try:
            rank_data[side] = get_rank_data(date, team_name)
        except Exception as e:
            print(f"⚠️ Rank data hiba {team_name} esetén: {e}")
            rank_data[side] = {'rank': None, 'rank_change': None, 'points': None, 'points_change': None}
        
        print(f"\n🔍 {team_name} last {N_MATCHES} matches H2H scraping:")
        
        history = team_histories.get(side, pd.DataFrame())
        
        if history.empty:
            print(f"  ⚠️ Nincs history, skip")
            historical_h2h[side] = {}
            continue
        
        history = history[history['date_parsed'] < date].reset_index(drop=True)
        
        # Last N match URL-ek
        if len(history) < N_MATCHES:
            print(f"  ⚠️ Kevesebb mint {N_MATCHES} meccs a historyban, csak {len(history)} elérhető")
            # Itt is adj hozzá üres dict-et
            historical_h2h[side] = {}
            continue
        
        last_n_matches = history.head(N_MATCHES)
        
        h2h_total = []
        h2h_wins = []
        ratings = []
        rating_stds = []
        adrs = []
        adr_stds = []
        swings = []
        swing_stds = []
        maps_total = []
        maps_wins = []
        maps_picked = []
        maps_avg_score_diffs = []
        ranks_opp = []
        ranks_change = []
        rank_diffs = []
        points_opp = []
        points_change = []
        point_diffs = []
        
        for idx, match in last_n_matches.iterrows():
            match_url = match['link']
            print(f"  [{idx+1}/{N_MATCHES}] Scraping: {match['date_parsed'].date()} vs {match['opponent_name']}\n{match_url}")
            rank_data_side = get_rank_data(match['date_parsed'], team_name)

            try:
                scraper = H2HScraper(headless=False)
                hist_h2h_df = scraper.scrape_match_h2h(match_url)

                if hist_h2h_df.empty:
                    raise ValueError("❌ H2H scraping sikertelen!")
                
                if str(hist_h2h_df['home_team_id'][0]) == str(team_id):
                    h2h_total.append(hist_h2h_df['total_non_overtime'][0])
                    h2h_wins.append(hist_h2h_df['wins_home'][0])
                    ratings.append(hist_h2h_df['home_team_avg_rating'][0])
                    rating_stds.append(hist_h2h_df['home_team_std_rating'][0])
                    adrs.append(hist_h2h_df['home_team_avg_ADR'][0])
                    adr_stds.append(hist_h2h_df['home_team_std_ADR'][0])
                    swings.append(hist_h2h_df['home_team_avg_Swing'][0])
                    swing_stds.append(hist_h2h_df['home_team_std_Swing'][0])
                    maps_total.append(hist_h2h_df['maps_played'][0])
                    maps_wins.append(hist_h2h_df['home_maps_won'][0])
                    maps_picked.append(hist_h2h_df['home_maps_picked'][0])
                    maps_avg_score_diffs.append(hist_h2h_df['map_avg_score_diff'][0])
                    opp = hist_h2h_df['away_team'][0]

                elif str(hist_h2h_df['away_team_id'][0]) == str(team_id):
                    h2h_total.append(hist_h2h_df['total_non_overtime'][0])
                    h2h_wins.append(hist_h2h_df['wins_away'][0])
                    ratings.append(hist_h2h_df['away_team_avg_rating'][0])
                    rating_stds.append(hist_h2h_df['away_team_std_rating'][0])
                    adrs.append(hist_h2h_df['away_team_avg_ADR'][0])
                    adr_stds.append(hist_h2h_df['away_team_std_ADR'][0])
                    swings.append(hist_h2h_df['away_team_avg_Swing'][0])
                    swing_stds.append(hist_h2h_df['away_team_std_Swing'][0])
                    maps_total.append(hist_h2h_df['maps_played'][0])
                    maps_wins.append(hist_h2h_df['away_maps_won'][0])
                    maps_picked.append(hist_h2h_df['maps_played'][0] - hist_h2h_df['home_maps_picked'][0])
                    maps_avg_score_diffs.append( - hist_h2h_df['map_avg_score_diff'][0])
                    opp = hist_h2h_df['home_team'][0]
                else:
                    print("ERROR: team_id not in df")

                # HLTV Rank & points
                rank_data_opp = get_rank_data(match['date_parsed'], opp)

                ranks_opp.append(rank_data_opp['rank'])
                ranks_change.append(rank_data_opp['rank_change'])
                rank_diffs.append(rank_data_opp['rank'] - rank_data_side['rank'])
                points_opp.append(rank_data_opp['points'])
                points_change.append(rank_data_opp['points_change'])
                point_diffs.append(rank_data_side['points'] - rank_data_opp['points'])
                            
            except Exception as e:
                print(f"    ⚠️ H2H scraping hiba: {e}")
                continue
        
        # Átlagok számítása
        avg_h2h_winrate = np.sum(h2h_wins) / np.sum(h2h_total) if h2h_total else None
        avg_rating = np.mean(ratings) if ratings else None
        avg_rating_std = np.mean(rating_stds) if rating_stds else None
        avg_adr = np.mean(adrs) if adrs else None
        avg_adr_std = np.mean(adr_stds) if adr_stds else None
        avg_swing = np.mean(swings) if swings else None
        avg_swing_std = np.mean(swing_stds) if swing_stds else None
        avg_maps_total = np.mean(maps_total) if maps_total else None
        avg_map_winrate = np.sum(maps_wins) / np.sum(maps_total) if maps_wins else None
        avg_map_pickrate = np.sum(maps_picked) / np.sum(maps_total) if maps_picked else None
        avg_map_score_diff = np.mean(maps_avg_score_diffs) if maps_avg_score_diffs else None
        avg_rank_diff = np.mean(rank_diffs) if rank_diffs else None
        std_rank_diff = np.std(rank_diffs) if rank_diffs else None
        avg_point_diff = np.mean(point_diffs) if point_diffs else None
        std_point_diff = np.std(point_diffs) if point_diffs else None
        weak_opp_rank_diff = np.max(rank_diffs) if rank_diffs else None
        strong_opp_rank_diff = np.min(rank_diffs) if rank_diffs else None
        weak_opp_point_diff = np.max(point_diffs) if point_diffs else None
        strong_opp_point_diff = np.min(point_diffs) if point_diffs else None

        historical_h2h[side] = {
            'avg_h2h_winrate': avg_h2h_winrate,
            'avg_rating': avg_rating,
            'avg_rating_std': avg_rating_std,
            'avg_adr': avg_adr,
            'avg_adr_std': avg_adr_std,
            'avg_swing': avg_swing,
            'avg_swing_std': avg_swing_std,
            'avg_maps_total': avg_maps_total,
            'avg_map_winrate': avg_map_winrate,
            'avg_map_pickrate': avg_map_pickrate,
            'avg_map_score_diff': avg_map_score_diff,
            'avg_rank_diff': avg_rank_diff,
            'std_rank_diff': std_rank_diff,
            'avg_point_diff': avg_point_diff,
            'std_point_diff': std_point_diff,
            'weak_opp_rank_diff': weak_opp_rank_diff,
            'strong_opp_rank_diff': strong_opp_rank_diff,
            'weak_opp_point_diff': weak_opp_point_diff,
            'strong_opp_point_diff': strong_opp_point_diff,
            'n_matches_scraped': len(ratings)
        }

    print(f"\n📊 Historical H2H stats összegzés:")
    for side in ['home', 'away']:
        stats = historical_h2h[side]
        display(stats)

    return historical_h2h, rank_data

Rank data function initialized.

In [7]:
# 10. ROLLING FEATURES SZÁMÍTÁSA

def _calculate_rolling_features(teams, team_histories, historical_h2h):

    print("\n" + "="*60)
    print("8️⃣ ROLLING FEATURES SZÁMÍTÁSA")
    print("="*60)

    ml_input_row = {}

    for side in ['home', 'away']:
        team_name = teams[side]['team_name']
        print(f"\n📊 {team_name} rolling features:")
        
        history = team_histories.get(side, pd.DataFrame())
        
        if history.empty:
            print(f"  ⚠️ Nincs history adat")
            continue
        
        # Last 3 winrate
        last_3 = history.head(3)
        last_3_wr = (last_3['result'] == 'win').mean() if len(last_3) > 0 else None
        
        # Last 5 winrate  
        last_5 = history.head(5)
        last_5_wr = (last_5['result'] == 'win').mean() if len(last_5) > 0 else None
        
        # Avg scores
        last_3_avg_for = last_3['score_for'].mean() if len(last_3) > 0 else None
        last_3_avg_against = last_3['score_against'].mean() if len(last_3) > 0 else None
        
        # Current streak
        streak = 0
        if len(history) > 0:
            last_result = history.iloc[0]['result']
            for _, match in history.iterrows():
                if match['result'] == last_result:
                    streak += 1
                else:
                    break
            if last_result == 'loss':
                streak *= -1
        
        print(f"  Last 3 winrate:    {last_3_wr:.3f}" if last_3_wr else "  Last 3 winrate:    N/A")
        print(f"  Last 5 winrate:    {last_5_wr:.3f}" if last_5_wr else "  Last 5 winrate:    N/A")
        print(f"  Last 3 avg score:  {last_3_avg_for:.1f} - {last_3_avg_against:.1f}" if last_3_avg_for else "  Last 3 avg score:  N/A")
        print(f"  Current streak:    {streak:+d}")
        
        # Store
        ml_input_row[f'{side}_last_3_winrate'] = last_3_wr
        ml_input_row[f'{side}_last_5_winrate'] = last_5_wr
        ml_input_row[f'{side}_last_3_avg_score_for'] = last_3_avg_for
        ml_input_row[f'{side}_last_3_avg_score_against'] = last_3_avg_against
        ml_input_row[f'{side}_current_streak'] = streak

        for key in historical_h2h[side].keys():
            value = historical_h2h[side][key]
            ml_input_row[f'{side}_{key}'] = value
            print(f"  {side}_{key}: {value:.2f}")

    # Difference features
    if 'home_last_3_winrate' in ml_input_row and 'away_last_3_winrate' in ml_input_row:
        diff_last3_wr = ml_input_row['home_last_3_winrate'] - ml_input_row['away_last_3_winrate']
        ml_input_row['diff_last_3_winrate'] = diff_last3_wr
        print(f"\n📊 Difference features:")
        print(f"  Diff last 3 WR:    {diff_last3_wr:+.3f}")

    return ml_input_row

In [8]:
# 11. RANKINGS ÉS EGYÉB FEATURE-ÖK

def _add_other_features(ml_input_row, event_id, selected_match, teams, rank_data, match_h2h):

    print("\n" + "="*60)
    print("9️⃣ RANKINGS ÉS EGYÉB FEATURE-ÖK")
    print("="*60)

    # Basic match info
    ml_input_row['match_id'] = selected_match['match_id']
    ml_input_row['event_id'] = event_id
    ml_input_row['date'] = selected_match['date_parsed']
    ml_input_row['match_url'] = selected_match['link']


    # Teams
    ml_input_row['team_home'] = teams['home']['team_name']
    ml_input_row['team_away'] = teams['away']['team_name']

    # Rankings
    ml_input_row['home_current_rank'] = rank_data['home']['rank']
    ml_input_row['away_current_rank'] = rank_data['away']['rank'] 
    ml_input_row['home_rank_change'] = rank_data['home']['rank_change']
    ml_input_row['away_rank_change'] = rank_data['away']['rank_change']

    print(f"  Home rank: #{ml_input_row['home_current_rank']} (change: {ml_input_row['home_rank_change']:+d})")
    print(f"  Away rank: #{ml_input_row['away_current_rank']} (change: {ml_input_row['away_rank_change']:+d})")

    # Date features
    ml_input_row['date_month'] = selected_match['date_parsed'].strftime("%m")
    ml_input_row['date_day'] = int(selected_match['date_parsed'].strftime("%w")) + 1

    # H2H features
    ml_input_row['H2H_winrate_team1'] = match_h2h['home_win_rate']
    ml_input_row['H2H_games'] = match_h2h['wins_home'] + match_h2h['wins_away']

    # Match info
    ml_input_row['match_rounds'] = selected_match['rounds']

    # Label (score)
    ml_input_row['score_home'] = selected_match['score_home']
    ml_input_row['score_away'] = selected_match['score_away']
    ml_input_row['label_home_win'] = 1 if selected_match['score_home'] > selected_match['score_away'] else 0

    print("✅ Feature-ök összegyűjtve!")

    return ml_input_row

In [9]:
# Find match and parse odds

def _parse_odds(ml_input_row):
    df_odds = pd.read_csv("odds.csv")

    df_odds.Date = pd.to_datetime(df_odds.Date)

    date = ml_input_row['date']
    oneday = timedelta(days=1.5)
    home_hltv = ml_input_row['team_home']
    away_hltv = ml_input_row['team_away']

    odds_row = df_odds[
                    (df_odds.event_id == int(ml_input_row['event_id'])) &
                    (df_odds.Date <= date + oneday) & 
                    (df_odds.Date >= date - oneday) &
                            
                    (
                        ((df_odds.home_team_mapped == home_hltv) & 
                        (df_odds.away_team_mapped == away_hltv) ) |
                            
                        ((df_odds.home_team_mapped == away_hltv) & 
                        (df_odds.away_team_mapped == home_hltv) ) 
                    )
                    ]
    
    display(odds_row)

    if len(odds_row) != 1:
        print(f"Length is not 1! ({len(odds_row)})")
    else:
        op_home = odds_row['home_team_mapped'].iloc[0]
        op_away = odds_row['away_team_mapped'].iloc[0]
        op_home_odds = odds_row['home_odds'].iloc[0]
        op_away_odds = odds_row['away_odds'].iloc[0]

        if (home_hltv == op_home) & (away_hltv == op_away):
            ml_input_row['home_odds'] = op_home_odds
            ml_input_row['away_odds'] = op_away_odds
            ml_input_row['home_implied_odds'] = 1 / op_home_odds
            ml_input_row['away_implied_odds'] = 1 / op_away_odds
        elif (away_hltv == op_home) & (home_hltv == op_away):
            ml_input_row['home_odds'] = op_away_odds
            ml_input_row['away_odds'] = op_home_odds
            ml_input_row['home_implied_odds'] = 1 / op_away_odds
            ml_input_row['away_implied_odds'] = 1 / op_home_odds
        else:
            print("ERROR")

    return ml_input_row

In [10]:
# CSV manager

def match_id_duplicate(selected_match, save_path = "data/ml_input.csv"):
    # Load
    df = pd.read_csv(save_path)
    display(df)
    if df.empty:
        return False

    # Check id
    if int(selected_match['match_id']) in df['match_id'].values:
        print(f"Match ID ({selected_match['match_id']}) already exists!")
        return True
    else:
        return False

def update_csv(ml_input_row, save_path = "data/ml_input.csv"):
    # Load
    df = pd.read_csv(save_path)

    # Append
    new_row = pd.DataFrame.from_dict(ml_input_row, orient='index').T
    df = pd.concat([df, new_row], ignore_index=True)
    # Check duplicates
    df = df.drop_duplicates(subset=['match_id', 'team_home', 'team_away'],
                            keep='first')

    # Save
    df.to_csv(save_path, index=False)
    print(f"✅ Új sor mentve. ({len(df)})")

In [14]:
# MAIN

for event_id in tours.keys():
    target_matches = _target_match_scrape(event_id)

    for _, selected_match in target_matches.iterrows():
        
        if match_id_duplicate(selected_match):
            continue
        
        print(f"🎯 Kiválasztott meccs (index={_}):")
        print(f"  Match ID:   {selected_match['match_id']}")
        print(f"  Date:       {selected_match['date_parsed']}")
        print(f"  Teams:      {selected_match['team_home']} vs {selected_match['team_away']}")
        print(f"  Score:      {selected_match['score_home']} - {selected_match['score_away']}")
        print(f"  URL:        {selected_match['link']}")
        print()

        match_h2h = _h2h_match_scrape(selected_match)
        teams = _extract_teams(match_h2h)
        team_histories = _team_history_scrape(teams, selected_match)
        historical_h2h, rank_data = _historical_h2h_scrape(teams, team_histories, selected_match)
        ml_input_row1 = _calculate_rolling_features(teams, team_histories, historical_h2h)
        ml_input_row = _add_other_features(ml_input_row1, event_id, selected_match, teams, rank_data, match_h2h)
        ml_input_row = _parse_odds(ml_input_row)

        # DataFrame-ként megjelenítés
        ml_df = pd.DataFrame([ml_input_row])

        print("📊 DataFrame nézet:")
        display(ml_df.T.style.set_caption("ML Input Row - Transposed"))

        update_csv(ml_input_row, save_path = "data/ml_input.csv")

============================================================
1️⃣ TARGET MATCHES SCRAPING
============================================================
✅ 40 meccs találva

,match_id,event_id,date,team_home,team_away,score_home,score_away,map_type,rounds,link,date_clean,date_parsed
0,2380078,8292,March 16th 2025,MOUZ,Vitality,0,3,bo5,5,https://www.hltv.org/matches/2380078/mouz-vs-v...,March 16 2025,2025-03-16
1,2380076,8292,March 15th 2025,Vitality,The MongolZ,2,1,bo3,3,https://www.hltv.org/matches/2380076/vitality-...,March 15 2025,2025-03-15
2,2380077,8292,March 15th 2025,Spirit,MOUZ,1,2,bo3,3,https://www.hltv.org/matches/2380077/spirit-vs...,March 15 2025,2025-03-15

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380078) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380076) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380077) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380073) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380072) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380074) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380075) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380071) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380070) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380069) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380068) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380067) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380066) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380065) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380064) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380063) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380061) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380062) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380059) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380060) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380057) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380058) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380055) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380056) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380053) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380054) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380051) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380052) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380049) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380050) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380047) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380048) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380046) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380043) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380042) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380041) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380045) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380044) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380040) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2380039) already exists!

============================================================
1️⃣ TARGET MATCHES SCRAPING
============================================================

  ⚠️ Mérkőzés hiba: Message: no such element: Unable to locate element: {"method":"css selector","selector":".map-and-stars .map-text"}
  (Session info: chrome=141.0.7390.108); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
	GetHandleVerifier [0x0x7ff7118ae9e5+80021]
	GetHandleVerifier [0x0x7ff7118aea40+80112]
	(No symbol) [0x0x7ff71163060f]
	(No symbol) [0x0x7ff711688854]
	(No symbol) [0x0x7ff711688b1c]
	(No symbol) [0x0x7ff71167b19c]
	(No symbol) [0x0x7ff7116b126f]
	(No symbol) [0x0x7ff71167b056]
	(No symbol) [0x0x7ff7116b1440]
	(No symbol) [0x0x7ff7116d968a]
	(No symbol) [0x0x7ff7116b1003]
	(No symbol) [0x0x7ff7116795d1]
	(No symbol) [0x0x7ff71167a3f3]
	GetHandleVerifier [0x0x7ff711b6dd8d+2960445]
	GetHandleVerifier [0x0x7ff711b6804a+2936570]
	GetHandleVerifier [0x0x7ff711b88a87+3070263]
	GetHandleVerifier [0x0x7ff7118c84ce+185214]
	GetHandleVerifier [0x0x7ff7118cff1f+216527]
	GetHandleVerifier [0x0x7ff7118b7c24+117460]
	GetHandleVerifier [0x0x7ff7118b7ddf+117903]
	GetHandleVerifier [0x0x7ff71189dcb8+11112]
	BaseThreadInitThunk [0x0x7ffc5bd97374+20]
	RtlUserThreadStart [0x0x7ffc5d95cc91+33]

  ⚠️ Mérkőzés hiba: Message: no such element: Unable to locate element: {"method":"css selector","selector":".map-and-stars .map-text"}
  (Session info: chrome=141.0.7390.108); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
	GetHandleVerifier [0x0x7ff7118ae9e5+80021]
	GetHandleVerifier [0x0x7ff7118aea40+80112]
	(No symbol) [0x0x7ff71163060f]
	(No symbol) [0x0x7ff711688854]
	(No symbol) [0x0x7ff711688b1c]
	(No symbol) [0x0x7ff71167b19c]
	(No symbol) [0x0x7ff7116b126f]
	(No symbol) [0x0x7ff71167b056]
	(No symbol) [0x0x7ff7116b1440]
	(No symbol) [0x0x7ff7116d968a]
	(No symbol) [0x0x7ff7116b1003]
	(No symbol) [0x0x7ff7116795d1]
	(No symbol) [0x0x7ff71167a3f3]
	GetHandleVerifier [0x0x7ff711b6dd8d+2960445]
	GetHandleVerifier [0x0x7ff711b6804a+2936570]
	GetHandleVerifier [0x0x7ff711b88a87+3070263]
	GetHandleVerifier [0x0x7ff7118c84ce+185214]
	GetHandleVerifier [0x0x7ff7118cff1f+216527]
	GetHandleVerifier [0x0x7ff7118b7c24+117460]
	GetHandleVerifier [0x0x7ff7118b7ddf+117903]
	GetHandleVerifier [0x0x7ff71189dcb8+11112]
	BaseThreadInitThunk [0x0x7ffc5bd97374+20]
	RtlUserThreadStart [0x0x7ffc5d95cc91+33]

✅ 22 meccs találva

,match_id,event_id,date,team_home,team_away,score_home,score_away,map_type,rounds,link,date_clean,date_parsed
0,2384851,7907,September 2nd 2025,Spirit,G2,1,2,bo3,3,https://www.hltv.org/matches/2384851/spirit-vs...,September 2 2025,2025-09-02
1,2384850,7907,September 1st 2025,MOUZ,FURIA,0,2,bo3,3,https://www.hltv.org/matches/2384850/mouz-vs-f...,September 1 2025,2025-09-01
2,2384842,7907,September 1st 2025,Vitality,FaZe,2,1,bo3,3,https://www.hltv.org/matches/2384842/vitality-...,September 1 2025,2025-09-01

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384851) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384850) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384842) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384849) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384848) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384840) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384841) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384847) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384846) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384845) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384844) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384839) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384838) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384837) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384814) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384813) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384812) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384811) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384810) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384809) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384808) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2384807) already exists!

============================================================
1️⃣ TARGET MATCHES SCRAPING
============================================================
✅ 29 meccs találva

,match_id,event_id,date,team_home,team_away,score_home,score_away,map_type,rounds,link,date_clean,date_parsed
0,2383844,8038,August 3rd 2025,Spirit,MOUZ,3,0,bo5,5,https://www.hltv.org/matches/2383844/spirit-vs...,August 3 2025,2025-08-03
1,2383842,8038,August 2nd 2025,Vitality,MOUZ,0,2,bo3,3,https://www.hltv.org/matches/2383842/vitality-...,August 2 2025,2025-08-02
2,2383843,8038,August 2nd 2025,Spirit,Natus Vincere,2,1,bo3,3,https://www.hltv.org/matches/2383843/spirit-vs...,August 2 2025,2025-08-02

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383844) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383842) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383843) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383840) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383841) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383831) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383839) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383838) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383830) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383837) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383836) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383828) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383829) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383833) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383834) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383832) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383835) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383826) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383824) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383827) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383825) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383764) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383761) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383762) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383763) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383757) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383760) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383758) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2383759) already exists!

============================================================
1️⃣ TARGET MATCHES SCRAPING
============================================================
✅ 29 meccs találva

,match_id,event_id,date,team_home,team_away,score_home,score_away,map_type,rounds,link,date_clean,date_parsed
0,2381773,8036,April 27th 2025,Falcons,Vitality,2,3,bo5,5,https://www.hltv.org/matches/2381773/falcons-v...,April 27 2025,2025-04-27
1,2381772,8036,April 26th 2025,Vitality,The MongolZ,2,0,bo3,3,https://www.hltv.org/matches/2381772/vitality-...,April 26 2025,2025-04-26
2,2381771,8036,April 26th 2025,MOUZ,Falcons,0,2,bo3,3,https://www.hltv.org/matches/2381771/mouz-vs-f...,April 26 2025,2025-04-26

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2381773) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2381772) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2381771) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2381770) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2381769) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2381767) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2381768) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2381765) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2381766) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2381763) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2381764) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2381762) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2381761) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2381758) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

Match ID (2381760) already exists!

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2381764,8036,2025-04-23 00:00:00,Liquid,MIBR,https://www.hltv.org/matches/2381764/liquid-vs...,0.333333,0.2,0.666667,1.666667,...,0.6667,3,3,2,0,1,1.44,2.69,0.694444,0.371747
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092

🎯 Kiválasztott meccs (index=15):
  Match ID:   2381757
  Date:       2025-04-22 00:00:00
  Teams:      Virtus.pro vs FlyQuest
  Score:      0 - 2
  URL:        https://www.hltv.org/matches/2381757/virtuspro-vs-flyquest-iem-melbourne-2025


============================================================
3️⃣ MATCH H2H SCRAPING
============================================================
🔍 Scraping: https://www.hltv.org/matches/2381757/virtuspro-vs-flyquest-iem-melbourne-2025
✅ H2H data:

match_id                                                          2381757
home_team                                                      Virtus.pro
home_team_id                                                         5378
away_team                                                        FlyQuest
away_team_id                                                        12774
wins_home                                                               0
wins_away                                                               0
overtimes                                                               0
total_non_overtime                                                      0
home_win_rate                                                        None
home_team_avg_rating                                                  0.9
home_team_std_rating                                               0.1785
home_team_avg_ADR                                                    65.5
home_team_std_ADR                                                     9.7
home_team_avg_Swing                                                 -2.09
home_team_std_Swing                                                  3.14
away_team_avg_rating                                                1.232
away_team_std_rating                                               0.3423
away_team_avg_ADR                                                   72.22
away_team_std_ADR                                                   18.18
away_team_avg_Swing                                                  2.02
away_team_std_Swing                                                   4.0
maps_played                                                             2
home_maps_won                                                           0
away_maps_won                                                           2
home_maps_picked                                                        1
map_avg_score_diff                                                   -4.5
home_map_winrate                                                      0.0
maps_json               [{"map_name": "Inferno", "played": true, "home...
source_url              https://www.hltv.org/matches/2381757/virtuspro...
Name: 0, dtype: object

============================================================
4️⃣ TEAMS EXTRACTION
============================================================
✅ Teams extracted:
  Home: Virtus.pro (ID: 5378)
  Away: FlyQuest (ID: 12774)

============================================================
6️⃣ TEAM HISTORIES SCRAPING
============================================================

📈 Scraping history: Virtus.pro (ID: 5378)
🔍 Összesen 91 results-sublist betöltve
✅ 66 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
34,5378,2381642,April 21st 2025,Liquid,loss,1,2,bo3,https://www.hltv.org/matches/2381642/liquid-vs...,April 21 2025,2025-04-21
35,5378,2381328,April 11th 2025,G2,loss,0,2,bo3,https://www.hltv.org/matches/2381328/g2-vs-vir...,April 11 2025,2025-04-11
36,5378,2381322,April 10th 2025,Astralis,win,2,0,bo3,https://www.hltv.org/matches/2381322/astralis-...,April 10 2025,2025-04-10

📈 Scraping history: FlyQuest (ID: 12774)
🔍 Összesen 80 results-sublist betöltve
✅ 72 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
28,12774,2381641,April 21st 2025,Vitality,loss,0,2,bo3,https://www.hltv.org/matches/2381641/vitality-...,April 21 2025,2025-04-21
29,12774,2381630,April 17th 2025,SemperFi,win,2,0,bo3,https://www.hltv.org/matches/2381630/flyquest-...,April 17 2025,2025-04-17
30,12774,2381627,April 16th 2025,SemperFi,win,2,0,bo3,https://www.hltv.org/matches/2381627/semperfi-...,April 16 2025,2025-04-16

============================================================
7️⃣ HISTORICAL H2H SCRAPING
============================================================

🔍 Virtus.pro last 3 matches H2H scraping:
  [1/3] Scraping: 2025-04-21 vs Liquid
https://www.hltv.org/matches/2381642/liquid-vs-virtuspro-iem-melbourne-2025
  [2/3] Scraping: 2025-04-11 vs G2
https://www.hltv.org/matches/2381328/g2-vs-virtuspro-pgl-bucharest-2025
  [3/3] Scraping: 2025-04-10 vs Astralis
https://www.hltv.org/matches/2381322/astralis-vs-virtuspro-pgl-bucharest-2025

🔍 FlyQuest last 3 matches H2H scraping:
  [1/3] Scraping: 2025-04-21 vs Vitality
https://www.hltv.org/matches/2381641/vitality-vs-flyquest-iem-melbourne-2025
  [2/3] Scraping: 2025-04-17 vs SemperFi
https://www.hltv.org/matches/2381630/flyquest-vs-semperfi-blasttv-austin-major-2025-oceania-sea-regional-qualifier

⚠️ Timeout (próbálkozás 1/3)

  [3/3] Scraping: 2025-04-16 vs SemperFi
https://www.hltv.org/matches/2381627/semperfi-vs-flyquest-blasttv-austin-major-2025-oceania-sea-regional-qualifier

⚠️ Timeout (próbálkozás 1/3)
⚠️ Timeout (próbálkozás 2/3)

📊 Historical H2H stats összegzés:

{'avg_h2h_winrate': 0.5714285714285714,
 'avg_rating': 1.0213333333333334,
 'avg_rating_std': 0.17899999999999996,
 'avg_adr': 67.92666666666668,
 'avg_adr_std': 11.410000000000002,
 'avg_swing': 0.10666666666666669,
 'avg_swing_std': 2.703333333333333,
 'avg_maps_total': 2.3333333333333335,
 'avg_map_winrate': 0.42857142857142855,
 'avg_map_pickrate': 0.5714285714285714,
 'avg_map_score_diff': 0.3333333333333333,
 'avg_rank_diff': 0.6666666666666666,
 'std_rank_diff': 3.299831645537222,
 'avg_point_diff': -52.0,
 'std_point_diff': 157.96413094961358,
 'weak_opp_rank_diff': 3,
 'strong_opp_rank_diff': -4,
 'weak_opp_point_diff': 71,
 'strong_opp_point_diff': -275,
 'n_matches_scraped': 3}

{'avg_h2h_winrate': 1.0,
 'avg_rating': 1.1506666666666667,
 'avg_rating_std': 0.15046666666666667,
 'avg_adr': 79.85333333333334,
 'avg_adr_std': 7.896666666666666,
 'avg_swing': 0.5266666666666667,
 'avg_swing_std': 2.5566666666666666,
 'avg_maps_total': 2.0,
 'avg_map_winrate': 0.6666666666666666,
 'avg_map_pickrate': 0.5,
 'avg_map_score_diff': 1.5,
 'avg_rank_diff': 26.333333333333332,
 'std_rank_diff': 36.29814810090944,
 'avg_point_diff': -295.0,
 'std_point_diff': 466.6904755831214,
 'weak_opp_rank_diff': 52,
 'strong_opp_rank_diff': -25,
 'weak_opp_point_diff': 35,
 'strong_opp_point_diff': -955,
 'n_matches_scraped': 3}

============================================================
8️⃣ ROLLING FEATURES SZÁMÍTÁSA
============================================================

📊 Virtus.pro rolling features:
  Last 3 winrate:    0.333
  Last 5 winrate:    0.400
  Last 3 avg score:  1.0 - 1.3
  Current streak:    -2
  home_avg_h2h_winrate: 0.57
  home_avg_rating: 1.02
  home_avg_rating_std: 0.18
  home_avg_adr: 67.93
  home_avg_adr_std: 11.41
  home_avg_swing: 0.11
  home_avg_swing_std: 2.70
  home_avg_maps_total: 2.33
  home_avg_map_winrate: 0.43
  home_avg_map_pickrate: 0.57
  home_avg_map_score_diff: 0.33
  home_avg_rank_diff: 0.67
  home_std_rank_diff: 3.30
  home_avg_point_diff: -52.00
  home_std_point_diff: 157.96
  home_weak_opp_rank_diff: 3.00
  home_strong_opp_rank_diff: -4.00
  home_weak_opp_point_diff: 71.00
  home_strong_opp_point_diff: -275.00
  home_n_matches_scraped: 3.00

📊 FlyQuest rolling features:
  Last 3 winrate:    0.667
  Last 5 winrate:    0.600
  Last 3 avg score:  1.3 - 0.7
  Current streak:    -1
  away_avg_h2h_winrate: 1.00
  away_avg_rating: 1.15
  away_avg_rating_std: 0.15
  away_avg_adr: 79.85
  away_avg_adr_std: 7.90
  away_avg_swing: 0.53
  away_avg_swing_std: 2.56
  away_avg_maps_total: 2.00
  away_avg_map_winrate: 0.67
  away_avg_map_pickrate: 0.50
  away_avg_map_score_diff: 1.50
  away_avg_rank_diff: 26.33
  away_std_rank_diff: 36.30
  away_avg_point_diff: -295.00
  away_std_point_diff: 466.69
  away_weak_opp_rank_diff: 52.00
  away_strong_opp_rank_diff: -25.00
  away_weak_opp_point_diff: 35.00
  away_strong_opp_point_diff: -955.00
  away_n_matches_scraped: 3.00

📊 Difference features:
  Diff last 3 WR:    -0.333

============================================================
9️⃣ RANKINGS ÉS EGYÉB FEATURE-ÖK
============================================================
  Home rank: #10 (change: +0)
  Away rank: #26 (change: +0)
✅ Feature-ök összegyűjtve!

,Date,home_team,away_team,home_odds,away_odds,event_id,home_team_mapped,away_team_mapped
192,2025-04-22,Virtus.pro,FlyQuest,1.26,3.66,8036,Virtus.pro,FlyQuest

📊 DataFrame nézet:

✅ Új sor mentve. (107)

C:\Users\Adam\AppData\Local\Temp\ipykernel_4684\1115427491.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, new_row], ignore_index=True)

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,2381762,8036,2025-04-23 00:00:00,Complexity,GamerLegion,https://www.hltv.org/matches/2381762/complexit...,0.666667,0.6,1.666667,0.666667,...,NaN,0,3,1,2,0,1.77,2.00,0.564972,0.500000
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092
106,2381757,8036,2025-04-22 00:00:00,Virtus.pro,FlyQuest,https://www.hltv.org/matches/2381757/virtuspro...,0.333333,0.4,1.000000,1.333333,...,NaN,0,3,0,2,0,1.26,3.66,0.793651,0.273224

🎯 Kiválasztott meccs (index=16):
  Match ID:   2381759
  Date:       2025-04-22 00:00:00
  Teams:      Liquid vs Vitality
  Score:      0 - 2
  URL:        https://www.hltv.org/matches/2381759/liquid-vs-vitality-iem-melbourne-2025


============================================================
3️⃣ MATCH H2H SCRAPING
============================================================
🔍 Scraping: https://www.hltv.org/matches/2381759/liquid-vs-vitality-iem-melbourne-2025
✅ H2H data:

match_id                                                          2381759
home_team                                                          Liquid
home_team_id                                                         5973
away_team                                                        Vitality
away_team_id                                                         9565
wins_home                                                               2
wins_away                                                               8
overtimes                                                               1
total_non_overtime                                                     10
home_win_rate                                                         0.2
home_team_avg_rating                                                 0.85
home_team_std_rating                                               0.2281
home_team_avg_ADR                                                   68.26
home_team_std_ADR                                                   12.29
home_team_avg_Swing                                                 -2.99
home_team_std_Swing                                                  3.22
away_team_avg_rating                                                1.266
away_team_std_rating                                               0.2916
away_team_avg_ADR                                                   81.82
away_team_std_ADR                                                    10.5
away_team_avg_Swing                                                   2.9
away_team_std_Swing                                                  4.17
maps_played                                                             2
home_maps_won                                                           0
away_maps_won                                                           2
home_maps_picked                                                        1
map_avg_score_diff                                                   -6.5
home_map_winrate                                                      0.0
maps_json               [{"map_name": "Mirage", "played": true, "home_...
source_url              https://www.hltv.org/matches/2381759/liquid-vs...
Name: 0, dtype: object

============================================================
4️⃣ TEAMS EXTRACTION
============================================================
✅ Teams extracted:
  Home: Liquid (ID: 5973)
  Away: Vitality (ID: 9565)

============================================================
6️⃣ TEAM HISTORIES SCRAPING
============================================================

📈 Scraping history: Liquid (ID: 5973)
🔍 Összesen 87 results-sublist betöltve
❌ Hiba a history scraping közben: expected string or bytes-like object, got 'NoneType'

📈 Scraping history: Vitality (ID: 9565)
🔍 Összesen 96 results-sublist betöltve
✅ 56 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
44,9565,2381641,April 21st 2025,FlyQuest,win,2,0,bo3,https://www.hltv.org/matches/2381641/vitality-...,April 21 2025,2025-04-21
45,9565,2380134,March 30th 2025,MOUZ,win,3,2,bo5,https://www.hltv.org/matches/2380134/mouz-vs-v...,March 30 2025,2025-03-30
46,9565,2380132,March 30th 2025,Spirit,win,2,1,bo3,https://www.hltv.org/matches/2380132/vitality-...,March 30 2025,2025-03-30

============================================================
7️⃣ HISTORICAL H2H SCRAPING
============================================================

🔍 Liquid last 3 matches H2H scraping:
  ⚠️ Nincs history, skip

🔍 Vitality last 3 matches H2H scraping:
  [1/3] Scraping: 2025-04-21 vs FlyQuest
https://www.hltv.org/matches/2381641/vitality-vs-flyquest-iem-melbourne-2025
  [2/3] Scraping: 2025-03-30 vs MOUZ
https://www.hltv.org/matches/2380134/mouz-vs-vitality-blast-open-lisbon-2025
  [3/3] Scraping: 2025-03-30 vs Spirit
https://www.hltv.org/matches/2380132/vitality-vs-spirit-blast-open-lisbon-2025

📊 Historical H2H stats összegzés:

{}

{'avg_h2h_winrate': 0.6896551724137931,
 'avg_rating': 1.1706666666666667,
 'avg_rating_std': 0.2326666666666667,
 'avg_adr': 74.17333333333333,
 'avg_adr_std': 9.583333333333334,
 'avg_swing': 1.9233333333333331,
 'avg_swing_std': 3.3000000000000003,
 'avg_maps_total': 3.3333333333333335,
 'avg_map_winrate': 0.7,
 'avg_map_pickrate': 0.5,
 'avg_map_score_diff': 4.288888888888889,
 'avg_rank_diff': 8.666666666666666,
 'std_rank_diff': 11.614167593456232,
 'avg_point_diff': 401.0,
 'std_point_diff': 427.9470372215079,
 'weak_opp_rank_diff': 25,
 'strong_opp_rank_diff': -1,
 'weak_opp_point_diff': 955,
 'strong_opp_point_diff': -87,
 'n_matches_scraped': 3}

============================================================
8️⃣ ROLLING FEATURES SZÁMÍTÁSA
============================================================

📊 Liquid rolling features:
  ⚠️ Nincs history adat

📊 Vitality rolling features:
  Last 3 winrate:    1.000
  Last 5 winrate:    1.000
  Last 3 avg score:  2.3 - 1.0
  Current streak:    +17
  away_avg_h2h_winrate: 0.69
  away_avg_rating: 1.17
  away_avg_rating_std: 0.23
  away_avg_adr: 74.17
  away_avg_adr_std: 9.58
  away_avg_swing: 1.92
  away_avg_swing_std: 3.30
  away_avg_maps_total: 3.33
  away_avg_map_winrate: 0.70
  away_avg_map_pickrate: 0.50
  away_avg_map_score_diff: 4.29
  away_avg_rank_diff: 8.67
  away_std_rank_diff: 11.61
  away_avg_point_diff: 401.00
  away_std_point_diff: 427.95
  away_weak_opp_rank_diff: 25.00
  away_strong_opp_rank_diff: -1.00
  away_weak_opp_point_diff: 955.00
  away_strong_opp_point_diff: -87.00
  away_n_matches_scraped: 3.00

============================================================
9️⃣ RANKINGS ÉS EGYÉB FEATURE-ÖK
============================================================
  Home rank: #13 (change: +0)
  Away rank: #1 (change: +0)
✅ Feature-ök összegyűjtve!

,Date,home_team,away_team,home_odds,away_odds,event_id,home_team_mapped,away_team_mapped
193,2025-04-22,Team Liquid,Team Vitality,5.52,1.12,8036,Liquid,Vitality

📊 DataFrame nézet:

✅ Új sor mentve. (108)

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,2381761,8036,2025-04-23 00:00:00,FaZe,3DMAX,https://www.hltv.org/matches/2381761/faze-vs-3...,0.666667,0.6,1.333333,0.666667,...,1.0000,3,3,2,0,1,1.52,2.47,0.657895,0.404858
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092
106,2381757,8036,2025-04-22 00:00:00,Virtus.pro,FlyQuest,https://www.hltv.org/matches/2381757/virtuspro...,0.333333,0.4,1.000000,1.333333,...,NaN,0,3,0,2,0,1.26,3.66,0.793651,0.273224
107,2381759,8036,2025-04-22 00:00:00,Liquid,Vitality,https://www.hltv.org/matches/2381759/liquid-vs...,NaN,NaN,NaN,NaN,...,0.2000,10,3,0,2,0,5.52,1.12,0.181159,0.892857

🎯 Kiválasztott meccs (index=17):
  Match ID:   2381753
  Date:       2025-04-22 00:00:00
  Teams:      3DMAX vs BIG
  Score:      2 - 0
  URL:        https://www.hltv.org/matches/2381753/3dmax-vs-big-iem-melbourne-2025


============================================================
3️⃣ MATCH H2H SCRAPING
============================================================
🔍 Scraping: https://www.hltv.org/matches/2381753/3dmax-vs-big-iem-melbourne-2025
✅ H2H data:

match_id                                                          2381753
home_team                                                           3DMAX
home_team_id                                                         4914
away_team                                                             BIG
away_team_id                                                         7532
wins_home                                                               3
wins_away                                                               2
overtimes                                                               0
total_non_overtime                                                      5
home_win_rate                                                         0.6
home_team_avg_rating                                                1.218
home_team_std_rating                                                0.328
home_team_avg_ADR                                                   81.48
home_team_std_ADR                                                   19.18
home_team_avg_Swing                                                  1.55
home_team_std_Swing                                                  3.63
away_team_avg_rating                                                0.916
away_team_std_rating                                               0.1454
away_team_avg_ADR                                                   68.44
away_team_std_ADR                                                     7.9
away_team_avg_Swing                                                 -1.61
away_team_std_Swing                                                  2.17
maps_played                                                             2
home_maps_won                                                           2
away_maps_won                                                           0
home_maps_picked                                                        1
map_avg_score_diff                                                    5.5
home_map_winrate                                                      1.0
maps_json               [{"map_name": "Ancient", "played": true, "home...
source_url              https://www.hltv.org/matches/2381753/3dmax-vs-...
Name: 0, dtype: object

============================================================
4️⃣ TEAMS EXTRACTION
============================================================
✅ Teams extracted:
  Home: 3DMAX (ID: 4914)
  Away: BIG (ID: 7532)

============================================================
6️⃣ TEAM HISTORIES SCRAPING
============================================================

📈 Scraping history: 3DMAX (ID: 4914)
🔍 Összesen 92 results-sublist betöltve
❌ Hiba a history scraping közben: expected string or bytes-like object, got 'NoneType'

📈 Scraping history: BIG (ID: 7532)
🔍 Összesen 81 results-sublist betöltve
✅ 40 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
60,7532,2381637,April 21st 2025,MOUZ,loss,1,2,bo3,https://www.hltv.org/matches/2381637/mouz-vs-b...,April 21 2025,2025-04-21
61,7532,2381599,April 16th 2025,Astralis,loss,1,2,bo3,https://www.hltv.org/matches/2381599/astralis-...,April 16 2025,2025-04-16
62,7532,2381595,April 16th 2025,Nemiga,loss,0,2,bo3,https://www.hltv.org/matches/2381595/nemiga-vs...,April 16 2025,2025-04-16

============================================================
7️⃣ HISTORICAL H2H SCRAPING
============================================================

🔍 3DMAX last 3 matches H2H scraping:
  ⚠️ Nincs history, skip

🔍 BIG last 3 matches H2H scraping:
  [1/3] Scraping: 2025-04-21 vs MOUZ
https://www.hltv.org/matches/2381637/mouz-vs-big-iem-melbourne-2025
  [2/3] Scraping: 2025-04-16 vs Astralis
https://www.hltv.org/matches/2381599/astralis-vs-big-blasttv-austin-major-2025-europe-regional-qualifier
  [3/3] Scraping: 2025-04-16 vs Nemiga
https://www.hltv.org/matches/2381595/nemiga-vs-big-blasttv-austin-major-2025-europe-regional-qualifier

⚠️ Timeout (próbálkozás 1/3)

📊 Historical H2H stats összegzés:

{}

{'avg_h2h_winrate': 0.25,
 'avg_rating': 0.972,
 'avg_rating_std': 0.11646666666666666,
 'avg_adr': 69.49333333333334,
 'avg_adr_std': 9.6,
 'avg_swing': -1.0866666666666667,
 'avg_swing_std': 1.9466666666666665,
 'avg_maps_total': 2.6666666666666665,
 'avg_map_winrate': 0.25,
 'avg_map_pickrate': 0.625,
 'avg_map_score_diff': -3.1111111111111107,
 'avg_rank_diff': -9.666666666666666,
 'std_rank_diff': 10.656244908763853,
 'avg_point_diff': -233.33333333333334,
 'std_point_diff': 266.6399986665333,
 'weak_opp_rank_diff': 4,
 'strong_opp_rank_diff': -22,
 'weak_opp_point_diff': 12,
 'strong_opp_point_diff': -604,
 'n_matches_scraped': 3}

============================================================
8️⃣ ROLLING FEATURES SZÁMÍTÁSA
============================================================

📊 3DMAX rolling features:
  ⚠️ Nincs history adat

📊 BIG rolling features:
  Last 3 winrate:    N/A
  Last 5 winrate:    0.400
  Last 3 avg score:  0.7 - 2.0
  Current streak:    -3
  away_avg_h2h_winrate: 0.25
  away_avg_rating: 0.97
  away_avg_rating_std: 0.12
  away_avg_adr: 69.49
  away_avg_adr_std: 9.60
  away_avg_swing: -1.09
  away_avg_swing_std: 1.95
  away_avg_maps_total: 2.67
  away_avg_map_winrate: 0.25
  away_avg_map_pickrate: 0.62
  away_avg_map_score_diff: -3.11
  away_avg_rank_diff: -9.67
  away_std_rank_diff: 10.66
  away_avg_point_diff: -233.33
  away_std_point_diff: 266.64
  away_weak_opp_rank_diff: 4.00
  away_strong_opp_rank_diff: -22.00
  away_weak_opp_point_diff: 12.00
  away_strong_opp_point_diff: -604.00
  away_n_matches_scraped: 3.00

============================================================
9️⃣ RANKINGS ÉS EGYÉB FEATURE-ÖK
============================================================
  Home rank: #11 (change: +0)
  Away rank: #24 (change: -1)
✅ Feature-ök összegyűjtve!

,Date,home_team,away_team,home_odds,away_odds,event_id,home_team_mapped,away_team_mapped
194,2025-04-22,3DMAX,BIG,1.52,2.45,8036,3DMAX,BIG

📊 DataFrame nézet:

✅ Új sor mentve. (109)

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,2381758,8036,2025-04-22 00:00:00,SAW,MIBR,https://www.hltv.org/matches/2381758/saw-vs-mi...,0.333333,0.4,0.666667,1.666667,...,NaN,0,3,1,2,0,2.09,1.70,0.478469,0.588235
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092
106,2381757,8036,2025-04-22 00:00:00,Virtus.pro,FlyQuest,https://www.hltv.org/matches/2381757/virtuspro...,0.333333,0.4,1.000000,1.333333,...,NaN,0,3,0,2,0,1.26,3.66,0.793651,0.273224
107,2381759,8036,2025-04-22 00:00:00,Liquid,Vitality,https://www.hltv.org/matches/2381759/liquid-vs...,NaN,NaN,NaN,NaN,...,0.2000,10,3,0,2,0,5.52,1.12,0.181159,0.892857
108,2381753,8036,2025-04-22 00:00:00,3DMAX,BIG,https://www.hltv.org/matches/2381753/3dmax-vs-...,NaN,NaN,NaN,NaN,...,0.6000,5,3,2,0,1,1.52,2.45,0.657895,0.408163

🎯 Kiválasztott meccs (index=18):
  Match ID:   2381756
  Date:       2025-04-22 00:00:00
  Teams:      FaZe vs The MongolZ
  Score:      0 - 2
  URL:        https://www.hltv.org/matches/2381756/faze-vs-the-mongolz-iem-melbourne-2025


============================================================
3️⃣ MATCH H2H SCRAPING
============================================================
🔍 Scraping: https://www.hltv.org/matches/2381756/faze-vs-the-mongolz-iem-melbourne-2025
✅ H2H data:

match_id                                                          2381756
home_team                                                            FaZe
home_team_id                                                         6667
away_team                                                     The MongolZ
away_team_id                                                         6248
wins_home                                                               0
wins_away                                                               0
overtimes                                                               0
total_non_overtime                                                      0
home_win_rate                                                        None
home_team_avg_rating                                                0.934
home_team_std_rating                                               0.1584
home_team_avg_ADR                                                   69.64
home_team_std_ADR                                                    7.68
home_team_avg_Swing                                                 -1.31
home_team_std_Swing                                                  1.79
away_team_avg_rating                                                1.122
away_team_std_rating                                               0.2106
away_team_avg_ADR                                                   74.32
away_team_std_ADR                                                   10.94
away_team_avg_Swing                                                  1.31
away_team_std_Swing                                                  2.38
maps_played                                                             2
home_maps_won                                                           0
away_maps_won                                                           2
home_maps_picked                                                        1
map_avg_score_diff                                                   -4.0
home_map_winrate                                                      0.0
maps_json               [{"map_name": "Dust2", "played": true, "home_w...
source_url              https://www.hltv.org/matches/2381756/faze-vs-t...
Name: 0, dtype: object

============================================================
4️⃣ TEAMS EXTRACTION
============================================================
✅ Teams extracted:
  Home: FaZe (ID: 6667)
  Away: The MongolZ (ID: 6248)

============================================================
6️⃣ TEAM HISTORIES SCRAPING
============================================================

📈 Scraping history: FaZe (ID: 6667)
🔍 Összesen 91 results-sublist betöltve
✅ 51 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
49,6667,2381639,April 21st 2025,paiN,win,2,0,bo3,https://www.hltv.org/matches/2381639/faze-vs-p...,April 21 2025,2025-04-21
50,6667,2381331,April 13th 2025,Complexity,win,2,0,bo3,https://www.hltv.org/matches/2381331/faze-vs-c...,April 13 2025,2025-04-13
51,6667,2381329,April 12th 2025,Falcons,loss,1,2,bo3,https://www.hltv.org/matches/2381329/falcons-v...,April 12 2025,2025-04-12

📈 Scraping history: The MongolZ (ID: 6248)
🔍 Összesen 94 results-sublist betöltve
❌ Hiba a history scraping közben: expected string or bytes-like object, got 'NoneType'

============================================================
7️⃣ HISTORICAL H2H SCRAPING
============================================================

🔍 FaZe last 3 matches H2H scraping:
  [1/3] Scraping: 2025-04-21 vs paiN
https://www.hltv.org/matches/2381639/faze-vs-pain-iem-melbourne-2025
  [2/3] Scraping: 2025-04-13 vs Complexity
https://www.hltv.org/matches/2381331/faze-vs-complexity-pgl-bucharest-2025

⚠️ Timeout (próbálkozás 1/3)

  [3/3] Scraping: 2025-04-12 vs Falcons
https://www.hltv.org/matches/2381329/falcons-vs-faze-pgl-bucharest-2025

⚠️ Timeout (próbálkozás 1/3)
⚠️ Timeout (próbálkozás 2/3)

🔍 The MongolZ last 3 matches H2H scraping:
  ⚠️ Nincs history, skip

📊 Historical H2H stats összegzés:

{'avg_h2h_winrate': 0.45454545454545453,
 'avg_rating': 1.05,
 'avg_rating_std': 0.12976666666666667,
 'avg_adr': 73.20666666666666,
 'avg_adr_std': 8.633333333333333,
 'avg_swing': 0.16,
 'avg_swing_std': 1.7433333333333332,
 'avg_maps_total': 2.3333333333333335,
 'avg_map_winrate': 0.7142857142857143,
 'avg_map_pickrate': 0.5714285714285714,
 'avg_map_score_diff': 0.38888888888888884,
 'avg_rank_diff': 7.333333333333333,
 'std_rank_diff': 4.9216076867444665,
 'avg_point_diff': 175.66666666666666,
 'std_point_diff': 65.79935832176143,
 'weak_opp_rank_diff': 13,
 'strong_opp_rank_diff': 1,
 'weak_opp_point_diff': 254,
 'strong_opp_point_diff': 93,
 'n_matches_scraped': 3}

{}

============================================================
8️⃣ ROLLING FEATURES SZÁMÍTÁSA
============================================================

📊 FaZe rolling features:
  Last 3 winrate:    0.667
  Last 5 winrate:    0.800
  Last 3 avg score:  1.7 - 0.7
  Current streak:    +2
  home_avg_h2h_winrate: 0.45
  home_avg_rating: 1.05
  home_avg_rating_std: 0.13
  home_avg_adr: 73.21
  home_avg_adr_std: 8.63
  home_avg_swing: 0.16
  home_avg_swing_std: 1.74
  home_avg_maps_total: 2.33
  home_avg_map_winrate: 0.71
  home_avg_map_pickrate: 0.57
  home_avg_map_score_diff: 0.39
  home_avg_rank_diff: 7.33
  home_std_rank_diff: 4.92
  home_avg_point_diff: 175.67
  home_std_point_diff: 65.80
  home_weak_opp_rank_diff: 13.00
  home_strong_opp_rank_diff: 1.00
  home_weak_opp_point_diff: 254.00
  home_strong_opp_point_diff: 93.00
  home_n_matches_scraped: 3.00

📊 The MongolZ rolling features:
  ⚠️ Nincs history adat

============================================================
9️⃣ RANKINGS ÉS EGYÉB FEATURE-ÖK
============================================================
  Home rank: #8 (change: +0)
  Away rank: #7 (change: +0)
✅ Feature-ök összegyűjtve!

,Date,home_team,away_team,home_odds,away_odds,event_id,home_team_mapped,away_team_mapped
195,2025-04-22,FaZe Clan,The Mongolz,1.94,1.82,8036,FaZe,The MongolZ

📊 DataFrame nézet:

✅ Új sor mentve. (110)

C:\Users\Adam\AppData\Local\Temp\ipykernel_4684\1115427491.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, new_row], ignore_index=True)

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,2381760,8036,2025-04-22 00:00:00,Falcons,Natus Vincere,https://www.hltv.org/matches/2381760/falcons-v...,1.000000,1.0,2.333333,0.333333,...,NaN,0,3,2,1,1,1.72,2.07,0.581395,0.483092
106,2381757,8036,2025-04-22 00:00:00,Virtus.pro,FlyQuest,https://www.hltv.org/matches/2381757/virtuspro...,0.333333,0.4,1.000000,1.333333,...,NaN,0,3,0,2,0,1.26,3.66,0.793651,0.273224
107,2381759,8036,2025-04-22 00:00:00,Liquid,Vitality,https://www.hltv.org/matches/2381759/liquid-vs...,NaN,NaN,NaN,NaN,...,0.2000,10,3,0,2,0,5.52,1.12,0.181159,0.892857
108,2381753,8036,2025-04-22 00:00:00,3DMAX,BIG,https://www.hltv.org/matches/2381753/3dmax-vs-...,NaN,NaN,NaN,NaN,...,0.6000,5,3,2,0,1,1.52,2.45,0.657895,0.408163
109,2381756,8036,2025-04-22 00:00:00,FaZe,The MongolZ,https://www.hltv.org/matches/2381756/faze-vs-t...,0.666667,0.8,1.666667,0.666667,...,NaN,0,3,0,2,0,1.94,1.82,0.515464,0.549451

🎯 Kiválasztott meccs (index=19):
  Match ID:   2381755
  Date:       2025-04-22 00:00:00
  Teams:      GamerLegion vs MOUZ
  Score:      0 - 2
  URL:        https://www.hltv.org/matches/2381755/gamerlegion-vs-mouz-iem-melbourne-2025


============================================================
3️⃣ MATCH H2H SCRAPING
============================================================
🔍 Scraping: https://www.hltv.org/matches/2381755/gamerlegion-vs-mouz-iem-melbourne-2025
✅ H2H data:

match_id                                                          2381755
home_team                                                     GamerLegion
home_team_id                                                         9928
away_team                                                            MOUZ
away_team_id                                                         4494
wins_home                                                               2
wins_away                                                               0
overtimes                                                               0
total_non_overtime                                                      2
home_win_rate                                                         1.0
home_team_avg_rating                                                0.932
home_team_std_rating                                                0.116
home_team_avg_ADR                                                   69.94
home_team_std_ADR                                                   10.62
home_team_avg_Swing                                                 -1.75
home_team_std_Swing                                                  2.01
away_team_avg_rating                                                1.194
away_team_std_rating                                               0.1519
away_team_avg_ADR                                                   81.88
away_team_std_ADR                                                   10.79
away_team_avg_Swing                                                  1.75
away_team_std_Swing                                                  2.49
maps_played                                                             2
home_maps_won                                                           0
away_maps_won                                                           2
home_maps_picked                                                        1
map_avg_score_diff                                                   -5.0
home_map_winrate                                                      0.0
maps_json               [{"map_name": "Inferno", "played": true, "home...
source_url              https://www.hltv.org/matches/2381755/gamerlegi...
Name: 0, dtype: object

============================================================
4️⃣ TEAMS EXTRACTION
============================================================
✅ Teams extracted:
  Home: GamerLegion (ID: 9928)
  Away: MOUZ (ID: 4494)

============================================================
6️⃣ TEAM HISTORIES SCRAPING
============================================================

📈 Scraping history: GamerLegion (ID: 9928)
🔍 Összesen 87 results-sublist betöltve
✅ 62 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
38,9928,2381638,April 21st 2025,3DMAX,win,2,0,bo3,https://www.hltv.org/matches/2381638/3dmax-vs-...,April 21 2025,2025-04-21
39,9928,2381593,April 16th 2025,SAW,loss,1,2,bo3,https://www.hltv.org/matches/2381593/saw-vs-ga...,April 16 2025,2025-04-16
40,9928,2381584,April 15th 2025,500,win,2,0,bo3,https://www.hltv.org/matches/2381584/gamerlegi...,April 15 2025,2025-04-15

📈 Scraping history: MOUZ (ID: 4494)
🔍 Összesen 94 results-sublist betöltve
✅ 57 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
43,4494,2381637,April 21st 2025,BIG,win,2,1,bo3,https://www.hltv.org/matches/2381637/mouz-vs-b...,April 21 2025,2025-04-21
44,4494,2380134,March 30th 2025,Vitality,loss,2,3,bo5,https://www.hltv.org/matches/2380134/mouz-vs-v...,March 30 2025,2025-03-30
45,4494,2380133,March 29th 2025,Eternal Fire,win,2,0,bo3,https://www.hltv.org/matches/2380133/eternal-f...,March 29 2025,2025-03-29

============================================================
7️⃣ HISTORICAL H2H SCRAPING
============================================================

🔍 GamerLegion last 3 matches H2H scraping:
  [1/3] Scraping: 2025-04-21 vs 3DMAX
https://www.hltv.org/matches/2381638/3dmax-vs-gamerlegion-iem-melbourne-2025

⚠️ Timeout (próbálkozás 1/3)
⚠️ Timeout (próbálkozás 2/3)

  [2/3] Scraping: 2025-04-16 vs SAW
https://www.hltv.org/matches/2381593/saw-vs-gamerlegion-blasttv-austin-major-2025-europe-regional-qualifier
  [3/3] Scraping: 2025-04-15 vs 500
https://www.hltv.org/matches/2381584/gamerlegion-vs-500-blasttv-austin-major-2025-europe-regional-qualifier

🔍 MOUZ last 3 matches H2H scraping:
  [1/3] Scraping: 2025-04-21 vs BIG
https://www.hltv.org/matches/2381637/mouz-vs-big-iem-melbourne-2025
  [2/3] Scraping: 2025-03-30 vs Vitality
https://www.hltv.org/matches/2380134/mouz-vs-vitality-blast-open-lisbon-2025
  [3/3] Scraping: 2025-03-29 vs Eternal Fire
https://www.hltv.org/matches/2380133/eternal-fire-vs-mouz-blast-open-lisbon-2025

📊 Historical H2H stats összegzés:

{'avg_h2h_winrate': 0.8,
 'avg_rating': 1.2966666666666666,
 'avg_rating_std': 0.23396666666666666,
 'avg_adr': 77.49333333333334,
 'avg_adr_std': 11.64,
 'avg_swing': 2.9166666666666665,
 'avg_swing_std': 2.9066666666666663,
 'avg_maps_total': 2.3333333333333335,
 'avg_map_winrate': 0.7142857142857143,
 'avg_map_pickrate': 0.5714285714285714,
 'avg_map_score_diff': 6.0,
 'avg_rank_diff': 11.333333333333334,
 'std_rank_diff': 12.81492185782739,
 'avg_point_diff': 79.33333333333333,
 'std_point_diff': 72.30644661592922,
 'weak_opp_rank_diff': 29,
 'strong_opp_rank_diff': -1,
 'weak_opp_point_diff': 166,
 'strong_opp_point_diff': -11,
 'n_matches_scraped': 3}

{'avg_h2h_winrate': 0.40625,
 'avg_rating': 1.044,
 'avg_rating_std': 0.11736666666666667,
 'avg_adr': 72.60666666666667,
 'avg_adr_std': 7.0200000000000005,
 'avg_swing': -0.15000000000000005,
 'avg_swing_std': 1.6566666666666665,
 'avg_maps_total': 3.3333333333333335,
 'avg_map_winrate': 0.6,
 'avg_map_pickrate': 0.4,
 'avg_map_score_diff': -0.34444444444444455,
 'avg_rank_diff': 7.0,
 'std_rank_diff': 10.677078252031311,
 'avg_point_diff': 95.33333333333333,
 'std_point_diff': 387.3261617236248,
 'weak_opp_rank_diff': 22,
 'strong_opp_rank_diff': -2,
 'weak_opp_point_diff': 604,
 'strong_opp_point_diff': -335,
 'n_matches_scraped': 3}

============================================================
8️⃣ ROLLING FEATURES SZÁMÍTÁSA
============================================================

📊 GamerLegion rolling features:
  Last 3 winrate:    0.667
  Last 5 winrate:    0.400
  Last 3 avg score:  1.7 - 0.7
  Current streak:    +1
  home_avg_h2h_winrate: 0.80
  home_avg_rating: 1.30
  home_avg_rating_std: 0.23
  home_avg_adr: 77.49
  home_avg_adr_std: 11.64
  home_avg_swing: 2.92
  home_avg_swing_std: 2.91
  home_avg_maps_total: 2.33
  home_avg_map_winrate: 0.71
  home_avg_map_pickrate: 0.57
  home_avg_map_score_diff: 6.00
  home_avg_rank_diff: 11.33
  home_std_rank_diff: 12.81
  home_avg_point_diff: 79.33
  home_std_point_diff: 72.31
  home_weak_opp_rank_diff: 29.00
  home_strong_opp_rank_diff: -1.00
  home_weak_opp_point_diff: 166.00
  home_strong_opp_point_diff: -11.00
  home_n_matches_scraped: 3.00

📊 MOUZ rolling features:
  Last 3 winrate:    0.667
  Last 5 winrate:    0.600
  Last 3 avg score:  2.0 - 1.3
  Current streak:    +1
  away_avg_h2h_winrate: 0.41
  away_avg_rating: 1.04
  away_avg_rating_std: 0.12
  away_avg_adr: 72.61
  away_avg_adr_std: 7.02
  away_avg_swing: -0.15
  away_avg_swing_std: 1.66
  away_avg_maps_total: 3.33
  away_avg_map_winrate: 0.60
  away_avg_map_pickrate: 0.40
  away_avg_map_score_diff: -0.34
  away_avg_rank_diff: 7.00
  away_std_rank_diff: 10.68
  away_avg_point_diff: 95.33
  away_std_point_diff: 387.33
  away_weak_opp_rank_diff: 22.00
  away_strong_opp_rank_diff: -2.00
  away_weak_opp_point_diff: 604.00
  away_strong_opp_point_diff: -335.00
  away_n_matches_scraped: 3.00

📊 Difference features:
  Diff last 3 WR:    +0.000

============================================================
9️⃣ RANKINGS ÉS EGYÉB FEATURE-ÖK
============================================================
  Home rank: #12 (change: +0)
  Away rank: #3 (change: +0)
✅ Feature-ök összegyűjtve!

,Date,home_team,away_team,home_odds,away_odds,event_id,home_team_mapped,away_team_mapped
197,2025-04-22,GamerLegion,MOUZ,3.63,1.26,8036,GamerLegion,MOUZ

📊 DataFrame nézet:

✅ Új sor mentve. (111)

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,2381757,8036,2025-04-22 00:00:00,Virtus.pro,FlyQuest,https://www.hltv.org/matches/2381757/virtuspro...,0.333333,0.4,1.000000,1.333333,...,NaN,0,3,0,2,0,1.26,3.66,0.793651,0.273224
107,2381759,8036,2025-04-22 00:00:00,Liquid,Vitality,https://www.hltv.org/matches/2381759/liquid-vs...,NaN,NaN,NaN,NaN,...,0.2000,10,3,0,2,0,5.52,1.12,0.181159,0.892857
108,2381753,8036,2025-04-22 00:00:00,3DMAX,BIG,https://www.hltv.org/matches/2381753/3dmax-vs-...,NaN,NaN,NaN,NaN,...,0.6000,5,3,2,0,1,1.52,2.45,0.657895,0.408163
109,2381756,8036,2025-04-22 00:00:00,FaZe,The MongolZ,https://www.hltv.org/matches/2381756/faze-vs-t...,0.666667,0.8,1.666667,0.666667,...,NaN,0,3,0,2,0,1.94,1.82,0.515464,0.549451
110,2381755,8036,2025-04-22 00:00:00,GamerLegion,MOUZ,https://www.hltv.org/matches/2381755/gamerlegi...,0.666667,0.4,1.666667,0.666667,...,1.0000,2,3,0,2,0,3.63,1.26,0.275482,0.793651

🎯 Kiválasztott meccs (index=20):
  Match ID:   2381754
  Date:       2025-04-22 00:00:00
  Teams:      paiN vs Complexity
  Score:      0 - 2
  URL:        https://www.hltv.org/matches/2381754/pain-vs-complexity-iem-melbourne-2025


============================================================
3️⃣ MATCH H2H SCRAPING
============================================================
🔍 Scraping: https://www.hltv.org/matches/2381754/pain-vs-complexity-iem-melbourne-2025
✅ H2H data:

match_id                                                          2381754
home_team                                                            paiN
home_team_id                                                         4773
away_team                                                      Complexity
away_team_id                                                         5005
wins_home                                                               0
wins_away                                                               0
overtimes                                                               0
total_non_overtime                                                      0
home_win_rate                                                        None
home_team_avg_rating                                                0.738
home_team_std_rating                                               0.3018
home_team_avg_ADR                                                   60.72
home_team_std_ADR                                                   19.54
home_team_avg_Swing                                                 -3.46
home_team_std_Swing                                                  4.36
away_team_avg_rating                                                1.364
away_team_std_rating                                               0.1294
away_team_avg_ADR                                                   86.66
away_team_std_ADR                                                   14.23
away_team_avg_Swing                                                  3.46
away_team_std_Swing                                                  1.88
maps_played                                                             2
home_maps_won                                                           0
away_maps_won                                                           2
home_maps_picked                                                        1
map_avg_score_diff                                                   -9.0
home_map_winrate                                                      0.0
maps_json               [{"map_name": "Train", "played": true, "home_w...
source_url              https://www.hltv.org/matches/2381754/pain-vs-c...
Name: 0, dtype: object

============================================================
4️⃣ TEAMS EXTRACTION
============================================================
✅ Teams extracted:
  Home: paiN (ID: 4773)
  Away: Complexity (ID: 5005)

============================================================
6️⃣ TEAM HISTORIES SCRAPING
============================================================

📈 Scraping history: paiN (ID: 4773)
🔍 Összesen 82 results-sublist betöltve
✅ 65 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
35,4773,2381639,April 21st 2025,FaZe,loss,0,2,bo3,https://www.hltv.org/matches/2381639/faze-vs-p...,April 21 2025,2025-04-21
36,4773,2381313,April 8th 2025,Falcons,loss,1,2,bo3,https://www.hltv.org/matches/2381313/falcons-v...,April 8 2025,2025-04-08
37,4773,2381307,April 7th 2025,FaZe,loss,0,2,bo3,https://www.hltv.org/matches/2381307/faze-vs-p...,April 7 2025,2025-04-07

📈 Scraping history: Complexity (ID: 5005)
🔍 Összesen 87 results-sublist betöltve
✅ 88 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
12,5005,2381640,April 21st 2025,The MongolZ,loss,1,2,bo3,https://www.hltv.org/matches/2381640/the-mongo...,April 21 2025,2025-04-21
13,5005,2381612,April 16th 2025,BLUEJAYS,win,2,0,bo3,https://www.hltv.org/matches/2381612/complexit...,April 16 2025,2025-04-16
14,5005,2381607,April 15th 2025,Getting Info,win,2,0,bo3,https://www.hltv.org/matches/2381607/complexit...,April 15 2025,2025-04-15

============================================================
7️⃣ HISTORICAL H2H SCRAPING
============================================================

🔍 paiN last 3 matches H2H scraping:
  [1/3] Scraping: 2025-04-21 vs FaZe
https://www.hltv.org/matches/2381639/faze-vs-pain-iem-melbourne-2025
  [2/3] Scraping: 2025-04-08 vs Falcons
https://www.hltv.org/matches/2381313/falcons-vs-pain-pgl-bucharest-2025
  [3/3] Scraping: 2025-04-07 vs FaZe
https://www.hltv.org/matches/2381307/faze-vs-pain-pgl-bucharest-2025

🔍 Complexity last 3 matches H2H scraping:
  [1/3] Scraping: 2025-04-21 vs The MongolZ
https://www.hltv.org/matches/2381640/the-mongolz-vs-complexity-iem-melbourne-2025
  [2/3] Scraping: 2025-04-16 vs BLUEJAYS
https://www.hltv.org/matches/2381612/complexity-vs-bluejays-blasttv-austin-major-2025-north-america-regional-qualifier
  [3/3] Scraping: 2025-04-15 vs Getting Info
https://www.hltv.org/matches/2381607/complexity-vs-getting-info-blasttv-austin-major-2025-north-america-regional-qualifier

📊 Historical H2H stats összegzés:

{'avg_h2h_winrate': 0.5555555555555556,
 'avg_rating': 0.9506666666666667,
 'avg_rating_std': 0.18883333333333333,
 'avg_adr': 67.63333333333334,
 'avg_adr_std': 13.956666666666669,
 'avg_swing': -1.0866666666666667,
 'avg_swing_std': 2.7533333333333334,
 'avg_maps_total': 2.3333333333333335,
 'avg_map_winrate': 0.14285714285714285,
 'avg_map_pickrate': 0.5714285714285714,
 'avg_map_score_diff': -2.222222222222222,
 'avg_rank_diff': -7.666666666666667,
 'std_rank_diff': 0.4714045207910317,
 'avg_point_diff': -157.33333333333334,
 'std_point_diff': 41.58792559812951,
 'weak_opp_rank_diff': -7,
 'strong_opp_rank_diff': -8,
 'weak_opp_point_diff': -99,
 'strong_opp_point_diff': -193,
 'n_matches_scraped': 3}

{'avg_h2h_winrate': 0.3333333333333333,
 'avg_rating': 1.088,
 'avg_rating_std': 0.15926666666666667,
 'avg_adr': 76.98666666666666,
 'avg_adr_std': 9.266666666666667,
 'avg_swing': 0.36666666666666664,
 'avg_swing_std': 2.0466666666666664,
 'avg_maps_total': 2.3333333333333335,
 'avg_map_winrate': 0.7142857142857143,
 'avg_map_pickrate': 0.5714285714285714,
 'avg_map_score_diff': 1.888888888888889,
 'avg_rank_diff': 19.0,
 'std_rank_diff': 19.096247449870006,
 'avg_point_diff': -14.0,
 'std_point_diff': 186.67619023324855,
 'weak_opp_rank_diff': 33,
 'strong_opp_rank_diff': -8,
 'weak_opp_point_diff': 118,
 'strong_opp_point_diff': -278,
 'n_matches_scraped': 3}

============================================================
8️⃣ ROLLING FEATURES SZÁMÍTÁSA
============================================================

📊 paiN rolling features:
  Last 3 winrate:    N/A
  Last 5 winrate:    N/A
  Last 3 avg score:  0.3 - 2.0
  Current streak:    -6
  home_avg_h2h_winrate: 0.56
  home_avg_rating: 0.95
  home_avg_rating_std: 0.19
  home_avg_adr: 67.63
  home_avg_adr_std: 13.96
  home_avg_swing: -1.09
  home_avg_swing_std: 2.75
  home_avg_maps_total: 2.33
  home_avg_map_winrate: 0.14
  home_avg_map_pickrate: 0.57
  home_avg_map_score_diff: -2.22
  home_avg_rank_diff: -7.67
  home_std_rank_diff: 0.47
  home_avg_point_diff: -157.33
  home_std_point_diff: 41.59
  home_weak_opp_rank_diff: -7.00
  home_strong_opp_rank_diff: -8.00
  home_weak_opp_point_diff: -99.00
  home_strong_opp_point_diff: -193.00
  home_n_matches_scraped: 3.00

📊 Complexity rolling features:
  Last 3 winrate:    0.667
  Last 5 winrate:    0.400
  Last 3 avg score:  1.7 - 0.7
  Current streak:    -1
  away_avg_h2h_winrate: 0.33
  away_avg_rating: 1.09
  away_avg_rating_std: 0.16
  away_avg_adr: 76.99
  away_avg_adr_std: 9.27
  away_avg_swing: 0.37
  away_avg_swing_std: 2.05
  away_avg_maps_total: 2.33
  away_avg_map_winrate: 0.71
  away_avg_map_pickrate: 0.57
  away_avg_map_score_diff: 1.89
  away_avg_rank_diff: 19.00
  away_std_rank_diff: 19.10
  away_avg_point_diff: -14.00
  away_std_point_diff: 186.68
  away_weak_opp_rank_diff: 33.00
  away_strong_opp_rank_diff: -8.00
  away_weak_opp_point_diff: 118.00
  away_strong_opp_point_diff: -278.00
  away_n_matches_scraped: 3.00

📊 Difference features:
  Diff last 3 WR:    -0.667

============================================================
9️⃣ RANKINGS ÉS EGYÉB FEATURE-ÖK
============================================================
  Home rank: #17 (change: +1)
  Away rank: #14 (change: -1)
✅ Feature-ök összegyűjtve!

,Date,home_team,away_team,home_odds,away_odds,event_id,home_team_mapped,away_team_mapped
196,2025-04-22,paiN Gaming,compLexity Gaming,4.61,1.18,8036,paiN,Complexity

📊 DataFrame nézet:

✅ Új sor mentve. (112)

C:\Users\Adam\AppData\Local\Temp\ipykernel_4684\1115427491.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, new_row], ignore_index=True)

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,2381759,8036,2025-04-22 00:00:00,Liquid,Vitality,https://www.hltv.org/matches/2381759/liquid-vs...,NaN,NaN,NaN,NaN,...,0.2000,10,3,0,2,0,5.52,1.12,0.181159,0.892857
108,2381753,8036,2025-04-22 00:00:00,3DMAX,BIG,https://www.hltv.org/matches/2381753/3dmax-vs-...,NaN,NaN,NaN,NaN,...,0.6000,5,3,2,0,1,1.52,2.45,0.657895,0.408163
109,2381756,8036,2025-04-22 00:00:00,FaZe,The MongolZ,https://www.hltv.org/matches/2381756/faze-vs-t...,0.666667,0.8,1.666667,0.666667,...,NaN,0,3,0,2,0,1.94,1.82,0.515464,0.549451
110,2381755,8036,2025-04-22 00:00:00,GamerLegion,MOUZ,https://www.hltv.org/matches/2381755/gamerlegi...,0.666667,0.4,1.666667,0.666667,...,1.0000,2,3,0,2,0,3.63,1.26,0.275482,0.793651
111,2381754,8036,2025-04-22 00:00:00,paiN,Complexity,https://www.hltv.org/matches/2381754/pain-vs-c...,0.000000,0.0,0.333333,2.000000,...,NaN,0,3,0,2,0,4.61,1.18,0.216920,0.847458

🎯 Kiválasztott meccs (index=21):
  Match ID:   2381644
  Date:       2025-04-21 00:00:00
  Teams:      Natus Vincere vs MIBR
  Score:      2 - 1
  URL:        https://www.hltv.org/matches/2381644/natus-vincere-vs-mibr-iem-melbourne-2025


============================================================
3️⃣ MATCH H2H SCRAPING
============================================================
🔍 Scraping: https://www.hltv.org/matches/2381644/natus-vincere-vs-mibr-iem-melbourne-2025

⚠️ Timeout (próbálkozás 1/3)

✅ H2H data:

match_id                                                          2381644
home_team                                                   Natus Vincere
home_team_id                                                         4608
away_team                                                            MIBR
away_team_id                                                         9215
wins_home                                                               0
wins_away                                                               1
overtimes                                                               0
total_non_overtime                                                      1
home_win_rate                                                         0.0
home_team_avg_rating                                                1.078
home_team_std_rating                                               0.1375
home_team_avg_ADR                                                   71.42
home_team_std_ADR                                                   10.24
home_team_avg_Swing                                                  0.78
home_team_std_Swing                                                  2.14
away_team_avg_rating                                                0.946
away_team_std_rating                                               0.1705
away_team_avg_ADR                                                   66.76
away_team_std_ADR                                                    5.39
away_team_avg_Swing                                                 -0.78
away_team_std_Swing                                                  2.31
maps_played                                                             3
home_maps_won                                                           2
away_maps_won                                                           1
home_maps_picked                                                        1
map_avg_score_diff                                               2.666667
home_map_winrate                                                 0.666667
maps_json               [{"map_name": "Anubis", "played": true, "home_...
source_url              https://www.hltv.org/matches/2381644/natus-vin...
Name: 0, dtype: object

============================================================
4️⃣ TEAMS EXTRACTION
============================================================
✅ Teams extracted:
  Home: Natus Vincere (ID: 4608)
  Away: MIBR (ID: 9215)

============================================================
6️⃣ TEAM HISTORIES SCRAPING
============================================================

📈 Scraping history: Natus Vincere (ID: 4608)
🔍 Összesen 93 results-sublist betöltve
✅ 61 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
39,4608,2380130,March 28th 2025,Spirit,loss,0,2,bo3,https://www.hltv.org/matches/2380130/spirit-vs...,March 28 2025,2025-03-28
40,4608,2380128,March 24th 2025,Eternal Fire,loss,0,2,bo3,https://www.hltv.org/matches/2380128/eternal-f...,March 24 2025,2025-03-24
41,4608,2380119,March 23rd 2025,The MongolZ,win,2,1,bo3,https://www.hltv.org/matches/2380119/the-mongo...,March 23 2025,2025-03-23

📈 Scraping history: MIBR (ID: 9215)
🔍 Összesen 80 results-sublist betöltve
✅ 61 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
39,9215,2380061,March 9th 2025,FURIA,loss,1,2,bo3,https://www.hltv.org/matches/2380061/furia-vs-...,March 9 2025,2025-03-09
40,9215,2380048,March 8th 2025,Eternal Fire,loss,0,2,bo3,https://www.hltv.org/matches/2380048/eternal-f...,March 8 2025,2025-03-08
41,9215,2380040,March 7th 2025,Vitality,loss,1,2,bo3,https://www.hltv.org/matches/2380040/vitality-...,March 7 2025,2025-03-07

============================================================
7️⃣ HISTORICAL H2H SCRAPING
============================================================

🔍 Natus Vincere last 3 matches H2H scraping:
  [1/3] Scraping: 2025-03-28 vs Spirit
https://www.hltv.org/matches/2380130/spirit-vs-natus-vincere-blast-open-lisbon-2025
  [2/3] Scraping: 2025-03-24 vs Eternal Fire
https://www.hltv.org/matches/2380128/eternal-fire-vs-natus-vincere-blast-open-lisbon-2025

⚠️ Timeout (próbálkozás 1/3)
⚠️ Timeout (próbálkozás 2/3)
⚠️ Timeout (próbálkozás 3/3)
❌ Végleg timeout: _scrape

    ⚠️ H2H scraping hiba: ❌ H2H scraping sikertelen!
  [3/3] Scraping: 2025-03-23 vs The MongolZ
https://www.hltv.org/matches/2380119/the-mongolz-vs-natus-vincere-blast-open-lisbon-2025

🔍 MIBR last 3 matches H2H scraping:
  [1/3] Scraping: 2025-03-09 vs FURIA
https://www.hltv.org/matches/2380061/furia-vs-mibr-esl-pro-league-season-21

⚠️ Timeout (próbálkozás 1/3)

  [2/3] Scraping: 2025-03-08 vs Eternal Fire
https://www.hltv.org/matches/2380048/eternal-fire-vs-mibr-esl-pro-league-season-21
  [3/3] Scraping: 2025-03-07 vs Vitality
https://www.hltv.org/matches/2380040/vitality-vs-mibr-esl-pro-league-season-21

📊 Historical H2H stats összegzés:

{'avg_h2h_winrate': 0.37037037037037035,
 'avg_rating': 0.9590000000000001,
 'avg_rating_std': 0.12254999999999999,
 'avg_adr': 67.25,
 'avg_adr_std': 7.84,
 'avg_swing': -1.0150000000000001,
 'avg_swing_std': 1.99,
 'avg_maps_total': 2.5,
 'avg_map_winrate': 0.4,
 'avg_map_pickrate': 0.6,
 'avg_map_score_diff': -3.75,
 'avg_rank_diff': 0.5,
 'std_rank_diff': 2.5,
 'avg_point_diff': -153.0,
 'std_point_diff': 223.0,
 'weak_opp_rank_diff': 3,
 'strong_opp_rank_diff': -2,
 'weak_opp_point_diff': 70,
 'strong_opp_point_diff': -376,
 'n_matches_scraped': 2}

{'avg_h2h_winrate': 0.3333333333333333,
 'avg_rating': 0.9146666666666666,
 'avg_rating_std': 0.15326666666666666,
 'avg_adr': 67.82000000000001,
 'avg_adr_std': 11.443333333333333,
 'avg_swing': -1.7166666666666668,
 'avg_swing_std': 2.223333333333333,
 'avg_maps_total': 2.6666666666666665,
 'avg_map_winrate': 0.25,
 'avg_map_pickrate': 0.625,
 'avg_map_score_diff': -5.055555555555556,
 'avg_rank_diff': -12.0,
 'std_rank_diff': 5.715476066494082,
 'avg_point_diff': -350.0,
 'std_point_diff': 214.15881957089695,
 'weak_opp_rank_diff': -4,
 'strong_opp_rank_diff': -17,
 'weak_opp_point_diff': -56,
 'strong_opp_point_diff': -560,
 'n_matches_scraped': 3}

============================================================
8️⃣ ROLLING FEATURES SZÁMÍTÁSA
============================================================

📊 Natus Vincere rolling features:
  Last 3 winrate:    0.333
  Last 5 winrate:    0.400
  Last 3 avg score:  0.7 - 1.7
  Current streak:    -2
  home_avg_h2h_winrate: 0.37
  home_avg_rating: 0.96
  home_avg_rating_std: 0.12
  home_avg_adr: 67.25
  home_avg_adr_std: 7.84
  home_avg_swing: -1.02
  home_avg_swing_std: 1.99
  home_avg_maps_total: 2.50
  home_avg_map_winrate: 0.40
  home_avg_map_pickrate: 0.60
  home_avg_map_score_diff: -3.75
  home_avg_rank_diff: 0.50
  home_std_rank_diff: 2.50
  home_avg_point_diff: -153.00
  home_std_point_diff: 223.00
  home_weak_opp_rank_diff: 3.00
  home_strong_opp_rank_diff: -2.00
  home_weak_opp_point_diff: 70.00
  home_strong_opp_point_diff: -376.00
  home_n_matches_scraped: 2.00

📊 MIBR rolling features:
  Last 3 winrate:    N/A
  Last 5 winrate:    0.400
  Last 3 avg score:  0.7 - 2.0
  Current streak:    -3
  away_avg_h2h_winrate: 0.33
  away_avg_rating: 0.91
  away_avg_rating_std: 0.15
  away_avg_adr: 67.82
  away_avg_adr_std: 11.44
  away_avg_swing: -1.72
  away_avg_swing_std: 2.22
  away_avg_maps_total: 2.67
  away_avg_map_winrate: 0.25
  away_avg_map_pickrate: 0.62
  away_avg_map_score_diff: -5.06
  away_avg_rank_diff: -12.00
  away_std_rank_diff: 5.72
  away_avg_point_diff: -350.00
  away_std_point_diff: 214.16
  away_weak_opp_rank_diff: -4.00
  away_strong_opp_rank_diff: -17.00
  away_weak_opp_point_diff: -56.00
  away_strong_opp_point_diff: -560.00
  away_n_matches_scraped: 3.00

📊 Difference features:
  Diff last 3 WR:    +0.333

============================================================
9️⃣ RANKINGS ÉS EGYÉB FEATURE-ÖK
============================================================
  Home rank: #5 (change: +0)
  Away rank: #20 (change: +1)
✅ Feature-ök összegyűjtve!

,Date,home_team,away_team,home_odds,away_odds,event_id,home_team_mapped,away_team_mapped
199,2025-04-21,NaVi,MIBR,1.16,4.84,8036,Natus Vincere,MIBR

📊 DataFrame nézet:

✅ Új sor mentve. (113)

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,2381753,8036,2025-04-22 00:00:00,3DMAX,BIG,https://www.hltv.org/matches/2381753/3dmax-vs-...,NaN,NaN,NaN,NaN,...,0.6000,5,3,2,0,1,1.52,2.45,0.657895,0.408163
109,2381756,8036,2025-04-22 00:00:00,FaZe,The MongolZ,https://www.hltv.org/matches/2381756/faze-vs-t...,0.666667,0.8,1.666667,0.666667,...,NaN,0,3,0,2,0,1.94,1.82,0.515464,0.549451
110,2381755,8036,2025-04-22 00:00:00,GamerLegion,MOUZ,https://www.hltv.org/matches/2381755/gamerlegi...,0.666667,0.4,1.666667,0.666667,...,1.0000,2,3,0,2,0,3.63,1.26,0.275482,0.793651
111,2381754,8036,2025-04-22 00:00:00,paiN,Complexity,https://www.hltv.org/matches/2381754/pain-vs-c...,0.000000,0.0,0.333333,2.000000,...,NaN,0,3,0,2,0,4.61,1.18,0.216920,0.847458
112,2381644,8036,2025-04-21 00:00:00,Natus Vincere,MIBR,https://www.hltv.org/matches/2381644/natus-vin...,0.333333,0.4,0.666667,1.666667,...,0.0000,1,3,2,1,1,1.16,4.84,0.862069,0.206612

🎯 Kiválasztott meccs (index=22):
  Match ID:   2381643
  Date:       2025-04-21 00:00:00
  Teams:      Falcons vs SAW
  Score:      2 - 0
  URL:        https://www.hltv.org/matches/2381643/falcons-vs-saw-iem-melbourne-2025


============================================================
3️⃣ MATCH H2H SCRAPING
============================================================
🔍 Scraping: https://www.hltv.org/matches/2381643/falcons-vs-saw-iem-melbourne-2025
✅ H2H data:

match_id                                                          2381643
home_team                                                         Falcons
home_team_id                                                        11283
away_team                                                             SAW
away_team_id                                                        10567
wins_home                                                               0
wins_away                                                               0
overtimes                                                               0
total_non_overtime                                                      0
home_win_rate                                                        None
home_team_avg_rating                                                1.156
home_team_std_rating                                               0.1473
home_team_avg_ADR                                                   70.04
home_team_std_ADR                                                    8.43
home_team_avg_Swing                                                  2.18
home_team_std_Swing                                                  1.46
away_team_avg_rating                                                0.854
away_team_std_rating                                               0.1086
away_team_avg_ADR                                                   65.26
away_team_std_ADR                                                    3.65
away_team_avg_Swing                                                 -2.18
away_team_std_Swing                                                  1.98
maps_played                                                             2
home_maps_won                                                           2
away_maps_won                                                           0
home_maps_picked                                                        1
map_avg_score_diff                                                    4.5
home_map_winrate                                                      1.0
maps_json               [{"map_name": "Nuke", "played": true, "home_wi...
source_url              https://www.hltv.org/matches/2381643/falcons-v...
Name: 0, dtype: object

============================================================
4️⃣ TEAMS EXTRACTION
============================================================
✅ Teams extracted:
  Home: Falcons (ID: 11283)
  Away: SAW (ID: 10567)

============================================================
6️⃣ TEAM HISTORIES SCRAPING
============================================================

📈 Scraping history: Falcons (ID: 11283)
🔍 Összesen 91 results-sublist betöltve
✅ 63 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
37,11283,2381332,April 13th 2025,G2,win,3,0,bo5,https://www.hltv.org/matches/2381332/falcons-v...,April 13 2025,2025-04-13
38,11283,2381329,April 12th 2025,FaZe,win,2,1,bo3,https://www.hltv.org/matches/2381329/falcons-v...,April 12 2025,2025-04-12
39,11283,2381325,April 11th 2025,GamerLegion,win,2,1,bo3,https://www.hltv.org/matches/2381325/gamerlegi...,April 11 2025,2025-04-11

📈 Scraping history: SAW (ID: 10567)
🔍 Összesen 85 results-sublist betöltve
✅ 68 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
32,10567,2381600,April 16th 2025,ENCE,loss,0,2,bo3,https://www.hltv.org/matches/2381600/saw-vs-en...,April 16 2025,2025-04-16
33,10567,2381593,April 16th 2025,GamerLegion,win,2,1,bo3,https://www.hltv.org/matches/2381593/saw-vs-ga...,April 16 2025,2025-04-16
34,10567,2381588,April 15th 2025,9 Pandas,loss,11,13,anc,https://www.hltv.org/matches/2381588/9-pandas-...,April 15 2025,2025-04-15

============================================================
7️⃣ HISTORICAL H2H SCRAPING
============================================================

🔍 Falcons last 3 matches H2H scraping:
  [1/3] Scraping: 2025-04-13 vs G2
https://www.hltv.org/matches/2381332/falcons-vs-g2-pgl-bucharest-2025
  [2/3] Scraping: 2025-04-12 vs FaZe
https://www.hltv.org/matches/2381329/falcons-vs-faze-pgl-bucharest-2025
  [3/3] Scraping: 2025-04-11 vs GamerLegion
https://www.hltv.org/matches/2381325/gamerlegion-vs-falcons-pgl-bucharest-2025

🔍 SAW last 3 matches H2H scraping:
  [1/3] Scraping: 2025-04-16 vs ENCE
https://www.hltv.org/matches/2381600/saw-vs-ence-blasttv-austin-major-2025-europe-regional-qualifier
  [2/3] Scraping: 2025-04-16 vs GamerLegion
https://www.hltv.org/matches/2381593/saw-vs-gamerlegion-blasttv-austin-major-2025-europe-regional-qualifier
  [3/3] Scraping: 2025-04-15 vs 9 Pandas
https://www.hltv.org/matches/2381588/9-pandas-vs-saw-blasttv-austin-major-2025-europe-regional-qualifier

⚠️ Timeout (próbálkozás 1/3)

📊 Historical H2H stats összegzés:

{'avg_h2h_winrate': 0.5,
 'avg_rating': 1.094,
 'avg_rating_std': 0.11823333333333334,
 'avg_adr': 75.56,
 'avg_adr_std': 6.096666666666667,
 'avg_swing': 1.3,
 'avg_swing_std': 1.7666666666666666,
 'avg_maps_total': 3.0,
 'avg_map_winrate': 0.7777777777777778,
 'avg_map_pickrate': 0.4444444444444444,
 'avg_map_score_diff': 3.888888888888889,
 'avg_rank_diff': 0.3333333333333333,
 'std_rank_diff': 3.39934634239519,
 'avg_point_diff': -91.33333333333333,
 'std_point_diff': 132.68592824996762,
 'weak_opp_rank_diff': 5,
 'strong_opp_rank_diff': -3,
 'weak_opp_point_diff': 72,
 'strong_opp_point_diff': -253,
 'n_matches_scraped': 3}

{'avg_h2h_winrate': 0.375,
 'avg_rating': 0.9806666666666667,
 'avg_rating_std': 0.20753333333333335,
 'avg_adr': 72.01333333333334,
 'avg_adr_std': 12.186666666666667,
 'avg_swing': -0.4633333333333334,
 'avg_swing_std': 2.893333333333333,
 'avg_maps_total': 2.0,
 'avg_map_winrate': 0.3333333333333333,
 'avg_map_pickrate': 0.5,
 'avg_map_score_diff': -1.5,
 'avg_rank_diff': 13.0,
 'std_rank_diff': 13.589211407093005,
 'avg_point_diff': 27.666666666666668,
 'std_point_diff': 78.25741001478532,
 'weak_opp_rank_diff': 25,
 'strong_opp_rank_diff': -6,
 'weak_opp_point_diff': 84,
 'strong_opp_point_diff': -83,
 'n_matches_scraped': 3}

============================================================
8️⃣ ROLLING FEATURES SZÁMÍTÁSA
============================================================

📊 Falcons rolling features:
  Last 3 winrate:    1.000
  Last 5 winrate:    1.000
  Last 3 avg score:  2.3 - 0.7
  Current streak:    +6
  home_avg_h2h_winrate: 0.50
  home_avg_rating: 1.09
  home_avg_rating_std: 0.12
  home_avg_adr: 75.56
  home_avg_adr_std: 6.10
  home_avg_swing: 1.30
  home_avg_swing_std: 1.77
  home_avg_maps_total: 3.00
  home_avg_map_winrate: 0.78
  home_avg_map_pickrate: 0.44
  home_avg_map_score_diff: 3.89
  home_avg_rank_diff: 0.33
  home_std_rank_diff: 3.40
  home_avg_point_diff: -91.33
  home_std_point_diff: 132.69
  home_weak_opp_rank_diff: 5.00
  home_strong_opp_rank_diff: -3.00
  home_weak_opp_point_diff: 72.00
  home_strong_opp_point_diff: -253.00
  home_n_matches_scraped: 3.00

📊 SAW rolling features:
  Last 3 winrate:    0.333
  Last 5 winrate:    0.400
  Last 3 avg score:  4.3 - 5.3
  Current streak:    -1
  away_avg_h2h_winrate: 0.38
  away_avg_rating: 0.98
  away_avg_rating_std: 0.21
  away_avg_adr: 72.01
  away_avg_adr_std: 12.19
  away_avg_swing: -0.46
  away_avg_swing_std: 2.89
  away_avg_maps_total: 2.00
  away_avg_map_winrate: 0.33
  away_avg_map_pickrate: 0.50
  away_avg_map_score_diff: -1.50
  away_avg_rank_diff: 13.00
  away_std_rank_diff: 13.59
  away_avg_point_diff: 27.67
  away_std_point_diff: 78.26
  away_weak_opp_rank_diff: 25.00
  away_strong_opp_rank_diff: -6.00
  away_weak_opp_point_diff: 84.00
  away_strong_opp_point_diff: -83.00
  away_n_matches_scraped: 3.00

📊 Difference features:
  Diff last 3 WR:    +0.667

============================================================
9️⃣ RANKINGS ÉS EGYÉB FEATURE-ÖK
============================================================
  Home rank: #9 (change: +0)
  Away rank: #18 (change: +1)
✅ Feature-ök összegyűjtve!

,Date,home_team,away_team,home_odds,away_odds,event_id,home_team_mapped,away_team_mapped
198,2025-04-21,FALCONS,sAw,1.14,4.98,8036,Falcons,SAW

📊 DataFrame nézet:

✅ Új sor mentve. (114)

C:\Users\Adam\AppData\Local\Temp\ipykernel_4684\1115427491.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, new_row], ignore_index=True)

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,2381756,8036,2025-04-22 00:00:00,FaZe,The MongolZ,https://www.hltv.org/matches/2381756/faze-vs-t...,0.666667,0.8,1.666667,0.666667,...,NaN,0,3,0,2,0,1.94,1.82,0.515464,0.549451
110,2381755,8036,2025-04-22 00:00:00,GamerLegion,MOUZ,https://www.hltv.org/matches/2381755/gamerlegi...,0.666667,0.4,1.666667,0.666667,...,1.0000,2,3,0,2,0,3.63,1.26,0.275482,0.793651
111,2381754,8036,2025-04-22 00:00:00,paiN,Complexity,https://www.hltv.org/matches/2381754/pain-vs-c...,0.000000,0.0,0.333333,2.000000,...,NaN,0,3,0,2,0,4.61,1.18,0.216920,0.847458
112,2381644,8036,2025-04-21 00:00:00,Natus Vincere,MIBR,https://www.hltv.org/matches/2381644/natus-vin...,0.333333,0.4,0.666667,1.666667,...,0.0000,1,3,2,1,1,1.16,4.84,0.862069,0.206612
113,2381643,8036,2025-04-21 00:00:00,Falcons,SAW,https://www.hltv.org/matches/2381643/falcons-v...,1.000000,1.0,2.333333,0.666667,...,NaN,0,3,2,0,1,1.14,4.98,0.877193,0.200803

🎯 Kiválasztott meccs (index=23):
  Match ID:   2381641
  Date:       2025-04-21 00:00:00
  Teams:      Vitality vs FlyQuest
  Score:      2 - 0
  URL:        https://www.hltv.org/matches/2381641/vitality-vs-flyquest-iem-melbourne-2025


============================================================
3️⃣ MATCH H2H SCRAPING
============================================================
🔍 Scraping: https://www.hltv.org/matches/2381641/vitality-vs-flyquest-iem-melbourne-2025
✅ H2H data:

match_id                                                          2381641
home_team                                                        Vitality
home_team_id                                                         9565
away_team                                                        FlyQuest
away_team_id                                                        12774
wins_home                                                               0
wins_away                                                               0
overtimes                                                               0
total_non_overtime                                                      0
home_win_rate                                                        None
home_team_avg_rating                                                1.312
home_team_std_rating                                               0.3048
home_team_avg_ADR                                                   83.66
home_team_std_ADR                                                    7.33
home_team_avg_Swing                                                   3.0
home_team_std_Swing                                                  4.31
away_team_avg_rating                                                0.908
away_team_std_rating                                               0.2015
away_team_avg_ADR                                                   69.14
away_team_std_ADR                                                    5.53
away_team_avg_Swing                                                  -3.0
away_team_std_Swing                                                  3.69
maps_played                                                             2
home_maps_won                                                           2
away_maps_won                                                           0
home_maps_picked                                                        1
map_avg_score_diff                                                    8.0
home_map_winrate                                                      1.0
maps_json               [{"map_name": "Anubis", "played": true, "home_...
source_url              https://www.hltv.org/matches/2381641/vitality-...
Name: 0, dtype: object

============================================================
4️⃣ TEAMS EXTRACTION
============================================================
✅ Teams extracted:
  Home: Vitality (ID: 9565)
  Away: FlyQuest (ID: 12774)

============================================================
6️⃣ TEAM HISTORIES SCRAPING
============================================================

📈 Scraping history: Vitality (ID: 9565)
🔍 Összesen 96 results-sublist betöltve
✅ 55 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
45,9565,2380134,March 30th 2025,MOUZ,win,3,2,bo5,https://www.hltv.org/matches/2380134/mouz-vs-v...,March 30 2025,2025-03-30
46,9565,2380132,March 30th 2025,Spirit,win,2,1,bo3,https://www.hltv.org/matches/2380132/vitality-...,March 30 2025,2025-03-30
47,9565,2380126,March 24th 2025,MOUZ,win,2,0,bo3,https://www.hltv.org/matches/2380126/mouz-vs-v...,March 24 2025,2025-03-24

📈 Scraping history: FlyQuest (ID: 12774)
🔍 Összesen 80 results-sublist betöltve
✅ 71 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
29,12774,2381630,April 17th 2025,SemperFi,win,2,0,bo3,https://www.hltv.org/matches/2381630/flyquest-...,April 17 2025,2025-04-17
30,12774,2381627,April 16th 2025,SemperFi,win,2,0,bo3,https://www.hltv.org/matches/2381627/semperfi-...,April 16 2025,2025-04-16
31,12774,2381626,April 15th 2025,Rooster,win,2,0,bo3,https://www.hltv.org/matches/2381626/rooster-v...,April 15 2025,2025-04-15

============================================================
7️⃣ HISTORICAL H2H SCRAPING
============================================================

🔍 Vitality last 3 matches H2H scraping:
  [1/3] Scraping: 2025-03-30 vs MOUZ
https://www.hltv.org/matches/2380134/mouz-vs-vitality-blast-open-lisbon-2025
  [2/3] Scraping: 2025-03-30 vs Spirit
https://www.hltv.org/matches/2380132/vitality-vs-spirit-blast-open-lisbon-2025
  [3/3] Scraping: 2025-03-24 vs MOUZ
https://www.hltv.org/matches/2380126/mouz-vs-vitality-blast-open-lisbon-2025

🔍 FlyQuest last 3 matches H2H scraping:
  [1/3] Scraping: 2025-04-17 vs SemperFi
https://www.hltv.org/matches/2381630/flyquest-vs-semperfi-blasttv-austin-major-2025-oceania-sea-regional-qualifier
  [2/3] Scraping: 2025-04-16 vs SemperFi
https://www.hltv.org/matches/2381627/semperfi-vs-flyquest-blasttv-austin-major-2025-oceania-sea-regional-qualifier
  [3/3] Scraping: 2025-04-15 vs Rooster
https://www.hltv.org/matches/2381626/rooster-vs-flyquest-blasttv-austin-major-2025-oceania-sea-regional-qualifier

❌ Hiba a H2H scraperben: Message:

    ⚠️ H2H scraping hiba: ❌ H2H scraping sikertelen!

📊 Historical H2H stats összegzés:

{'avg_h2h_winrate': 0.6956521739130435,
 'avg_rating': 1.106,
 'avg_rating_std': 0.23139999999999997,
 'avg_adr': 70.11333333333334,
 'avg_adr_std': 12.836666666666668,
 'avg_swing': 1.2233333333333334,
 'avg_swing_std': 3.1366666666666667,
 'avg_maps_total': 3.3333333333333335,
 'avg_map_winrate': 0.7,
 'avg_map_pickrate': 0.5,
 'avg_map_score_diff': 2.288888888888889,
 'avg_rank_diff': 1.0,
 'std_rank_diff': 1.4142135623730951,
 'avg_point_diff': 189.33333333333334,
 'std_point_diff': 195.49310871628074,
 'weak_opp_rank_diff': 2,
 'strong_opp_rank_diff': -1,
 'weak_opp_point_diff': 335,
 'strong_opp_point_diff': -87,
 'n_matches_scraped': 3}

{'avg_h2h_winrate': 1.0,
 'avg_rating': 1.272,
 'avg_rating_std': 0.12495,
 'avg_adr': 85.21000000000001,
 'avg_adr_std': 9.08,
 'avg_swing': 2.29,
 'avg_swing_std': 1.99,
 'avg_maps_total': 2.0,
 'avg_map_winrate': 1.0,
 'avg_map_pickrate': 0.5,
 'avg_map_score_diff': 6.25,
 'avg_rank_diff': 52.0,
 'std_rank_diff': 0.0,
 'avg_point_diff': 35.0,
 'std_point_diff': 0.0,
 'weak_opp_rank_diff': 52,
 'strong_opp_rank_diff': 52,
 'weak_opp_point_diff': 35,
 'strong_opp_point_diff': 35,
 'n_matches_scraped': 2}

============================================================
8️⃣ ROLLING FEATURES SZÁMÍTÁSA
============================================================

📊 Vitality rolling features:
  Last 3 winrate:    1.000
  Last 5 winrate:    1.000
  Last 3 avg score:  2.3 - 1.0
  Current streak:    +16
  home_avg_h2h_winrate: 0.70
  home_avg_rating: 1.11
  home_avg_rating_std: 0.23
  home_avg_adr: 70.11
  home_avg_adr_std: 12.84
  home_avg_swing: 1.22
  home_avg_swing_std: 3.14
  home_avg_maps_total: 3.33
  home_avg_map_winrate: 0.70
  home_avg_map_pickrate: 0.50
  home_avg_map_score_diff: 2.29
  home_avg_rank_diff: 1.00
  home_std_rank_diff: 1.41
  home_avg_point_diff: 189.33
  home_std_point_diff: 195.49
  home_weak_opp_rank_diff: 2.00
  home_strong_opp_rank_diff: -1.00
  home_weak_opp_point_diff: 335.00
  home_strong_opp_point_diff: -87.00
  home_n_matches_scraped: 3.00

📊 FlyQuest rolling features:
  Last 3 winrate:    1.000
  Last 5 winrate:    0.600
  Last 3 avg score:  2.0 - 0.0
  Current streak:    +3
  away_avg_h2h_winrate: 1.00
  away_avg_rating: 1.27
  away_avg_rating_std: 0.12
  away_avg_adr: 85.21
  away_avg_adr_std: 9.08
  away_avg_swing: 2.29
  away_avg_swing_std: 1.99
  away_avg_maps_total: 2.00
  away_avg_map_winrate: 1.00
  away_avg_map_pickrate: 0.50
  away_avg_map_score_diff: 6.25
  away_avg_rank_diff: 52.00
  away_std_rank_diff: 0.00
  away_avg_point_diff: 35.00
  away_std_point_diff: 0.00
  away_weak_opp_rank_diff: 52.00
  away_strong_opp_rank_diff: 52.00
  away_weak_opp_point_diff: 35.00
  away_strong_opp_point_diff: 35.00
  away_n_matches_scraped: 2.00

📊 Difference features:
  Diff last 3 WR:    +0.000

============================================================
9️⃣ RANKINGS ÉS EGYÉB FEATURE-ÖK
============================================================
  Home rank: #1 (change: +0)
  Away rank: #26 (change: +0)
✅ Feature-ök összegyűjtve!

,Date,home_team,away_team,home_odds,away_odds,event_id,home_team_mapped,away_team_mapped
200,2025-04-21,Team Vitality,FlyQuest,1.03,10.0,8036,Vitality,FlyQuest

📊 DataFrame nézet:

✅ Új sor mentve. (115)

C:\Users\Adam\AppData\Local\Temp\ipykernel_4684\1115427491.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, new_row], ignore_index=True)

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,2381755,8036,2025-04-22 00:00:00,GamerLegion,MOUZ,https://www.hltv.org/matches/2381755/gamerlegi...,0.666667,0.4,1.666667,0.666667,...,1.0000,2,3,0,2,0,3.63,1.26,0.275482,0.793651
111,2381754,8036,2025-04-22 00:00:00,paiN,Complexity,https://www.hltv.org/matches/2381754/pain-vs-c...,0.000000,0.0,0.333333,2.000000,...,NaN,0,3,0,2,0,4.61,1.18,0.216920,0.847458
112,2381644,8036,2025-04-21 00:00:00,Natus Vincere,MIBR,https://www.hltv.org/matches/2381644/natus-vin...,0.333333,0.4,0.666667,1.666667,...,0.0000,1,3,2,1,1,1.16,4.84,0.862069,0.206612
113,2381643,8036,2025-04-21 00:00:00,Falcons,SAW,https://www.hltv.org/matches/2381643/falcons-v...,1.000000,1.0,2.333333,0.666667,...,NaN,0,3,2,0,1,1.14,4.98,0.877193,0.200803
114,2381641,8036,2025-04-21 00:00:00,Vitality,FlyQuest,https://www.hltv.org/matches/2381641/vitality-...,1.000000,1.0,2.333333,1.000000,...,NaN,0,3,2,0,1,1.03,10.00,0.970874,0.100000

🎯 Kiválasztott meccs (index=24):
  Match ID:   2381642
  Date:       2025-04-21 00:00:00
  Teams:      Liquid vs Virtus.pro
  Score:      2 - 1
  URL:        https://www.hltv.org/matches/2381642/liquid-vs-virtuspro-iem-melbourne-2025


============================================================
3️⃣ MATCH H2H SCRAPING
============================================================
🔍 Scraping: https://www.hltv.org/matches/2381642/liquid-vs-virtuspro-iem-melbourne-2025
✅ H2H data:

match_id                                                          2381642
home_team                                                          Liquid
home_team_id                                                         5973
away_team                                                      Virtus.pro
away_team_id                                                         5378
wins_home                                                               4
wins_away                                                               2
overtimes                                                               2
total_non_overtime                                                      6
home_win_rate                                                      0.6667
home_team_avg_rating                                                1.018
home_team_std_rating                                               0.0431
home_team_avg_ADR                                                    75.5
home_team_std_ADR                                                    8.17
home_team_avg_Swing                                                 -0.09
home_team_std_Swing                                                  0.85
away_team_avg_rating                                                1.026
away_team_std_rating                                               0.0582
away_team_avg_ADR                                                   70.92
away_team_std_ADR                                                   10.22
away_team_avg_Swing                                                  0.04
away_team_std_Swing                                                   1.3
maps_played                                                             3
home_maps_won                                                           2
away_maps_won                                                           1
home_maps_picked                                                        1
map_avg_score_diff                                                    1.0
home_map_winrate                                                 0.666667
maps_json               [{"map_name": "Dust2", "played": true, "home_w...
source_url              https://www.hltv.org/matches/2381642/liquid-vs...
Name: 0, dtype: object

============================================================
4️⃣ TEAMS EXTRACTION
============================================================
✅ Teams extracted:
  Home: Liquid (ID: 5973)
  Away: Virtus.pro (ID: 5378)

============================================================
6️⃣ TEAM HISTORIES SCRAPING
============================================================

📈 Scraping history: Liquid (ID: 5973)
🔍 Összesen 87 results-sublist betöltve
❌ Hiba a history scraping közben: expected string or bytes-like object, got 'NoneType'

📈 Scraping history: Virtus.pro (ID: 5378)
🔍 Összesen 91 results-sublist betöltve
✅ 65 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
35,5378,2381328,April 11th 2025,G2,loss,0,2,bo3,https://www.hltv.org/matches/2381328/g2-vs-vir...,April 11 2025,2025-04-11
36,5378,2381322,April 10th 2025,Astralis,win,2,0,bo3,https://www.hltv.org/matches/2381322/astralis-...,April 10 2025,2025-04-10
37,5378,2381316,April 9th 2025,GamerLegion,loss,0,2,bo3,https://www.hltv.org/matches/2381316/gamerlegi...,April 9 2025,2025-04-09

============================================================
7️⃣ HISTORICAL H2H SCRAPING
============================================================

🔍 Liquid last 3 matches H2H scraping:
  ⚠️ Nincs history, skip

🔍 Virtus.pro last 3 matches H2H scraping:
  [1/3] Scraping: 2025-04-11 vs G2
https://www.hltv.org/matches/2381328/g2-vs-virtuspro-pgl-bucharest-2025
  [2/3] Scraping: 2025-04-10 vs Astralis
https://www.hltv.org/matches/2381322/astralis-vs-virtuspro-pgl-bucharest-2025
  [3/3] Scraping: 2025-04-09 vs GamerLegion
https://www.hltv.org/matches/2381316/gamerlegion-vs-virtuspro-pgl-bucharest-2025

📊 Historical H2H stats összegzés:

{}

{'avg_h2h_winrate': 0.75,
 'avg_rating': 0.9686666666666666,
 'avg_rating_std': 0.2155,
 'avg_adr': 66.74666666666667,
 'avg_adr_std': 12.246666666666668,
 'avg_swing': -0.6533333333333334,
 'avg_swing_std': 3.14,
 'avg_maps_total': 2.0,
 'avg_map_winrate': 0.3333333333333333,
 'avg_map_pickrate': 0.5,
 'avg_map_score_diff': -1.1666666666666667,
 'avg_rank_diff': 1.0,
 'std_rank_diff': 3.559026084010437,
 'avg_point_diff': -59.0,
 'std_point_diff': 152.73724714903915,
 'weak_opp_rank_diff': 4,
 'strong_opp_rank_diff': -4,
 'weak_opp_point_diff': 50,
 'strong_opp_point_diff': -275,
 'n_matches_scraped': 3}

============================================================
8️⃣ ROLLING FEATURES SZÁMÍTÁSA
============================================================

📊 Liquid rolling features:
  ⚠️ Nincs history adat

📊 Virtus.pro rolling features:
  Last 3 winrate:    0.333
  Last 5 winrate:    0.600
  Last 3 avg score:  0.7 - 1.3
  Current streak:    -1
  away_avg_h2h_winrate: 0.75
  away_avg_rating: 0.97
  away_avg_rating_std: 0.22
  away_avg_adr: 66.75
  away_avg_adr_std: 12.25
  away_avg_swing: -0.65
  away_avg_swing_std: 3.14
  away_avg_maps_total: 2.00
  away_avg_map_winrate: 0.33
  away_avg_map_pickrate: 0.50
  away_avg_map_score_diff: -1.17
  away_avg_rank_diff: 1.00
  away_std_rank_diff: 3.56
  away_avg_point_diff: -59.00
  away_std_point_diff: 152.74
  away_weak_opp_rank_diff: 4.00
  away_strong_opp_rank_diff: -4.00
  away_weak_opp_point_diff: 50.00
  away_strong_opp_point_diff: -275.00
  away_n_matches_scraped: 3.00

============================================================
9️⃣ RANKINGS ÉS EGYÉB FEATURE-ÖK
============================================================
  Home rank: #13 (change: +2)
  Away rank: #10 (change: +0)
✅ Feature-ök összegyűjtve!

,Date,home_team,away_team,home_odds,away_odds,event_id,home_team_mapped,away_team_mapped
201,2025-04-21,Team Liquid,Virtus.pro,1.73,2.05,8036,Liquid,Virtus.pro

📊 DataFrame nézet:

✅ Új sor mentve. (116)

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,2381754,8036,2025-04-22 00:00:00,paiN,Complexity,https://www.hltv.org/matches/2381754/pain-vs-c...,0.000000,0.0,0.333333,2.000000,...,NaN,0,3,0,2,0,4.61,1.18,0.216920,0.847458
112,2381644,8036,2025-04-21 00:00:00,Natus Vincere,MIBR,https://www.hltv.org/matches/2381644/natus-vin...,0.333333,0.4,0.666667,1.666667,...,0.0000,1,3,2,1,1,1.16,4.84,0.862069,0.206612
113,2381643,8036,2025-04-21 00:00:00,Falcons,SAW,https://www.hltv.org/matches/2381643/falcons-v...,1.000000,1.0,2.333333,0.666667,...,NaN,0,3,2,0,1,1.14,4.98,0.877193,0.200803
114,2381641,8036,2025-04-21 00:00:00,Vitality,FlyQuest,https://www.hltv.org/matches/2381641/vitality-...,1.000000,1.0,2.333333,1.000000,...,NaN,0,3,2,0,1,1.03,10.00,0.970874,0.100000
115,2381642,8036,2025-04-21 00:00:00,Liquid,Virtus.pro,https://www.hltv.org/matches/2381642/liquid-vs...,NaN,NaN,NaN,NaN,...,0.6667,6,3,2,1,1,1.73,2.05,0.578035,0.487805

🎯 Kiválasztott meccs (index=25):
  Match ID:   2381637
  Date:       2025-04-21 00:00:00
  Teams:      MOUZ vs BIG
  Score:      2 - 1
  URL:        https://www.hltv.org/matches/2381637/mouz-vs-big-iem-melbourne-2025


============================================================
3️⃣ MATCH H2H SCRAPING
============================================================
🔍 Scraping: https://www.hltv.org/matches/2381637/mouz-vs-big-iem-melbourne-2025
✅ H2H data:

match_id                                                          2381637
home_team                                                            MOUZ
home_team_id                                                         4494
away_team                                                             BIG
away_team_id                                                         7532
wins_home                                                               2
wins_away                                                               0
overtimes                                                               1
total_non_overtime                                                      2
home_win_rate                                                         1.0
home_team_avg_rating                                                1.076
home_team_std_rating                                               0.0799
home_team_avg_ADR                                                    74.8
home_team_std_ADR                                                    6.02
home_team_avg_Swing                                                 -0.05
home_team_std_Swing                                                  1.06
away_team_avg_rating                                                 0.97
away_team_std_rating                                               0.0616
away_team_avg_ADR                                                   66.56
away_team_std_ADR                                                    7.29
away_team_avg_Swing                                                  0.03
away_team_std_Swing                                                  1.13
maps_played                                                             3
home_maps_won                                                           2
away_maps_won                                                           1
home_maps_picked                                                        1
map_avg_score_diff                                               0.666667
home_map_winrate                                                 0.666667
maps_json               [{"map_name": "Inferno", "played": true, "home...
source_url              https://www.hltv.org/matches/2381637/mouz-vs-b...
Name: 0, dtype: object

============================================================
4️⃣ TEAMS EXTRACTION
============================================================
✅ Teams extracted:
  Home: MOUZ (ID: 4494)
  Away: BIG (ID: 7532)

============================================================
6️⃣ TEAM HISTORIES SCRAPING
============================================================

📈 Scraping history: MOUZ (ID: 4494)
🔍 Összesen 94 results-sublist betöltve
✅ 56 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
44,4494,2380134,March 30th 2025,Vitality,loss,2,3,bo5,https://www.hltv.org/matches/2380134/mouz-vs-v...,March 30 2025,2025-03-30
45,4494,2380133,March 29th 2025,Eternal Fire,win,2,0,bo3,https://www.hltv.org/matches/2380133/eternal-f...,March 29 2025,2025-03-29
46,4494,2380131,March 28th 2025,G2,win,2,0,bo3,https://www.hltv.org/matches/2380131/mouz-vs-g...,March 28 2025,2025-03-28

📈 Scraping history: BIG (ID: 7532)
🔍 Összesen 81 results-sublist betöltve
✅ 39 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
61,7532,2381599,April 16th 2025,Astralis,loss,1,2,bo3,https://www.hltv.org/matches/2381599/astralis-...,April 16 2025,2025-04-16
62,7532,2381595,April 16th 2025,Nemiga,loss,0,2,bo3,https://www.hltv.org/matches/2381595/nemiga-vs...,April 16 2025,2025-04-16
63,7532,2381586,April 15th 2025,BC.Game,win,16,14,anc,https://www.hltv.org/matches/2381586/bcgame-vs...,April 15 2025,2025-04-15

============================================================
7️⃣ HISTORICAL H2H SCRAPING
============================================================

🔍 MOUZ last 3 matches H2H scraping:
  [1/3] Scraping: 2025-03-30 vs Vitality
https://www.hltv.org/matches/2380134/mouz-vs-vitality-blast-open-lisbon-2025
  [2/3] Scraping: 2025-03-29 vs Eternal Fire
https://www.hltv.org/matches/2380133/eternal-fire-vs-mouz-blast-open-lisbon-2025

⚠️ Timeout (próbálkozás 1/3)

  [3/3] Scraping: 2025-03-28 vs G2
https://www.hltv.org/matches/2380131/mouz-vs-g2-blast-open-lisbon-2025

🔍 BIG last 3 matches H2H scraping:
  [1/3] Scraping: 2025-04-16 vs Astralis
https://www.hltv.org/matches/2381599/astralis-vs-big-blasttv-austin-major-2025-europe-regional-qualifier
  [2/3] Scraping: 2025-04-16 vs Nemiga
https://www.hltv.org/matches/2381595/nemiga-vs-big-blasttv-austin-major-2025-europe-regional-qualifier
  [3/3] Scraping: 2025-04-15 vs BC.Game
https://www.hltv.org/matches/2381586/bcgame-vs-big-blasttv-austin-major-2025-europe-regional-qualifier

📊 Historical H2H stats összegzés:

{'avg_h2h_winrate': 0.42857142857142855,
 'avg_rating': 1.1286666666666667,
 'avg_rating_std': 0.1683,
 'avg_adr': 73.90666666666665,
 'avg_adr_std': 12.656666666666666,
 'avg_swing': 0.85,
 'avg_swing_std': 2.39,
 'avg_maps_total': 3.0,
 'avg_map_winrate': 0.6666666666666666,
 'avg_map_pickrate': 0.4444444444444444,
 'avg_map_score_diff': 1.9333333333333333,
 'avg_rank_diff': 0.6666666666666666,
 'std_rank_diff': 2.0548046676563256,
 'avg_point_diff': -81.0,
 'std_point_diff': 181.15923014482775,
 'weak_opp_rank_diff': 3,
 'strong_opp_rank_diff': -2,
 'weak_opp_point_diff': 75,
 'strong_opp_point_diff': -335,
 'n_matches_scraped': 3}

{'avg_h2h_winrate': 0.26666666666666666,
 'avg_rating': 1.02,
 'avg_rating_std': 0.1731,
 'avg_adr': 72.74000000000001,
 'avg_adr_std': 11.223333333333334,
 'avg_swing': -1.0166666666666666,
 'avg_swing_std': 2.51,
 'avg_maps_total': 2.0,
 'avg_map_winrate': 0.3333333333333333,
 'avg_map_pickrate': 0.6666666666666666,
 'avg_map_score_diff': -2.222222222222222,
 'avg_rank_diff': 1.0,
 'std_rank_diff': 8.831760866327848,
 'avg_point_diff': -23.666666666666668,
 'std_point_diff': 59.86837414046103,
 'weak_opp_rank_diff': 10,
 'strong_opp_rank_diff': -11,
 'weak_opp_point_diff': 25,
 'strong_opp_point_diff': -108,
 'n_matches_scraped': 3}

============================================================
8️⃣ ROLLING FEATURES SZÁMÍTÁSA
============================================================

📊 MOUZ rolling features:
  Last 3 winrate:    0.667
  Last 5 winrate:    0.600
  Last 3 avg score:  2.0 - 1.0
  Current streak:    -1
  home_avg_h2h_winrate: 0.43
  home_avg_rating: 1.13
  home_avg_rating_std: 0.17
  home_avg_adr: 73.91
  home_avg_adr_std: 12.66
  home_avg_swing: 0.85
  home_avg_swing_std: 2.39
  home_avg_maps_total: 3.00
  home_avg_map_winrate: 0.67
  home_avg_map_pickrate: 0.44
  home_avg_map_score_diff: 1.93
  home_avg_rank_diff: 0.67
  home_std_rank_diff: 2.05
  home_avg_point_diff: -81.00
  home_std_point_diff: 181.16
  home_weak_opp_rank_diff: 3.00
  home_strong_opp_rank_diff: -2.00
  home_weak_opp_point_diff: 75.00
  home_strong_opp_point_diff: -335.00
  home_n_matches_scraped: 3.00

📊 BIG rolling features:
  Last 3 winrate:    0.333
  Last 5 winrate:    0.400
  Last 3 avg score:  5.7 - 6.0
  Current streak:    -2
  away_avg_h2h_winrate: 0.27
  away_avg_rating: 1.02
  away_avg_rating_std: 0.17
  away_avg_adr: 72.74
  away_avg_adr_std: 11.22
  away_avg_swing: -1.02
  away_avg_swing_std: 2.51
  away_avg_maps_total: 2.00
  away_avg_map_winrate: 0.33
  away_avg_map_pickrate: 0.67
  away_avg_map_score_diff: -2.22
  away_avg_rank_diff: 1.00
  away_std_rank_diff: 8.83
  away_avg_point_diff: -23.67
  away_std_point_diff: 59.87
  away_weak_opp_rank_diff: 10.00
  away_strong_opp_rank_diff: -11.00
  away_weak_opp_point_diff: 25.00
  away_strong_opp_point_diff: -108.00
  away_n_matches_scraped: 3.00

📊 Difference features:
  Diff last 3 WR:    +0.333

============================================================
9️⃣ RANKINGS ÉS EGYÉB FEATURE-ÖK
============================================================
  Home rank: #3 (change: +0)
  Away rank: #25 (change: +3)
✅ Feature-ök összegyűjtve!

,Date,home_team,away_team,home_odds,away_odds,event_id,home_team_mapped,away_team_mapped
202,2025-04-21,MOUZ,BIG,1.07,6.95,8036,MOUZ,BIG

📊 DataFrame nézet:

✅ Új sor mentve. (117)

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,2381644,8036,2025-04-21 00:00:00,Natus Vincere,MIBR,https://www.hltv.org/matches/2381644/natus-vin...,0.333333,0.4,0.666667,1.666667,...,0.0000,1,3,2,1,1,1.16,4.84,0.862069,0.206612
113,2381643,8036,2025-04-21 00:00:00,Falcons,SAW,https://www.hltv.org/matches/2381643/falcons-v...,1.000000,1.0,2.333333,0.666667,...,NaN,0,3,2,0,1,1.14,4.98,0.877193,0.200803
114,2381641,8036,2025-04-21 00:00:00,Vitality,FlyQuest,https://www.hltv.org/matches/2381641/vitality-...,1.000000,1.0,2.333333,1.000000,...,NaN,0,3,2,0,1,1.03,10.00,0.970874,0.100000
115,2381642,8036,2025-04-21 00:00:00,Liquid,Virtus.pro,https://www.hltv.org/matches/2381642/liquid-vs...,NaN,NaN,NaN,NaN,...,0.6667,6,3,2,1,1,1.73,2.05,0.578035,0.487805
116,2381637,8036,2025-04-21 00:00:00,MOUZ,BIG,https://www.hltv.org/matches/2381637/mouz-vs-b...,0.666667,0.6,2.000000,1.000000,...,1.0000,2,3,2,1,1,1.07,6.95,0.934579,0.143885

🎯 Kiválasztott meccs (index=26):
  Match ID:   2381638
  Date:       2025-04-21 00:00:00
  Teams:      3DMAX vs GamerLegion
  Score:      0 - 2
  URL:        https://www.hltv.org/matches/2381638/3dmax-vs-gamerlegion-iem-melbourne-2025


============================================================
3️⃣ MATCH H2H SCRAPING
============================================================
🔍 Scraping: https://www.hltv.org/matches/2381638/3dmax-vs-gamerlegion-iem-melbourne-2025

⚠️ Timeout (próbálkozás 1/3)

✅ H2H data:

match_id                                                          2381638
home_team                                                           3DMAX
home_team_id                                                         4914
away_team                                                     GamerLegion
away_team_id                                                         9928
wins_home                                                               0
wins_away                                                               0
overtimes                                                               0
total_non_overtime                                                      0
home_win_rate                                                        None
home_team_avg_rating                                                0.844
home_team_std_rating                                               0.1553
home_team_avg_ADR                                                   65.62
home_team_std_ADR                                                    6.52
home_team_avg_Swing                                                 -2.95
home_team_std_Swing                                                  2.39
away_team_avg_rating                                                 1.31
away_team_std_rating                                               0.2333
away_team_avg_ADR                                                   79.98
away_team_std_ADR                                                   11.56
away_team_avg_Swing                                                  2.76
away_team_std_Swing                                                  2.67
maps_played                                                             2
home_maps_won                                                           0
away_maps_won                                                           2
home_maps_picked                                                        1
map_avg_score_diff                                                   -7.0
home_map_winrate                                                      0.0
maps_json               [{"map_name": "Ancient", "played": true, "home...
source_url              https://www.hltv.org/matches/2381638/3dmax-vs-...
Name: 0, dtype: object

============================================================
4️⃣ TEAMS EXTRACTION
============================================================
✅ Teams extracted:
  Home: 3DMAX (ID: 4914)
  Away: GamerLegion (ID: 9928)

============================================================
6️⃣ TEAM HISTORIES SCRAPING
============================================================

📈 Scraping history: 3DMAX (ID: 4914)
🔍 Összesen 92 results-sublist betöltve
❌ Hiba a history scraping közben: expected string or bytes-like object, got 'NoneType'

📈 Scraping history: GamerLegion (ID: 9928)
🔍 Összesen 87 results-sublist betöltve
✅ 61 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
39,9928,2381593,April 16th 2025,SAW,loss,1,2,bo3,https://www.hltv.org/matches/2381593/saw-vs-ga...,April 16 2025,2025-04-16
40,9928,2381584,April 15th 2025,500,win,2,0,bo3,https://www.hltv.org/matches/2381584/gamerlegi...,April 15 2025,2025-04-15
41,9928,2381583,April 14th 2025,fnatic,loss,8,13,anb,https://www.hltv.org/matches/2381583/gamerlegi...,April 14 2025,2025-04-14

============================================================
7️⃣ HISTORICAL H2H SCRAPING
============================================================

🔍 3DMAX last 3 matches H2H scraping:
  ⚠️ Nincs history, skip

🔍 GamerLegion last 3 matches H2H scraping:
  [1/3] Scraping: 2025-04-16 vs SAW
https://www.hltv.org/matches/2381593/saw-vs-gamerlegion-blasttv-austin-major-2025-europe-regional-qualifier
  [2/3] Scraping: 2025-04-15 vs 500
https://www.hltv.org/matches/2381584/gamerlegion-vs-500-blasttv-austin-major-2025-europe-regional-qualifier
  [3/3] Scraping: 2025-04-14 vs fnatic
https://www.hltv.org/matches/2381583/gamerlegion-vs-fnatic-blasttv-austin-major-2025-europe-regional-qualifier

📊 Historical H2H stats összegzés:

{}

{'avg_h2h_winrate': 0.8,
 'avg_rating': 1.186,
 'avg_rating_std': 0.24773333333333336,
 'avg_adr': 73.16666666666667,
 'avg_adr_std': 12.433333333333332,
 'avg_swing': 1.59,
 'avg_swing_std': 3.473333333333333,
 'avg_maps_total': 2.0,
 'avg_map_winrate': 0.5,
 'avg_map_pickrate': 0.5,
 'avg_map_score_diff': 2.0,
 'avg_rank_diff': 21.0,
 'std_rank_diff': 10.614455552060438,
 'avg_point_diff': 127.33333333333333,
 'std_point_diff': 34.120700787384514,
 'weak_opp_rank_diff': 29,
 'strong_opp_rank_diff': 6,
 'weak_opp_point_diff': 166,
 'strong_opp_point_diff': 83,
 'n_matches_scraped': 3}

============================================================
8️⃣ ROLLING FEATURES SZÁMÍTÁSA
============================================================

📊 3DMAX rolling features:
  ⚠️ Nincs history adat

📊 GamerLegion rolling features:
  Last 3 winrate:    0.333
  Last 5 winrate:    0.200
  Last 3 avg score:  3.7 - 5.0
  Current streak:    -1
  away_avg_h2h_winrate: 0.80
  away_avg_rating: 1.19
  away_avg_rating_std: 0.25
  away_avg_adr: 73.17
  away_avg_adr_std: 12.43
  away_avg_swing: 1.59
  away_avg_swing_std: 3.47
  away_avg_maps_total: 2.00
  away_avg_map_winrate: 0.50
  away_avg_map_pickrate: 0.50
  away_avg_map_score_diff: 2.00
  away_avg_rank_diff: 21.00
  away_std_rank_diff: 10.61
  away_avg_point_diff: 127.33
  away_std_point_diff: 34.12
  away_weak_opp_rank_diff: 29.00
  away_strong_opp_rank_diff: 6.00
  away_weak_opp_point_diff: 166.00
  away_strong_opp_point_diff: 83.00
  away_n_matches_scraped: 3.00

============================================================
9️⃣ RANKINGS ÉS EGYÉB FEATURE-ÖK
============================================================
  Home rank: #11 (change: -1)
  Away rank: #12 (change: -2)
✅ Feature-ök összegyűjtve!

,Date,home_team,away_team,home_odds,away_odds,event_id,home_team_mapped,away_team_mapped
203,2025-04-21,3DMAX,GamerLegion,1.63,2.22,8036,3DMAX,GamerLegion

📊 DataFrame nézet:

✅ Új sor mentve. (118)

C:\Users\Adam\AppData\Local\Temp\ipykernel_4684\1115427491.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, new_row], ignore_index=True)

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,2381643,8036,2025-04-21 00:00:00,Falcons,SAW,https://www.hltv.org/matches/2381643/falcons-v...,1.000000,1.0,2.333333,0.666667,...,NaN,0,3,2,0,1,1.14,4.98,0.877193,0.200803
114,2381641,8036,2025-04-21 00:00:00,Vitality,FlyQuest,https://www.hltv.org/matches/2381641/vitality-...,1.000000,1.0,2.333333,1.000000,...,NaN,0,3,2,0,1,1.03,10.00,0.970874,0.100000
115,2381642,8036,2025-04-21 00:00:00,Liquid,Virtus.pro,https://www.hltv.org/matches/2381642/liquid-vs...,NaN,NaN,NaN,NaN,...,0.6667,6,3,2,1,1,1.73,2.05,0.578035,0.487805
116,2381637,8036,2025-04-21 00:00:00,MOUZ,BIG,https://www.hltv.org/matches/2381637/mouz-vs-b...,0.666667,0.6,2.000000,1.000000,...,1.0000,2,3,2,1,1,1.07,6.95,0.934579,0.143885
117,2381638,8036,2025-04-21 00:00:00,3DMAX,GamerLegion,https://www.hltv.org/matches/2381638/3dmax-vs-...,NaN,NaN,NaN,NaN,...,NaN,0,3,0,2,0,1.63,2.22,0.613497,0.450450

🎯 Kiválasztott meccs (index=27):
  Match ID:   2381640
  Date:       2025-04-21 00:00:00
  Teams:      The MongolZ vs Complexity
  Score:      2 - 1
  URL:        https://www.hltv.org/matches/2381640/the-mongolz-vs-complexity-iem-melbourne-2025


============================================================
3️⃣ MATCH H2H SCRAPING
============================================================
🔍 Scraping: https://www.hltv.org/matches/2381640/the-mongolz-vs-complexity-iem-melbourne-2025
✅ H2H data:

match_id                                                          2381640
home_team                                                     The MongolZ
home_team_id                                                         6248
away_team                                                      Complexity
away_team_id                                                         5005
wins_home                                                               5
wins_away                                                               0
overtimes                                                               1
total_non_overtime                                                      5
home_win_rate                                                         1.0
home_team_avg_rating                                                1.048
home_team_std_rating                                               0.1433
home_team_avg_ADR                                                   74.14
home_team_std_ADR                                                    4.13
home_team_avg_Swing                                                  0.39
home_team_std_Swing                                                  2.16
away_team_avg_rating                                                1.006
away_team_std_rating                                               0.1315
away_team_avg_ADR                                                   74.64
away_team_std_ADR                                                    13.8
away_team_avg_Swing                                                  -0.5
away_team_std_Swing                                                  1.37
maps_played                                                             3
home_maps_won                                                           2
away_maps_won                                                           1
home_maps_picked                                                        1
map_avg_score_diff                                               1.333333
home_map_winrate                                                 0.666667
maps_json               [{"map_name": "Anubis", "played": true, "home_...
source_url              https://www.hltv.org/matches/2381640/the-mongo...
Name: 0, dtype: object

============================================================
4️⃣ TEAMS EXTRACTION
============================================================
✅ Teams extracted:
  Home: The MongolZ (ID: 6248)
  Away: Complexity (ID: 5005)

============================================================
6️⃣ TEAM HISTORIES SCRAPING
============================================================

📈 Scraping history: The MongolZ (ID: 6248)
🔍 Összesen 94 results-sublist betöltve
❌ Hiba a history scraping közben: expected string or bytes-like object, got 'NoneType'

📈 Scraping history: Complexity (ID: 5005)
❌ Hiba a history scraping közben: Message: timeout: Timed out receiving message from renderer: 14.849
  (Session info: chrome=141.0.7390.108)
Stacktrace:
	GetHandleVerifier [0x0x7ff7118ae9e5+80021]
	GetHandleVerifier [0x0x7ff7118aea40+80112]
	(No symbol) [0x0x7ff71163060f]
	(No symbol) [0x0x7ff71161d82f]
	(No symbol) [0x0x7ff71161d51d]
	(No symbol) [0x0x7ff71161b08c]
	(No symbol) [0x0x7ff71161bb0b]
	(No symbol) [0x0x7ff71162ab0e]
	(No symbol) [0x0x7ff711641161]
	(No symbol) [0x0x7ff7116483aa]
	(No symbol) [0x0x7ff71161c2be]
	(No symbol) [0x0x7ff711640e51]
	(No symbol) [0x0x7ff7116d99f6]
	(No symbol) [0x0x7ff7116b1003]
	(No symbol) [0x0x7ff7116795d1]
	(No symbol) [0x0x7ff71167a3f3]
	GetHandleVerifier [0x0x7ff711b6dd8d+2960445]
	GetHandleVerifier [0x0x7ff711b6804a+2936570]
	GetHandleVerifier [0x0x7ff711b88a87+3070263]
	GetHandleVerifier [0x0x7ff7118c84ce+185214]
	GetHandleVerifier [0x0x7ff7118cff1f+216527]
	GetHandleVerifier [0x0x7ff7118b7c24+117460]
	GetHandleVerifier [0x0x7ff7118b7ddf+117903]
	GetHandleVerifier [0x0x7ff71189dcb8+11112]
	BaseThreadInitThunk [0x0x7ffc5bd97374+20]
	RtlUserThreadStart [0x0x7ffc5d95cc91+33]


============================================================
7️⃣ HISTORICAL H2H SCRAPING
============================================================

🔍 The MongolZ last 3 matches H2H scraping:
  ⚠️ Nincs history, skip

🔍 Complexity last 3 matches H2H scraping:
  ⚠️ Nincs history, skip

📊 Historical H2H stats összegzés:

{}

{}

============================================================
8️⃣ ROLLING FEATURES SZÁMÍTÁSA
============================================================

📊 The MongolZ rolling features:
  ⚠️ Nincs history adat

📊 Complexity rolling features:
  ⚠️ Nincs history adat

============================================================
9️⃣ RANKINGS ÉS EGYÉB FEATURE-ÖK
============================================================
  Home rank: #7 (change: +0)
  Away rank: #15 (change: -6)
✅ Feature-ök összegyűjtve!

,Date,home_team,away_team,home_odds,away_odds,event_id,home_team_mapped,away_team_mapped
205,2025-04-21,The Mongolz,compLexity Gaming,1.41,2.76,8036,The MongolZ,Complexity

📊 DataFrame nézet:

✅ Új sor mentve. (119)

,match_id,event_id,date,team_home,team_away,match_url,home_last_3_winrate,home_last_5_winrate,home_last_3_avg_score_for,home_last_3_avg_score_against,...,H2H_winrate_team1,H2H_games,match_rounds,score_home,score_away,label_home_win,home_odds,away_odds,home_implied_odds,away_implied_odds
0,2380078,8292,2025-03-16 00:00:00,MOUZ,Vitality,https://www.hltv.org/matches/2380078/mouz-vs-v...,1.000000,0.8,2.000000,0.666667,...,0.3571,14,5,0,3,0,3.70,1.26,0.270270,0.793651
1,2380076,8292,2025-03-15 00:00:00,Vitality,The MongolZ,https://www.hltv.org/matches/2380076/vitality-...,1.000000,1.0,2.000000,0.000000,...,1.0000,7,3,2,1,1,1.27,3.66,0.787402,0.273224
2,2380077,8292,2025-03-15 00:00:00,Spirit,MOUZ,https://www.hltv.org/matches/2380077/spirit-vs...,1.000000,0.8,2.000000,0.333333,...,0.5333,15,3,1,2,0,1.37,2.96,0.729927,0.337838
3,2380073,8292,2025-03-14 00:00:00,Natus Vincere,The MongolZ,https://www.hltv.org/matches/2380073/natus-vin...,NaN,NaN,NaN,NaN,...,1.0000,3,3,0,2,0,1.47,2.65,0.680272,0.377358
4,2380072,8292,2025-03-14 00:00:00,Vitality,Liquid,https://www.hltv.org/matches/2380072/vitality-...,NaN,NaN,NaN,NaN,...,0.7500,8,3,2,0,1,1.20,4.35,0.833333,0.229885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,2381641,8036,2025-04-21 00:00:00,Vitality,FlyQuest,https://www.hltv.org/matches/2381641/vitality-...,1.000000,1.0,2.333333,1.000000,...,NaN,0,3,2,0,1,1.03,10.00,0.970874,0.100000
115,2381642,8036,2025-04-21 00:00:00,Liquid,Virtus.pro,https://www.hltv.org/matches/2381642/liquid-vs...,NaN,NaN,NaN,NaN,...,0.6667,6,3,2,1,1,1.73,2.05,0.578035,0.487805
116,2381637,8036,2025-04-21 00:00:00,MOUZ,BIG,https://www.hltv.org/matches/2381637/mouz-vs-b...,0.666667,0.6,2.000000,1.000000,...,1.0000,2,3,2,1,1,1.07,6.95,0.934579,0.143885
117,2381638,8036,2025-04-21 00:00:00,3DMAX,GamerLegion,https://www.hltv.org/matches/2381638/3dmax-vs-...,NaN,NaN,NaN,NaN,...,NaN,0,3,0,2,0,1.63,2.22,0.613497,0.450450
118,2381640,8036,2025-04-21 00:00:00,The MongolZ,Complexity,https://www.hltv.org/matches/2381640/the-mongo...,NaN,NaN,NaN,NaN,...,1.0000,5,3,2,1,1,1.41,2.76,0.709220,0.362319

🎯 Kiválasztott meccs (index=28):
  Match ID:   2381639
  Date:       2025-04-21 00:00:00
  Teams:      FaZe vs paiN
  Score:      2 - 0
  URL:        https://www.hltv.org/matches/2381639/faze-vs-pain-iem-melbourne-2025


============================================================
3️⃣ MATCH H2H SCRAPING
============================================================
🔍 Scraping: https://www.hltv.org/matches/2381639/faze-vs-pain-iem-melbourne-2025
✅ H2H data:

match_id                                                          2381639
home_team                                                            FaZe
home_team_id                                                         6667
away_team                                                            paiN
away_team_id                                                         4773
wins_home                                                               2
wins_away                                                               2
overtimes                                                               0
total_non_overtime                                                      4
home_win_rate                                                         0.5
home_team_avg_rating                                                1.072
home_team_std_rating                                               0.0813
home_team_avg_ADR                                                   70.92
home_team_std_ADR                                                    4.22
home_team_avg_Swing                                                  0.61
home_team_std_Swing                                                  1.24
away_team_avg_rating                                                0.966
away_team_std_rating                                               0.1876
away_team_avg_ADR                                                   63.86
away_team_std_ADR                                                   16.22
away_team_avg_Swing                                                  -0.9
away_team_std_Swing                                                  3.16
maps_played                                                             2
home_maps_won                                                           2
away_maps_won                                                           0
home_maps_picked                                                        1
map_avg_score_diff                                                    2.0
home_map_winrate                                                      1.0
maps_json               [{"map_name": "Anubis", "played": true, "home_...
source_url              https://www.hltv.org/matches/2381639/faze-vs-p...
Name: 0, dtype: object

============================================================
4️⃣ TEAMS EXTRACTION
============================================================
✅ Teams extracted:
  Home: FaZe (ID: 6667)
  Away: paiN (ID: 4773)

============================================================
6️⃣ TEAM HISTORIES SCRAPING
============================================================

📈 Scraping history: FaZe (ID: 6667)
🔍 Összesen 91 results-sublist betöltve
✅ 50 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
50,6667,2381331,April 13th 2025,Complexity,win,2,0,bo3,https://www.hltv.org/matches/2381331/faze-vs-c...,April 13 2025,2025-04-13
51,6667,2381329,April 12th 2025,Falcons,loss,1,2,bo3,https://www.hltv.org/matches/2381329/falcons-v...,April 12 2025,2025-04-12
52,6667,2381326,April 11th 2025,3DMAX,win,2,0,bo3,https://www.hltv.org/matches/2381326/3dmax-vs-...,April 11 2025,2025-04-11

📈 Scraping history: paiN (ID: 4773)
🔍 Összesen 82 results-sublist betöltve
✅ 64 meccs találva

📋 Megelőző 3 meccs:

,team_id,match_id,match_date,opponent_name,result,score_for,score_against,map_type,link,date_clean,date_parsed
36,4773,2381313,April 8th 2025,Falcons,loss,1,2,bo3,https://www.hltv.org/matches/2381313/falcons-v...,April 8 2025,2025-04-08
37,4773,2381307,April 7th 2025,FaZe,loss,0,2,bo3,https://www.hltv.org/matches/2381307/faze-vs-p...,April 7 2025,2025-04-07
38,4773,2381255,April 6th 2025,Aurora,loss,1,2,bo3,https://www.hltv.org/matches/2381255/aurora-vs...,April 6 2025,2025-04-06

============================================================
7️⃣ HISTORICAL H2H SCRAPING
============================================================

🔍 FaZe last 3 matches H2H scraping:
  [1/3] Scraping: 2025-04-13 vs Complexity
https://www.hltv.org/matches/2381331/faze-vs-complexity-pgl-bucharest-2025

⚠️ Timeout (próbálkozás 1/3)

  [2/3] Scraping: 2025-04-12 vs Falcons
https://www.hltv.org/matches/2381329/falcons-vs-faze-pgl-bucharest-2025
  [3/3] Scraping: 2025-04-11 vs 3DMAX
https://www.hltv.org/matches/2381326/3dmax-vs-faze-pgl-bucharest-2025

🔍 paiN last 3 matches H2H scraping:
  [1/3] Scraping: 2025-04-08 vs Falcons
https://www.hltv.org/matches/2381313/falcons-vs-pain-pgl-bucharest-2025
  [2/3] Scraping: 2025-04-07 vs FaZe
https://www.hltv.org/matches/2381307/faze-vs-pain-pgl-bucharest-2025
  [3/3] Scraping: 2025-04-06 vs Aurora
https://www.hltv.org/matches/2381255/aurora-vs-pain-pgl-bucharest-2025

📊 Historical H2H stats összegzés:

{'avg_h2h_winrate': 0.47368421052631576,
 'avg_rating': 1.172,
 'avg_rating_std': 0.24706666666666666,
 'avg_adr': 77.96666666666665,
 'avg_adr_std': 13.926666666666668,
 'avg_swing': 1.8,
 'avg_swing_std': 3.07,
 'avg_maps_total': 2.3333333333333335,
 'avg_map_winrate': 0.7142857142857143,
 'avg_map_pickrate': 0.5714285714285714,
 'avg_map_score_diff': 3.222222222222222,
 'avg_rank_diff': 6.0,
 'std_rank_diff': 5.0990195135927845,
 'avg_point_diff': 166.66666666666666,
 'std_point_diff': 66.4345960743012,
 'weak_opp_rank_diff': 13,
 'strong_opp_rank_diff': 1,
 'weak_opp_point_diff': 254,
 'strong_opp_point_diff': 93,
 'n_matches_scraped': 3}

{'avg_h2h_winrate': 0.4444444444444444,
 'avg_rating': 0.9540000000000001,
 'avg_rating_std': 0.19813333333333336,
 'avg_adr': 69.60000000000001,
 'avg_adr_std': 12.729999999999999,
 'avg_swing': -0.9266666666666667,
 'avg_swing_std': 2.6799999999999997,
 'avg_maps_total': 2.6666666666666665,
 'avg_map_winrate': 0.25,
 'avg_map_pickrate': 0.625,
 'avg_map_score_diff': -2.111111111111111,
 'avg_rank_diff': 3.0,
 'std_rank_diff': 14.854853303438128,
 'avg_point_diff': -62.333333333333336,
 'std_point_diff': 124.39006748486348,
 'weak_opp_rank_diff': 24,
 'strong_opp_rank_diff': -8,
 'weak_opp_point_diff': 105,
 'strong_opp_point_diff': -193,
 'n_matches_scraped': 3}

============================================================
8️⃣ ROLLING FEATURES SZÁMÍTÁSA
============================================================

📊 FaZe rolling features:
  Last 3 winrate:    0.667
  Last 5 winrate:    0.600
  Last 3 avg score:  1.7 - 0.7
  Current streak:    +1
  home_avg_h2h_winrate: 0.47
  home_avg_rating: 1.17
  home_avg_rating_std: 0.25
  home_avg_adr: 77.97
  home_avg_adr_std: 13.93
  home_avg_swing: 1.80
  home_avg_swing_std: 3.07
  home_avg_maps_total: 2.33
  home_avg_map_winrate: 0.71
  home_avg_map_pickrate: 0.57
  home_avg_map_score_diff: 3.22
  home_avg_rank_diff: 6.00
  home_std_rank_diff: 5.10
  home_avg_point_diff: 166.67
  home_std_point_diff: 66.43
  home_weak_opp_rank_diff: 13.00
  home_strong_opp_rank_diff: 1.00
  home_weak_opp_point_diff: 254.00
  home_strong_opp_point_diff: 93.00
  home_n_matches_scraped: 3.00

📊 paiN rolling features:
  Last 3 winrate:    N/A
  Last 5 winrate:    N/A
  Last 3 avg score:  0.7 - 2.0
  Current streak:    -5
  away_avg_h2h_winrate: 0.44
  away_avg_rating: 0.95
  away_avg_rating_std: 0.20
  away_avg_adr: 69.60
  away_avg_adr_std: 12.73
  away_avg_swing: -0.93
  away_avg_swing_std: 2.68
  away_avg_maps_total: 2.67
  away_avg_map_winrate: 0.25
  away_avg_map_pickrate: 0.62
  away_avg_map_score_diff: -2.11
  away_avg_rank_diff: 3.00
  away_std_rank_diff: 14.85
  away_avg_point_diff: -62.33
  away_std_point_diff: 124.39
  away_weak_opp_rank_diff: 24.00
  away_strong_opp_rank_diff: -8.00
  away_weak_opp_point_diff: 105.00
  away_strong_opp_point_diff: -193.00
  away_n_matches_scraped: 3.00

📊 Difference features:
  Diff last 3 WR:    +0.667

============================================================
9️⃣ RANKINGS ÉS EGYÉB FEATURE-ÖK
============================================================
  Home rank: #8 (change: +0)
  Away rank: #16 (change: +0)
✅ Feature-ök összegyűjtve!

,Date,home_team,away_team,home_odds,away_odds,event_id,home_team_mapped,away_team_mapped
204,2025-04-21,FaZe Clan,paiN Gaming,1.04,9.06,8036,FaZe,paiN

📊 DataFrame nézet:

✅ Új sor mentve. (120)

# Other

## Rankings history

In [ ]:
# Rankings history

# Rankings

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from datetime import datetime

def scrape_team_rankings(url):
    driver = webdriver.Chrome()
    driver.get(url)
    
    # Várj, amíg betölt a lista
    wait = WebDriverWait(driver, 10)
    wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".ranked-team.standard-box")))
    
    url_prev = driver.find_element(By.CLASS_NAME, "pagination-prev ").get_attribute("href")

    date_raw = driver.find_element(By.CLASS_NAME, "regional-ranking-header-text").text
    date = date_raw.split("ranking on ")[-1]
    # ordinal ragok eltávolítása
    date_clean = re.sub(r'(\d+)(st|nd|rd|th)', r'\1', date)
    # dátummá alakítás
    date_parsed = pd.to_datetime(date_clean, format="%B %d, %Y")

    rankings = []
    rank_divs = driver.find_elements(By.CSS_SELECTOR, ".ranked-team.standard-box")
    
    for rank_div in rank_divs:
        try:
            rank = rank_div.find_element(By.CLASS_NAME, "position").text
            team_name = rank_div.find_element(By.CLASS_NAME, "name").text
            points = rank_div.find_element(By.CLASS_NAME, "points").text.replace('(', '').replace(')', '').replace(" HLTV points", "").replace(" points", "")
            
            team_link = rank_div.find_element(By.TAG_NAME, "a").get_attribute("href")
            team_id = team_link.split('/')[-2]
            profile_link = rank_div.find_element(By.CLASS_NAME, "moreLink").get_attribute("href")
            
            rankings.append({
                'date': date_parsed,
                'rank': int(rank.replace('#', '')),
                'team_id': team_id,
                'team_name': team_name,
                'points': int(points),
                'profile_link': profile_link
            })
        except Exception as e:
            print(f"Hiba: {e}")
            continue
    
    driver.quit()
    return pd.DataFrame(rankings), url_prev

# Összes rankings leszedése
all_rankings = pd.DataFrame()
url = "https://www.hltv.org/ranking/teams/"
url_prev = ""
while url_prev != "https://www.hltv.org/ranking/teams/2024/december/30":
    rankings, url_prev = scrape_team_rankings(url)
    print(f"Scraping: {url}")
    all_rankings = pd.concat([all_rankings, rankings], ignore_index=True)
    display(rankings.sample(3))
    print(f"+{len(rankings)} (Total: {len(all_rankings)})")
    url = url_prev

In [ ]:
# Save rankings history

all_rankings.to_csv("data/all_rankings2025.csv", index=False)

## OddsPortal

In [ ]:
# Tournaments

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import time

def scrape_oddsportal_cs_links():
    url = "https://www.oddsportal.com/results/#esports"
    driver = webdriver.Chrome()
    driver.get(url)

    wait = WebDriverWait(driver, 15)
    # várjuk, amíg betöltődik legalább 1 tournament link
    wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, "li[data-testid='results-tournament-box'] a")))

    time.sleep(2)  # kis extra wait, hogy minden JS lefusson

    links = driver.find_elements(By.CSS_SELECTOR, "li[data-testid='results-tournament-box'] a")

    data = []
    for link in links:
        try:
            text = link.text.strip()
            href = link.get_attribute("href")
            if text.startswith("Counter-Strike "):
                name = text.replace("Counter-Strike ", "").strip()
                data.append({
                    "Name": name,
                    "url": href
                })
        except Exception as e:
            print(f"⚠️ Hiba egy link feldolgozásánál: {e}")
            continue

    driver.quit()
    df = pd.DataFrame(data)
    print(f"✅ {len(df)} Counter-Strike esemény található az OddsPortalon.")
    return df


# --- Példa futtatás ---
df_oddsportal = scrape_oddsportal_cs_links()
display(df_oddsportal.sample(5))

In [ ]:
# Search tournaments

#df_oddsportal[df_oddsportal.Name == "ESL Pro League Season 21"]["url"].iloc[0]
#df_oddsportal[df_oddsportal.Name.str.contains("IEM")].loc[196, "url"]

In [ ]:
# Odds of tournaments

tours = {'8292': {'name': 'ESL Pro League Season 21',
                  'url': 'https://www.oddsportal.com/esports/counter-strike/counter-strike-esl-pro-league-season-21/results/'},
         '7907': {'name': 'BLAST Open London 2025',
                  'url': 'https://www.oddsportal.com/esports/counter-strike/counter-strike-blast-open/results/'},
         '8038': {'name': 'IEM Cologne 2025',
              'url': 'https://www.oddsportal.com/esports/counter-strike/counter-strike-intel-extreme-masters-cologne/results/'},
         '8036': {'name': 'IEM Melbourne 2025',
              'url': 'https://www.oddsportal.com/esports/counter-strike/counter-strike-iem-melbourne/results/'}
        }


from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import re, time
from datetime import datetime

def scrape_oddsportal_fixed(event_url, headless=False):
    opts = webdriver.ChromeOptions()
    if headless:
        opts.add_argument("--headless=new")
    opts.add_argument("--no-sandbox")
    opts.add_argument("--disable-dev-shm-usage")
    opts.add_argument("user-agent=Mozilla/5.0")
    
    driver = webdriver.Chrome(options=opts)
    driver.get(event_url)
    wait = WebDriverWait(driver, 20)
    
    all_data = []
    page = 1
    
    print(f"Scrape: {event_url}")
    while True:
        print(f"🔍 Oldal {page} feldolgozása...")
        
        # Fokozatos scroll (több elemet tölt be)
        print(f"  📜 Scrolling...")
        for i in range(2):
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight / 4);")
            time.sleep(1.5)  # Lassabb scroll

        # Extra várakozás a renderelésre
        time.sleep(3)
        wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, "div.eventRow")))

        # Extra wait hogy a game-row-k is betöltsenek
        try:
            wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "div[data-testid='game-row']")))
        except:
            print("  ⚠️ Nincs game-row az oldalon")

        event_rows = driver.find_elements(By.CSS_SELECTOR, "div.eventRow")
        all_game_rows_global = driver.find_elements(By.CSS_SELECTOR, "div[data-testid='game-row']")

        # Csak az eventRow-n BELÜLI game-row-kat számoljuk
        game_rows_in_events = []
        for event in event_rows:
            try:
                game_row = event.find_element(By.CSS_SELECTOR, "div[data-testid='game-row']")
                game_rows_in_events.append(game_row)
            except:
                pass

        print(f"  📊 {len(event_rows)} eventRow")
        print(f"  📊 {len(all_game_rows_global)} game-row (GLOBAL - rossz!)")
        print(f"  📊 {len(game_rows_in_events)} game-row (eventRow-kban - jó!)")

        current_date = None
        matches_processed_this_page = 0

        # Dátum keresése MINDEN eventRow-ban - JAVÍTOTT VERZIÓ
        for event in event_rows:
            # dátum keresése data-testid="date-header" elemben
            try:
                date_header = event.find_element(By.CSS_SELECTOR, '[data-testid="date-header"]')
                date_text = date_header.text.strip()
                if any(month in date_text for month in ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']):
                    # Dátum formázása - eltávolítjuk a " -" utáni részt
                    clean_date = date_text.split(' -')[0].strip()
                    current_date = clean_date
                    
                    # Dátum átalakítása YYYY-MM-dd formátumba
                    try:
                        date_obj = datetime.strptime(current_date, '%d %b %Y')
                        current_date = date_obj.strftime('%Y-%m-%d')
                    except ValueError:
                        # Ha nem sikerül átalakítani, marad az eredeti
                        pass
                    # NE continue-oljunk itt! Hagyjuk, hogy a game-row keresés is lefusson
            except:
                pass  # Nincs date-header ebben az eventRow-ban

            # Ha nincs dátum, de van game-row, akkor meccs sor
            try:
                game_row = event.find_element(By.CSS_SELECTOR, "div[data-testid='game-row']")
                #print(game_row.text)
            except:
                continue

            # DEBUG: Van game-row, nézzük mi van benne
            # csapatnevek
            participants = game_row.find_elements(By.CSS_SELECTOR, "a[title]")
            if len(participants) < 2:
                print(f"    ⚠️ SKIP: Kevés participant ({len(participants)}) - nincs 2 csapat")
                continue
            
            home_team = participants[0].get_attribute("title").strip()
            away_team = participants[1].get_attribute("title").strip()
            
            if not home_team or not away_team:
                print(f"    ⚠️ SKIP: Üres csapatnév (home={home_team}, away={away_team})")
                continue
            
            # oddsok
            odds_blocks = event.find_elements(By.CSS_SELECTOR, "div[data-testid^='odd-container'] p")
            odds = []
            for p in odds_blocks:
                try:
                    odds_text = p.text.strip().replace(",", ".")
                    if re.match(r"^\d+(\.\d+)?$", odds_text):
                        odds.append(float(odds_text))
                except:
                    continue
            
            home_odds = odds[0] if len(odds) > 0 else None
            away_odds = odds[1] if len(odds) > 1 else None
            
            if not home_odds or not away_odds:
                print(f"    ⚠️ SKIP: Nincs odds (home={home_odds}, away={away_odds}) - {home_team} vs {away_team}")
                continue
            
            if not current_date:
                print(f"    ⚠️ WARNING: Nincs dátum! - {home_team} vs {away_team}")
                current_date = "Unknown date"  # ← Csak ezt a sort kell hozzáadni

            all_data.append({
                "Date": current_date,
                "home_team": home_team,
                "away_team": away_team,
                "home_odds": home_odds,
                "away_odds": away_odds
            })

            matches_processed_this_page += 1  # ← Számláló növelése

        # Következő oldal ellenőrzése
        try:
            next_button = driver.find_element(By.CSS_SELECTOR, f"a.pagination-link[data-number='{page + 1}']")
            if next_button.is_enabled():
                print(f"➡️ Következő oldal: {page + 1}")
                driver.execute_script("arguments[0].click();", next_button)
                page += 1
                time.sleep(3)  # Várakozás az oldal betöltésére
                continue
            else:
                break
        except:
            # Ha nincs következő oldal, kilépünk
            break

    driver.quit()
    
    df = pd.DataFrame(all_data).drop_duplicates(subset=["Date","home_team","away_team","home_odds","away_odds"])
    print(f"✅ Összesen {len(df)} meccs feldolgozva {page} oldalról.")
    return df

# Futtatás
df_odds = pd.DataFrame()
for id in tours.keys():
    print(f"Scraping {tours[id]['name']}")
    url_tour = tours[id]['url']
    df_odds_tour = scrape_oddsportal_fixed(url_tour, headless=False)
    df_odds_tour.Date = pd.to_datetime(df_odds_tour.Date)
    df_odds_tour['event_id'] = id
    display(df_odds_tour.sample(5))
    
    df_odds = pd.concat([df_odds, df_odds_tour], ignore_index=True)

print(f"Total odds found {len(df_odds)}")

In [ ]:
# Fuzzy matching

import pandas as pd
from fuzzywuzzy import process, fuzz
import json
from pathlib import Path

def fuzzy_match_teams(odds_teams, ranking_teams, save_path="fuzzy_mapping.json", threshold=70):
    """
    Fuzzy matching odds csapatok → rankings csapatok
    
    Args:
        odds_teams: list of team names from odds data
        ranking_teams: list of team names from rankings data  
        save_path: path to save the mapping
        threshold: minimum similarity score (0-100)
    """
    
    # Betöltés korábbi mapping-ből, ha létezik
    mapping = {}
    if Path(save_path).exists():
        with open(save_path, 'r', encoding='utf-8') as f:
            mapping = json.load(f)
        print(f"✅ Korábbi mapping betöltve: {len(mapping)} csapat")
    
    # Csak azokat a csapatokat dolgozzuk fel, amik még nincsenek a mapping-ben
    teams_to_process = [team for team in odds_teams if team not in mapping]
    
    if not teams_to_process:
        print("✅ Minden csapat már mapped!")
        return mapping
    
    print(f"🔍 {len(teams_to_process)} csapat feldolgozása...")
    
    for i, team in enumerate(teams_to_process, 1):
        print(f"\n[{i}/{len(teams_to_process)}] {team}")
        
        # Pontos egyezés
        if team in ranking_teams:
            mapping[team] = team
            print(f"   ✅ Auto match: {team}")
            continue
        
        # Fuzzy matching
        matches = process.extract(team, ranking_teams, limit=5, scorer=fuzz.token_sort_ratio)
        
        # Szűrés threshold alapján
        good_matches = [(match, score) for match, score in matches if score >= threshold]
        
        if len(good_matches) == 1:
            # Egyértelmű match
            best_match, best_score = good_matches[0]
            mapping[team] = best_match
            print(f"   ✅ Auto fuzzy: {team} → {best_match} ({best_score})")
        
        elif len(good_matches) > 1:
            # Több jó match - user dönt
            best_match, best_score = good_matches[0]
            second_match, second_score = good_matches[1]
            
            # Egyértelmű, ha nagy a különbség
            if best_score - second_score >= 15:
                mapping[team] = best_match
                print(f"   ✅ Clear winner: {team} → {best_match} ({best_score})")
            else:
                # User választ
                print(f"   ❓ Több hasonló találat:")
                for j, (match, score) in enumerate(good_matches, 1):
                    print(f"      {j}. {match} ({score})")
                print(f"      0. SKIP (kézi feldolgozás később)")
                
                try:
                    choice = input(f"   Válassz [1-{len(good_matches)}]: ").strip()
                    if choice.isdigit():
                        choice_int = int(choice)
                        if 1 <= choice_int <= len(good_matches):
                            chosen_match = good_matches[choice_int - 1][0]
                            mapping[team] = chosen_match
                            print(f"   👉 Kiválasztva: {team} → {chosen_match}")
                        else:
                            mapping[team] = None
                            print(f"   ⏭️ Skipped: {team}")
                    else:
                        mapping[team] = None
                        print(f"   ⏭️ Skipped: {team}")
                except:
                    mapping[team] = None
                    print(f"   ⏭️ Skipped: {team}")
        else:
            # Nincs jó match
            mapping[team] = None
            print(f"   ❌ No good match found for: {team}")
    
    # Mentés
    with open(save_path, 'w', encoding='utf-8') as f:
        json.dump(mapping, f, indent=2, ensure_ascii=False)
    
    print(f"\n✅ Mapping mentve: {save_path}")
    print(f"📊 Statisztika:")
    print(f"   Összes csapat: {len(mapping)}")
    print(f"   Sikeres match: {sum(1 for v in mapping.values() if v is not None)}")
    print(f"   Nincs match: {sum(1 for v in mapping.values() if v is None)}")
    
    return mapping

# Használat:
def apply_fuzzy_mapping(df_odds, rankings, mapping_path="fuzzy_mapping.json"):
    """Apply fuzzy mapping to merge odds with rankings"""
    
    # Betöltés mapping
    with open(mapping_path, 'r', encoding='utf-8') as f:
        mapping = json.load(f)
    
    # Csapatok összekapcsolása
    df_odds['home_team_mapped'] = df_odds['home_team'].map(mapping)
    df_odds['away_team_mapped'] = df_odds['away_team'].map(mapping)
    
    # Rankings merge
    rankings_clean = rankings.drop_duplicates('team_name')
    
    df_merged = df_odds.merge(
        rankings_clean, 
        left_on='home_team_mapped', 
        right_on='team_name', 
        how='left',
        suffixes=('', '_home')
    ).merge(
        rankings_clean,
        left_on='away_team_mapped', 
        right_on='team_name', 
        how='left',
        suffixes=('_home', '_away')
    )
    
    # Statisztika
    matched_home = df_merged['home_team_mapped'].notna().sum()
    matched_away = df_merged['away_team_mapped'].notna().sum()
    total_matches = len(df_merged)
    
    print(f"📊 Merge statisztika:")
    print(f"   Home team matched: {matched_home}/{total_matches} ({matched_home/total_matches*100:.1f}%)")
    print(f"   Away team matched: {matched_away}/{total_matches} ({matched_away/total_matches*100:.1f}%)")
    
    return df_merged

# PÉLDA HASZNÁLAT:
if __name__ == "__main__":
    # 2. Csapatok listázása
    odds_teams = pd.unique([*df_odds.home_team.unique(), *df_odds.away_team.unique()])
    ranking_teams = rankings.team_name.unique()
    
    print(f"📊 Adatok:")
    print(f"   Odds csapatok: {len(odds_teams)}")
    print(f"   Ranking csapatok: {len(ranking_teams)}")
    
    # 3. Fuzzy matching futtatása
    mapping = fuzzy_match_teams(odds_teams, ranking_teams, "team_mapping.json")
    
    # 4. Merge elvégzése
    df_final = apply_fuzzy_mapping(df_odds, rankings, "team_mapping.json")

In [ ]:
# Save dem odds

df_odds.to_csv("odds.csv", index=False)

In [ ]:
# Manual search
for t in rankings.team_name.unique():
    if 'nrg' in t.lower():
        print(t)

In [ ]:
# Check if names in dataframes

with open("team_mapping.json", 'r', encoding='utf-8') as f:
    mapping = json.load(f)

for t_op, t_hltv in mapping.items():
    if (t_op in odds_teams) & (t_hltv in rankings.team_name.unique()):
        pass
    else:
        print(f"Error for {t_op}/{t_hltv}")